### ISSUE TITLE
CSCAP Download Tool omnibus

### ISSUE THREAD

**Issue by akrherz** [isudatateam/datateam#10]
Feedback from Steph et al and general TODO list:

- [x] the disabling of non-available options is too subtle, perhaps remove entirely or something else
- [x] Have a 'select-all' button to check all-available for that page
- [x] Add subheadings under the treatments `Tillage`, `Rotation`, etc
- [x] ~~Order treatments as found in the site-treatments spreadsheet~~, (no longer makes sense with headings?)
- [x] Make clicking on the panel headings work along with the `next` and `previous` buttons
- [x] convert any valid column headings of `valid` to be `date` instead
- [x] add management, pesticides, and other data from the management gadget to the export
- [x] implement conversion of fertilzer rates/percentages into straight rates, see comment below
- [x] resort management export to match column order (left to right) in entry sheet 
- [x] Gio email on 26 May 2017 suggested aggregates to lump various items together, further discussed on 2 June and think I have a means forward for implementation
- [x] ~~add an Unselect All button next to Select All button~~ 
- [x] add PlotID tab to export files with plot identifiera data
- [x] plotid filtering does not happen on the actual export like it does for the interface

**Comment by akrherz** [comment]
There was an email discussion thread on what to do about the `-1` fertilizer values denoted in the download file.  This nomenclature is a daryl-ism to keep some things straight with the web gadget form.  So the question at hand is how to straighten this out in the downloaded data.  I think the best option would be to covert the columns to `kg/ha` and unset the `product_rate` column when it is -1

**Comment by loriabendroth** [comment]
Your work here looks good Daryl - looked at your code and the exported values.

**Comment by loriabendroth** [comment]
@akrherz what does your last item in list above mean? forget "unselect" edit; not critical.

**Comment by akrherz** [comment]
@loriabendroth When you click on various treatments, rotations, etc within the download interface, the effect is to filter plotids that are relevant for those treatments, etc.  When it comes time to actually download, the filtering is more relaxed and basically only the combination sites, years, and variables.  We discussed this issue at our last meeting and I think determined that it was not a huge deal.
