### ISSUE TITLE
Add CSCAP weather data to download interface

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#11]
- [x] Change "Data" tab to "Research Data". Create a new tab "Weather Data" - or if you think better to have automatically with the rest of the data, then fine to include along with other data tabs under Research Data.

- [x] Bring in weather data from https://sites.google.com/site/sustainablecorn/database/currentweather

- [x] Bring in all data variables except for GDD with base of 40. For model formatted exports, possible to have those separate from measured variables? 

- [x] Include header text (reword as you see fit):
Supplementary weather data are available for Sustainable Corn research sites. This dataset is provided from nearby weather networks and curated by Sustainable Corn personnel. It is most representative and accurate for pairing with these research sites. The data is collected from a variety of sources, including the National Climatic Data Center, National Weather Service, and State Climatologists.  These entities revise their data and will produce updated values that are reprocessed into this archive.  

- [x] Include reference to this page for more details regarding source, history, and gaps for data:
https://mesonet.agron.iastate.edu/info/datasets/climodat.html

**Comment by loriabendroth** [comment]
Include reference to this page for more details regarding source, history, and gaps for data:
https://mesonet.agron.iastate.edu/info/datasets/climodat.html

**Comment by akrherz** [comment]
Regarding the third item of moving the exported formats.  I did move them down in the listing, which should help the confusion some, I hope.  I have a related IEM issue on the confusion with that model outputs showing up in the variable listing akrherz/iem#113

**Comment by loriabendroth** [comment]
@akrherz this looks great. I like how you separated the model outputs into a separate list. Works well.
