### ISSUE TITLE
Add more detailed header rows to data export

### ISSUE THREAD

**Issue by akrherz** [isudatateam/datateam#114]
Currently, the exported data spreadsheets have 1 cryptic header row.  We can likely do better with the following pseudo code supporting the necessary operations

```python
# Add header row at the beginning of the data frame
data = []
data.append(rowdict)
df = pd.concat([pd.DataFrame(data), df], ignore_index=True)
# freeze the top x rows with Excel writer
worksheet.freeze_panes(x, 0)
```

The header metadata rows can be derived from the smartsheet content that is synced to the database, me thinks...

**Comment by akrherz** [comment]
@giorgichi @loriabendroth what do you think of this example Excel file showing what my development code generated for the Agronomic tab?

[cscap.xlsx](https://github.com/isudatateam/datateam/files/1422165/cscap.xlsx)

**Comment by loriabendroth** [comment]
@akrherz I'm looking at it on my phone so not ideal viewing but I think conceptually it is great. I was going to say I could provide my abbreviations for the headers such as "cppa" for corn plant population. But i don't know that adding in new shorthand codes is that useful or helpful. Using the descriptors here is better and less likely for misinterpretation.

**Comment by giorgichi** [comment]
@akrherz, this is GREAT! I like that you added units and froze the header rows. Can you implement this for all tabs?

**Comment by akrherz** [comment]
OK, an implementation is done for four of the tabs now

**Comment by loriabendroth** [comment]
@akrherz this is based on the column "Short Description" in SS, correct? Assume it syncs everyday so if I make changes it automatically updates? Can you also do this for tabs Plot Identifiers, GHG, and IPM?

**Comment by akrherz** [comment]
@loriabendroth regarding
> this is based on the column "Short Description" in SS, correct? 
Correct.

> Assume it syncs everyday so if I make changes it automatically updates?
Correct

> Can you also do this for tabs Plot Identifiers, GHG, and IPM?
done

**Comment by loriabendroth** [comment]
@akrherz looks great. Few issues to address when able:

- [ ] add short description and units also for Drainage Control Structure Mngt tab.

- [ ] Duplication exists in the “description” and “units” (rows 2 and 3) of the exported file when the variable name (row 1) is used in multiple places. It is populating the text twice. See listing below of 6 instances of this. To get around, need to use Spreadsheet tab in conjunction with variable name to place these descriptive headers and units. 

Field Operations tab > depth
Soil tab > depth
GHG tab > method
Pesticides tab > method
Field Operations tab > operation
Pesticides tab > operation

- [ ] where are column headings coming from for “Site Metadata” tab? I have changed them in the original sheet (https://docs.google.com/spreadsheets/d/1tQvw-TQFtBI6xcsbZpaCHtYF7oKZEXNXy-CZHBr8Lh8/edit#gid=0) and also ensured they match in the SS data dictionary but the exported file doesn’t match.

**Comment by akrherz** [comment]
@loriabendroth regarding
> where are column headings coming from for “Site Metadata” tab?

The export has a manual translation from stored column names to what they should appear as within the export.  you'll need to list out which columns are missing and/or the translation from what's now used in the google sheet to what it should look like in the export.

**Comment by loriabendroth** [comment]
- [ ] @akrherz here are column headings that need to change in export. If not listed, no changes needed. The old is what it is right now. 
Old -> New
City (nearest) -> city
Landscape Slope (%) -> landscape slope
Number of Plots/ Subplots -> number of plots
Raw LonLat -> raw LonLat
Site Area (ha) -> site area
Tile Spacing (m) -> tile spacing

- [ ] Tile depth (column V) should be included in export but is not. Please add. It should be "tile depth" as column heading. 
https://docs.google.com/spreadsheets/d/1tQvw-TQFtBI6xcsbZpaCHtYF7oKZEXNXy-CZHBr8Lh8/edit?hl=en_US&pli=1&hl=en_US&pli=1#gid=0

- [ ] Add description and units to Site Metadata tab too - like you have done in other sheets by adding it as second and third rows.

**Comment by loriabendroth** [comment]
@akrherz, not sure if you were wondering where to pull in site metadata descriptions, if so they are rows 70-79 here: https://app.smartsheet.com/b/home?lx=pmYOq3M3XZWvMXl6OM_MZQ

**Comment by akrherz** [comment]
@loriabendroth regarding
> site metadata descriptions

The columns need to match 1 to 1, so need eight rows for the lat/lon columns

**Comment by loriabendroth** [comment]
@akrherz better now?

**Comment by giorgichi** [comment]
@akrherz Lori added the problematic entries explicitly, so it should work now.

**Comment by akrherz** [comment]
Indeed, looks good to me now

**Comment by giorgichi** [comment]
@akrherz, could you change the format of x axis for CSCAP Water Table plotting tool? Currently is shows %b'%y (month and year), instead of %d.%b (date and month), as we have in TD plotting tool. 

p.s. I spent some time trying to find the piece of code that controls this feature of the plot, but failed.

**Comment by akrherz** [comment]
@giorgichi I think it was just a matter of the CSCAP plotting tools using an older highcharts library than TD was using.  Better now?

**Comment by giorgichi** [comment]
@akrherz Yes, it's working perfectly! 

"CSCAP plotting tools using an older highcharts library than TD was using" - this explains why I could not find the problem in the script.

**Comment by giorgichi** [comment]
We might need to reconsider this implementation again.
