### ISSUE TITLE
Add CSCAP map to download interface

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#13]
Create Research Site tab at /dl with Google Map embedded. This is a public copy of the CSCAP internal map. On-farm and organic sites have been removed. Will add descriptive text to top of page in future - for now, just add map.
https://drive.google.com/open?id=1VQuDqTRkO5RPvIgWMODYvBLWU1A&usp=sharing

**Comment by akrherz** [comment]
Got the same permission error as before.  Google asked me to contact you via a form, so lets see if that yields the right permissions.  Maybe the issue is that the file is in a shared google drive without the right permissions?

**Comment by loriabendroth** [comment]
I see that. Just changed ownership to api. This map is getting the better of me.

**Comment by akrherz** [comment]
Got it embedded now, but the default view is wonky.  Will wait to see if a config change I just made fixes the issue.

**Comment by loriabendroth** [comment]
Gio, can you look at unchecked SS google map issues. There should be 3 new ones. I see they do not match the watershed boundaries and need to be corrected. Make changes in external map; dont bother with internal map. We can just delete that one eventually from internal website.

**Comment by loriabendroth** [comment]
@akrherz nice job with the map!
