### ISSUE TITLE
Changes to codes, text

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#134]
Few final items to address asap:

- [x] change data year in citation from 2016 to 2017. Do this here and in email: https://datateam.agron.iastate.edu/cscap/dl/#tab_data
https://datateam.agron.iastate.edu/cscap/usage.phtml

- [x] Convert TIL4 to TIL1v in export

- [x] Remove “(CT)” and “(NT)” under Treatments/Tillage. Also put a hyphen in “No-tillage”. Remove “Tillage (2011), no tillage (2012-2015)” also since TIL4 is becoming TIL1v. 
https://datateam.agron.iastate.edu/cscap/dl/#tab_data

- [x] in email on 10/12, ROT59 was changed to ROT36 in plotids and agronomic sheet of ISUAG.USB. ROT59 was “early kill” however and that detail is lost when converted to ROT36. Which then makes the spreadsheet not useable in regards to timing of kill if we ever need it. I think this should be reverted in plotids and agronomic sheet and instead in exported file only change ROT59 to ROT36. 

- [x] ROT is little off at ISUAG.USB. Please adjust as follows:
https://github.com/isudatateam/datateam/blob/master/htdocs/cscap/dl/dl.py#L87

- ROT60 was converted to ROT36v for export. Not needed. Just exclude all ROT60 treatments from export across all sites.
- ROT61 was converted to ROT1v; convert to ROT5v instead. ROT61 only occurs at ISUAG.USB so no other changes needed. 
- ROT57 should be converted to ROT37v for export. Only occurs at ISUAG.USB so no other changes needed. 
 
- [x] in db, ROT60 should be corn w/ rye and soybean w/ rye alternating years. It looks like it is corn w/ rye and just soybean. This is not important for export function because ROT60 will not be exported but is important for correctness in db.

- [x] for export, please change all occurrences of: 
ROT54 to ROT5v
ROT55 to ROT37v
ROT56 to ROT1v

- [x] Listing of “Corn-corn-soybean-corn-soybean” under Treatments is not needed. The other variants are not included so unsure why this one remains. This is ROT41 which is now ROT5v in the export – so most similar to first in listing (“Corn-soybean”). 

- [x] in “Site Metadata” tab, the column “tile spacing” has TBD for some sites but in site master it is “Unknown”. Should be represented as “Unknown” in export instead of TBD. This is also true for NWREC tile depth. 

- [x] the handling of water headers are different than other data sets. Make the water data similar with the water codes (“element or value display name”) also included, so that users can align with DD directly and make sense of it. Right now they tend to be short descriptions instead. Need to include abbreviation, short description, and units. 

- [x] for all water data, change the “Spreadsheet Tab” in the DD from “n/a” to “Water”. That will help group similar variables. 

- [x] export all water data as compiled csv files for upload to NAL

- [x] “Discharge (mm)” and “WAT9” have empty “Acceptable Values” in DD. Fill in. 

- [x] Add this text to https://datateam.agron.iastate.edu/cscap/dl/#tab_wdata, underneath the hyperlinked webpages. 
“Tile flow and water quality data for the BRADFORD.A experimental site are not included here due to conditions that are distinct from other drainage sites. Drainage tile were installed in the clay layer of the soil profile which impacted the amount of water through the system and out from the site. Contact sustainablecorn@iastate.edu for access to this data.”

- [x] revert removal of 2015 agronomic data for WOOSTER.COV 

- [x] remove 4 "data plotting" tools from drop down list if possible. People will access within Research Data tab instead. 

- [x] remove "manurecomposition" from management export. I have already switched SS DD column "CSCAP DB Export" from yes to no. 

- [x] do not export "seed" entries under Pesticides tab > operation for exported file. Keep in db though.

- [x] "biomassdate1" and "biomassdate2" are all coming in as missing data if a date is not included. But in original sheet, they are "n/a" or "unknown" if a date is not stated. This is how it should be in export.  https://docs.google.com/spreadsheets/d/1CdPi6IEnO3T35t-OFQajKYzFLpu7hwOaWdL2FG1_kVA/edit#gid=0

- [x] "outletdate" under Drainage tab is not populating "unknown" and "n/a" in the exported file from the management sheet. Instead they are coming in blank. 
https://docs.google.com/spreadsheets/d/1CdPi6IEnO3T35t-OFQajKYzFLpu7hwOaWdL2FG1_kVA/edit#gid=1897822480

- [x] Discharge (mm) is missing a number range in the DD for its Acceptable Value. Populate this.

**Comment by loriabendroth** [comment]
@giorgichi thanks for csv files. For the NAL, we'll just upload daily values (not hourly) and if people want finer, they come to our interface to download. I am pretty sure this is what we discussed earlier and decided was best for consistency across sites. Can you aggregate and reload to Google?

**Comment by giorgichi** [comment]
@loriabendroth, how do you want to aggregate water table depth?

**Comment by giorgichi** [comment]
CSV files with daily water data can be found here:
https://drive.google.com/drive/folders/0B6ZGw0coobCxdUtsUmFHZ2xiWTg

**Comment by loriabendroth** [comment]
@giorgichi daily water data looks good. Can you add headers to match how agro, soil data are? See 10th item above.

**Comment by giorgichi** [comment]
CSV files with new headings can be found here:
https://drive.google.com/drive/folders/0B6ZGw0coobCxdUtsUmFHZ2xiWTg

**Comment by giorgichi** [comment]
@akrherz - about the error that Lori found with ROT60.

- changed "Soybean" with "Soybean w/Rye" in following files: "xref Rotation" and "ISUAG.USB Agronomic Data".
- **need to update "plot identifier" table in db**

**Comment by giorgichi** [comment]
@loriabendroth - is "Site Treatments" sheet KELLOG and MASON are checked for ROT59 and ROT60, but could not find plots with that rotation in corresponding plot identifiers.

**Comment by giorgichi** [comment]
@loriabendroth - in the DD it is explained why there is no range for Discharge.

**Comment by loriabendroth** [comment]
@giorgichi ok, I see about discharge. Added a statement that it depends on time period.

**Comment by akrherz** [comment]
@loriabendroth regarding
> "biomassdate1" and "biomassdate2" are all coming in as missing data if a date is not included. But in original sheet, they are "n/a" or "unknown" if a date is not stated. This is how it should be in export.

The ISU database only has the option to store a 'null' or an actual date, so it is one or the other.  The storage is not a string value.  For the export, missing values are all treated the same.  So there isn't a means to account for this request.

**Comment by giorgichi** [comment]
@akrherz I thought the same about the last two open requests. My guess was that both "biomass date" and "outlet date" are stored as **date-time** in db. The only way to implement these requests is to change that column type into **character** in db. But I do not want to know what will be the implications of this alteration :)

**Comment by loriabendroth** [comment]
@akrherz got it. I see that other dates are handled the same way - I had missed that.

**Comment by loriabendroth** [comment]
@akrherz in the Notes tab, the decimal places to round to are exported. I was thinking that was just for you to use and not export. Possible to exclude?

**Comment by akrherz** [comment]
@loriabendroth regarding
> in the Notes tab, the decimal places to round to are exported. I was thinking that was just for you to use and not export. Possible to exclude?

I am not seeing this currently happen.  I see these columns
* uniqueid 
* overarching_data_category 
* data_type 
* growing_season 
* comments

Oh, you mean "Data Dictionary"? if so, done

**Comment by loriabendroth** [comment]
@akrherz thanks for reading my mind.

**Comment by akrherz** [comment]
@giorgichi regarding
> need to update "plot identifier" table in db

this is done now
