### ISSUE TITLE
Add GHG, Water, and IPM tabs, data to /dl

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#14]
Need to bring in additional data to download interface. Because the sampling varies for these as compared to agronomic/soil you do not need to integrate with existing interface if clumsy. Can create new tabs that make it clear they are separate sets. So that people simply download those on their own; plot IDs match so can easily align if they want. 

- [x] GHG: Bring in sites as listed here https://docs.google.com/spreadsheets/d/1PKK-vWuOryYFOSYSgt4TosrjIDX_F-opHOvrEo5q-i4/edit?hl=en_US&hl=en_US#gid=0. 

- [x] Water: Two options exist - direct to visualization/aggregate/export tools or build download options for this data type.

- [x] IPM: not high priority; do last. Lori will sort out some column heading issues with entered data to-date.

**Comment by loriabendroth** [comment]
@giorgichi sent GHG file on 6/19/17 to ingest. 

IPM data - we'll only bring in Dunbar data; do not bring in other USB data (8 Google sheets here: https://drive.google.com/drive/u/2/folders/0B4fyEPcRW7IscDcweEwxUFV3YkU) because of low perceived value; too few of sites and limited measurements available.

**Comment by akrherz** [comment]
The GHG file @giorgichi sent on 19 Jun 2017 has been ingested and added to the dl form

**Comment by akrherz** [comment]
The IPM file @giorgichi sent on 22 Jun 2017 has been ingested and added to the dl form
