### ISSUE TITLE
Eliminate issues w early-late at MI sites

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#146]
Only two items needed to wrap this up:

- [x] KELLOGG plot ids - use the second tab instead of first.
https://docs.google.com/spreadsheets/d/1f-zBjMRLIYt7cgI2IQg108AfXBz43jJtMJBnbrfb2k0/edit#gid=11692408

- [x] MASON plot ids - use the second tab instead of first.
https://docs.google.com/spreadsheets/d/1QfKv-QgSrLtCiF4dF5idI7wDJXFG13UZnAqicEjz1u4/edit#gid=1608082382

Note for memory sake:
I removed the early/late plots from GHG data for KELLOGG in 2014 since site personnel did not clarify which plots were which treatments. All other GHG data could be reconciled based on the maps that I had so that the "early" plots were used for export. GHG data is different from soil and agro in this way.
Agronomic and Soil Nitrate data for KELLOGG and MASON in 2014 and 2015 have been averaged across the two treatments earlier by Gio (May 2016). Put a note explaining this in SS site sheets. Ideal case is to work backwards and revert to exporting early plots to match GHG data but this also would remove some plots because of missing plot identifier information. It is not high value so leave as is.

**Comment by akrherz** [comment]
ingested
