### ISSUE TITLE
Compile data for Strock et al. paper

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#151]
Steps: 

- [x] add soil types into either plot identifier (like with CSCAP) or in site metadata/history sheet. Pull from Web Soil Survey. This includes: Soil Series Name (1), Soil Texture Series (1), Soil Series Description (1), Soil Taxonomic Class (1).

Parameters of data to pull specifically for sites:
- [x] AUGLA - Auglaize County, OH
- [ ] BATH_A - Beaufort County, NC  *n/a
- [x] CRAWF - Crawford County, OH
- [x] DEFI_M - Defiance County, OH
- [x] DPAC - Randolph County, IN
- [ ] FAIRM - Richland County, MN  *n/a
- [x] HARDIN - Hardin County, OH
- [x] HARDIN_NW - Hardin County, OH
- [x] HENRY - Henry County, OH
- [x] HICKS_B - Redwood County, MN
- [x] MUDS2 - Knox County, MO
- [ ] MUDS3_OLD - Knox County, MO  *n/a
- [x] MUDS4 - Knox County, MO
- [x] SERF_IA - Washington County, IA
- [x] SERF_SD - Clay County, SD
- [x] STJOHNS - Auglaize County, OH
- [x] STORY - Story County, IA
- [x] TIDE_OLD - Washington County, NC
- [ ] UBWC - Delaware County, OH  *n/a

Send four spreadsheets to members:

SPREADSHEET 1
- [x] only include years with corn. Spreadsheet will include site, year, plot, treatment, maize yield.
- [x] calculate percent yield relative to maximum yield for each site-year, have this column to the right of yield (kg ha-1).

SPREADSHEET 2 
- [x] management data per site year: 
FD yes/no
CD_season yes/no
CD_winter yes/no

SPREADSHEET 3 
- [x] daily precipitation for each all years; members will aggregate April 1 – Sept 30 for growing season and Oct 1 – Mar 31 for non-growing season. Therefore, need to include all years even if some don’t have corn yield because of summing across calendar years.

SPREADSHEET 4
- [x] export drainage system description from methods entered to-date. Provide this to understand whether site is potentially under or over designed.

**Comment by loriabendroth** [comment]
Forgot to mention that replicate should be included in spreadsheet 1. And that once soil data is compiled, that can be merged with Spreadsheet 1 also.

**Comment by giorgichi** [comment]
Refined list of sites:
- [ ] AUGLA - Auglaize County, OH
- [ ] CRAWF - Crawford County, OH
- [ ] DEFI_M - Defiance County, OH
- [ ] DPAC - Randolph County, IN
- [ ] HARDIN - Hardin County, OH
- [ ] HARDIN_NW - Hardin County, OH
- [ ] HENRY - Henry County, OH
- [ ] HICKS_B - Redwood County, MN
- [ ] MUDS2 - Knox County, MO
- [ ] MUDS4 - Knox County, MO
- [ ] SERF_IA - Washington County, IA
- [ ] SERF_SD - Clay County, SD
- [ ] STJOHNS - Auglaize County, OH
- [ ] STORY - Story County, IA
- [ ] TIDE_OLD - Washington County, NC

**Comment by giorgichi** [comment]
@loriabendroth - should we exclude popcorn too?

**Comment by loriabendroth** [comment]
@giorgichi yes, exclude it for now
