### ISSUE TITLE
Change sentence in citation

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#155]
OK, was going to try and change myself... but cant quite figure out. 

Can you replace the first sentence with the following sentence at 3 locations (email, https://datateam.agron.iastate.edu/cscap/usage.phtml, and https://datateam.agron.iastate.edu/cscap/dl/#tab_data)

OLD SENTENCE:
By using these data, you acknowledge and agree to cite the data in all publications or presentations using the following format.

NEW SENTENCE:
Please reference this data set in publications as:

**Comment by loriabendroth** [comment]
@akrherz @giorgichi check this - none appear to have been changed. still as "By using these data, you acknowledge and agree to cite the data in all publications or presentations using the following format."

**Comment by akrherz** [comment]
@loriabendroth I think I forgot to update the website, better now?

**Comment by loriabendroth** [comment]
@akrherz yep looks good. email changed also?

**Comment by akrherz** [comment]
@loriabendroth yes
