### ISSUE TITLE
Edit to Publications tab

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#159]
- [x] Add this statement to end of header: 

"... major University library. If a web link is not provided, contact sustainablecorn@iastate.edu for a PDF copy."

- [ ] the thesis/diss with "N/A" in online source column are missing from the listing. The N/A entries exist in the SS file "Sus Corn Theses & Dissertations_ExternalWeb" so it is a transfer issue.

**Comment by akrherz** [comment]
@loriabendroth regarding
> the thesis/diss with "N/A" in online source column are missing from the listing. The N/A entries exist in the SS file "Sus Corn Theses & Dissertations_ExternalWeb" so it is a transfer issue.

see the first bullet on issue #27

**Comment by loriabendroth** [comment]
@akrherz oh yes, that is what I said but not what I meant! Sorry. I meant to just not show the text "N/A" in the web listing but to keep the entry in the list. Make sense?
