### ISSUE TITLE
Upload weather stations to TD internal

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#162]
Add research sites to drop-down weather tool for TD (https://sites.google.com/site/transformingdrainage/database/weather-data-download). This is a repeat of email from Gio on 12/19/2017 btw. The attached file notes which sites have weather data on website and which dont (YES/NO). 

~~- [ ] bring in all NO sites if possible. IEM climate site provided in some cases and lat/long in others.~~ 

[IEM_Weather_Stations.xlsx](https://github.com/isudatateam/datateam/files/1643966/IEM_Weather_Stations.xlsx)

- [x] rename HICKS_R to HICKS_S in drop-down
- [x] reorder all sites in dropdown so in alphabetical order; some are and some are not. 
- [x] remove "Site 1" and "Site 2" which follow BEAR and MAASS, respectively, in dropdown

**Comment by giorgichi** [comment]
@akrherz, I cannot find a code that runs the TD Weather gadget. If you send a link I will try to address these and other future issues.

**Comment by akrherz** [comment]
@giorgichi the TD weather download widget is contained within the old-style Google Gadgets.  I have transfered the `cscap-google-gadgets` repository to the ISUDataTeam organization.  The `td-wx-download.xml` is the gadget found in the repo.

**Comment by loriabendroth** [comment]
also need to add 2017 data to drop-down options. Stops at 2016 now.

**Comment by loriabendroth** [comment]
Definite progress on this - thanks. Still need to add: 
IA > BEAR2, DIKE, HICKORY, SHEARER, (MILLER - will delete in future so ignore this site)
MN > WILKIN1-3
NC > BATH_A, BATH_R, TIDE_OLD

I understand the issue with NC sites. @giorgichi, which data did Katie use for recent weather plotting exercise?  

BEAR2 has same lat/long as BEAR, so can just repeat data for that site like we do with other sites that have same weather station. For other IA sites, we have lat/long here, can you add based off of these? Skip MILLER site because it will be deleted in the future.  https://docs.google.com/spreadsheets/d/1oZ2NEmoa0XHSGTWKaBLt0DJK1kIbpWO6iSZ0I2OE2gA/edit#gid=0 

WILKIN sites have lat/long also, select closest weather station based off of these?

**Comment by giorgichi** [comment]
@loriabendroth - I do not know the name of the weather station. But I assume it should be in the spreadsheet that Katie send if you look for it.

**Comment by giorgichi** [comment]
the station name, according to the spreadsheet is EWN.

**Comment by giorgichi** [comment]
[Precipitation data.xlsx](https://github.com/isudatateam/datateam/files/1729055/Precipitation.data.xlsx)
This is a file Katie sent to us.

**Comment by loriabendroth** [comment]
This is an ASOS site. Katie is going to check if COOP site exists instead for NC. So those sites can wait to be updated. Rest can be done.

**Comment by loriabendroth** [comment]
@giorgichi , in the external export for on-site weather data (https://datateam.agron.iastate.edu/td/dl/#tab_wxdata), no data exists for WILKIN 1-3 yet in the master data collected, it says that 2017 and 2018 exist. I believe these master sheets were not maintained after awhile though. Can you confirm that WILKIN should not have onsite weather data in external? MN_Redwood2 is also missing but should have onsite data.

**Comment by giorgichi** [comment]
@loriabendroth, I updated site data collected sheets by removing on-site weather data for WILKIN 1-3. We never recived that data from Jeppe.

**Comment by giorgichi** [comment]
@loriabendroth, MN_Redwood1 does not have actual on-site data. It is assumed that the weather station at MN_Redwood2 represents both locations. As a result of this arrangement, there were two options - to duplicate weather data for each site, or report only for one. I think duplication of the same weather data is not the best solution, so I assigned the weather data to the most relevant site between these two (MN_Redwood1).

**Comment by loriabendroth** [comment]
> @loriabendroth, MN_Redwood1 does not have actual on-site data. It is assumed that the weather station at MN_Redwood2 represents both locations. As a result of this arrangement, there were two options - to duplicate weather data for each site, or report only for one. I think duplication of the same weather data is not the best solution, so I assigned the weather data to the most relevant site between these two (MN_Redwood1).

@giorgichi , I see the change to only having one of the sites listed and that is fine. Wouldn't it be Redwood2 though (rather than 1) if that is where the station is located?

**Comment by loriabendroth** [comment]
@giorgichi , please address last item here so we can close out.

**Comment by loriabendroth** [comment]
done, close out
