### ISSUE TITLE
Follow-up from TD Data Reviews (DR)

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#164]
Here are a list of items needed based on DR conversations, some of which are necessary for team members to enter data. Others are to have things represented correctly and clear for members. I will add more to this list as I progress through lists and am sure you have other items on your list too.

- [x] *update plot identifier sheet with correct experimental design for SWROC. Update agronomic and soil entry spreadsheets with these identifiers. Also, move plot maps to shared folder as only one exists now that is vague. 
https://docs.google.com/spreadsheets/d/1xA-9YIe68gg5-HA_ivhvT-Zx-fpWJJGBGS40M19DNLU/edit#gid=0
https://drive.google.com/drive/folders/0B-gT6NSY_M5Hfnl1QkxWR1Y0b0RnMWJCeU1wVWlPSVF1N3FsYTI5Vkt1ZldjTGJ1TnZudmc 

- [x] *remove MILLER site and replace with BENTON-TAMA on internal website, spreadsheets, and Google map. BT is in Tama county during 2016 & 2017 with 9 wells and a tipping bucket.

- [x] record crop for each saturated buffer site-year; no other mngt data needed. Can add this by creating planting and harvesting operations for each year but with date "unknown". Not sure where else to put this information for users. 

- [x] check crop rotation at BATH_R, I thought Mohamed said wheat and soybean. But this may be for 2017 and corn for 2018. Do you recall? Update site master data collected and crop rotation represented in TD site measurement and instrumentation file.

- [x] *change TIDE_OLD to TIDE in methods form and backend sheet 

- [x] combine precip data with temp file (https://docs.google.com/spreadsheets/d/1M3zewHuUs-RuzN_rMDIY4YDVjZorPtr4Ed2cSNNg438/htmlview) into one weather file for TIDE_OLD 2007-2012. Rename column headings to match dictionary codes. Also convert temp data from F to C. Then upload this sheet to WEATHER EXPORT page with hyperlink to it for users who want data for the period of time research was conducted at site. 

- [x] create plot id spreadsheet for ACRE so we have a master copy that Daryl can cross-check eventually to verify all files have same field IDs, etc. https://drive.google.com/drive/u/0/folders/0B6ZGw0coobCxc1V2cDNHZHNyNjg

- [x] add DRAINMOD to weather drop down for export options. This was an earlier request that got lost in time. Possible? 

- [x] work with Matt(?) to remove problematic water table values from SERF_IA for TD and sync with CSCAP. In DR, plot S1 and S8 were identified as problematic (see SS notes). Tile flow issues may also exist with S1. Provide a list of entries changed (date and what change occurred) as this will be uploaded to versioning log.

- [x] work with Matt(?) regarding SERF_IA soil moisture values, Matt commented that not confident below 60 cm; remove 100 cm from TD and CSCAP??

- [x] work with Lindsay to go back through STJOHNS WT data and check for outliers/accuracy.

- [x] Review max flows for Allred sites and truncate high values and eliminate negative flows as requested by Barry. Set negative flows to 0.

- [x] FAIRM was completely redesigned in 2011; think we need to split this into "OLD" and "NEW" fields likely so users understand site data. Or does it matter since don't have data from those earlier years? Originally was going to be 2008-2018 but have no pre-2011 data except for soil samples. 

- [x] DEFI_R management form reports some operations for 11N and 11S plots. We only have yield data for plot 11 though.  Add N or S designation and cross-check that plot ID master aligns with all entered plot IDs for this site. 

- [x] Create water entry forms for people based on those missing here that are applicable - such as HICKS_S, MUDS1, and BATH_R. Link to the hyperlink list here (https://sites.google.com/site/transformingdrainage/researchsites/other-sites/site-description) and on individual site tabs.

**Comment by akrherz** [comment]
regarding 
> add DRAINMOD to weather drop down for export options. This was an earlier request that got lost in time. Possible?

If the need is only for daily data, this should be doable.  Just need some examples of the file formats.

**Comment by giorgichi** [comment]
> FAIRM was completely redesigned in 2011; think we need to split this into "OLD" and "NEW" fields likely so users understand site data. Or does it matter since don't have data from those earlier years? Originally was going to be 2008-2018 but have no pre-2011 data except for soil samples.

This does not matter.

**Comment by giorgichi** [comment]
@loriabendroth - you've been working with Stuart for the last two months about ACRE yield data. Did you manage to finalize it, or are you going to exclude some plots?

**Comment by loriabendroth** [comment]
@giorgichi see email I sent on 4/20 to Stuart. Yield data will not be used; it has been deleted from master data collected sheet. So plot ids should only be those relevant for water data.

**Comment by loriabendroth** [comment]
@giorgichi I want DRAINMOD included in weather dropdown if possible. Can you send @akrherz an example of files that Lamyaa needed for weather data that you formatted?

**Comment by giorgichi** [comment]
@loriabendroth, I am not sure it is a good idea to add DRAINMOD option to the dropdown list, but I assume you already looked at it and made this decision accordingly. 
@akrherz you can use information on [this webpage](http://www4.ncsu.edu/~bdphilli/drainmod/help_file/index.html?weather_format.htm) to format weather data for DRAINMOD input.

**Comment by akrherz** [comment]
@giorgichi if I am reading that correctly, you can't directly produce the DRAINMOD weather file format but you have to produce columnar data that is manually imported into the program?

**Comment by loriabendroth** [comment]
@giorgichi @akrherz I knew it was a bit more challenging but prefer to have it up to show that we support all models of the team. And also for the bus analogy of Daryls - that if we get ran over by a bus the team is self-sufficient and has what they need. But if painful, then skip.

**Comment by akrherz** [comment]
@giorgichi yes please.  I don't think this will be difficult to implement.

**Comment by giorgichi** [comment]
@akrherz files are sent to your email.

**Comment by akrherz** [comment]
@giorgichi sure, will effort that soon

**Comment by giorgichi** [comment]
@loriabendroth about this comment 

> DEFI_R management form reports some operations for 11N and 11S plots. We only have yield data for plot 11 though. Add N or S designation and cross-check that plot ID master aligns with all entered plot IDs for this site.

The best way to address this will be to use "11" without "N" or "S" suffix. We did the similar thing for SERF_IA where plots were devided into North ("N"), Central ("C"), and South ("S") sections. But after transfering the data to TD db those subplot identifers were eliminated.

**Comment by loriabendroth** [comment]
SERF_IA soil moisture data not edited - Helmers decided to leave as is.

**Comment by loriabendroth** [comment]
closed out DRAINMOD export request - not completed.

**Comment by giorgichi** [comment]
> DEFI_R management form reports some operations for 11N and 11S plots. We only have yield data for plot 11 though. Add N or S designation and cross-check that plot ID master aligns with all entered plot IDs for this site.

N and S is separated from the plot id and added as a location identifier.
