### ISSUE TITLE
Sort management entries by date in TD form

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#166]
Can you please change so that the entries under each tab sort by the calendar date? If not possible then sort by operation.

**Comment by akrherz** [comment]
@loriabendroth I think I have implemented this.  Do you see any issues?  This is only done when the backend spreadsheet column is `date` perhaps I need to key off of other columns for other sheets?

**Comment by loriabendroth** [comment]
@akrherz thanks. This looks great. I dont see a reason to use other key than date. It is sorting well.
