### ISSUE TITLE
Deletion not working in TD management tool

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#167]
I entered n/a's and TBD in the backend management sheet yesterday. This was done to identify areas needing attention still versus those that are not relevant. Many cells had been blank earlier. However, now the delete function doesnt appear to be working. Did I break logic somehow for this function?

**Comment by akrherz** [comment]
@loriabendroth it is unclear to me why this was failing and indeed I could reproduce the failures, so I rewrote the logic and it appears to be working better now.

**Comment by akrherz** [comment]
@loriabendroth seemed to indicate it is working now.  I repushed the code and she shift-reloaded the page.
