### ISSUE TITLE
Visualization and export tool for TD

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#168]
@akrherz, couple things needed upfront before we load more data in next week:

- [x] The agronomic plotting is coming up blank for me regardless of what site and variable combination I try. This problem is not occurring with aggregation in other tools. Example: 
https://datateam.agron.iastate.edu/td/plot_agronomic.phtml?site=DPAC&group=1&varname=AGR17&view=plot 
 
- [x] Free Drainage treatment should always be on the left of the other bars if possible. Can you also switch colors so that free drainage is always navy blue and controlled drainage is yellow?  This would be needed in all instances where aggregation by drainage treatment is possible: agronomic, nitrate load, tile flow, and water table.

- [ ] where are you pulling the treatment and plot pairings from? Need to have some updates to this to account for drainage treatments that go beyond these categories (free and controlled).

- [ ] how painful is it to populate the variable drop-down list only with the variables applicable for that site? it would be based on site master (correct?):
https://docs.google.com/spreadsheets/d/1CZJVPVXghb3fJFKl7BKUrH9JOlIuGoCC8krtJQLfw84/edit#gid=0

**Comment by akrherz** [comment]
@loriabendroth I think these both are now implemented, you concur?

**Comment by loriabendroth** [comment]
@akrherz, yes, your work here looks great. Two follow-up items:

- [ ] where are you pulling the treatment and plot pairings from? Need to have some updates to this to account for drainage treatments that go beyond these categories (free and controlled). 

- [ ] how painful is it to populate the variable drop-down list only with the variables applicable for that site? it would be based on site master (correct)?
https://docs.google.com/spreadsheets/d/1CZJVPVXghb3fJFKl7BKUrH9JOlIuGoCC8krtJQLfw84/edit#gid=0

**Comment by loriabendroth** [comment]
closed job bc two other components are n/a now.
