### ISSUE TITLE
Missing tile flow entries

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#17]
*Revised this on 8/21 from earlier posting. Daryl not able to complete based on processed file. Need to work with pre-processed. 

Generate:
- [x] Complete listing of missing data for tile flow data
- [x] Develop timeline graphic for each site-year that shows where gaps occur and length of time
- [x] Calculate percent of missing data that is less than a day and also more than a day to guide group discussion. 

Do this for 8 sites:
STORY
STJOHNS
HICKS_B
SERF_IA
MUDS2
MUDS4
DPAC
SERF_SD

**Comment by akrherz** [comment]
Here's a report of missing data at whatever resolution reported by the site

Site | Plot ID | Missing Count | Interval
---- | ----- | ---- | ------
BRADFORD.A | 101 | 0 | 1 hour
BRADFORD.A | 102 | 1 | 1 hour
BRADFORD.A | 104 | 0 | 1 hour
BRADFORD.A | 105 | 0 | 1 hour
BRADFORD.A | 201 | 0 | 1 hour
BRADFORD.A | 202 | 0 | 1 hour
BRADFORD.A | 203 | 0 | 1 hour
BRADFORD.A | 204 | 0 | 1 hour
BRADFORD.A | 301 | 0 | 1 hour
BRADFORD.A | 302 | 0 | 1 hour
BRADFORD.A | 303 | 0 | 1 hour
BRADFORD.A | 304 | 0 | 1 hour
BRADFORD.A | 401 | 0 | 1 hour
BRADFORD.A | 403 | 0 | 1 hour
BRADFORD.A | 404 | 0 | 1 hour
BRADFORD.A | 405 | 0 | 1 hour
DPAC | NE | 21283 | 1 hour
DPAC | NW | 6128 | 1 hour
DPAC | SE | 22000 | 1 hour
DPAC | SW | 11971 | 1 hour
GILMORE | 11.1 | 0 | 1 hour
GILMORE | 11.2 | 0 | 1 hour
GILMORE | 12.2 | 0 | 1 hour
GILMORE | 12.3 | 0 | 1 hour
GILMORE | 14.1 | 0 | 1 hour
GILMORE | 16.2 | 0 | 1 hour
GILMORE | 16.3 | 0 | 1 hour
GILMORE | 17.1 | 0 | 1 hour
GILMORE | 17.3 | 0 | 1 hour
GILMORE | 19.2 | 0 | 1 hour
GILMORE | 19.3 | 0 | 1 hour
GILMORE | 21.3 | 0 | 1 hour
GILMORE | 22.1 | 0 | 1 hour
GILMORE | 22.3 | 0 | 1 hour
GILMORE | 23.1 | 0 | 1 hour
GILMORE | 24.3 | 0 | 1 hour
GILMORE | 26.2 | 0 | 1 hour
GILMORE | 3.1 | 0 | 1 hour
GILMORE | 3.2 | 0 | 1 hour
GILMORE | 4.1 | 0 | 1 hour
GILMORE | 4.2 | 0 | 1 hour
GILMORE | 6.2 | 0 | 1 hour
GILMORE | 7.3 | 0 | 1 hour
GILMORE | 9.3 | 0 | 1 hour
SERF | S1 | 2518 | 15 minute
SERF | S2 | 2235 | 15 minute
SERF | S3 | 3746 | 15 minute
SERF | S4 | 5177 | 15 minute
SERF | S5 | 4589 | 15 minute
SERF | S6 | 5738 | 15 minute
STJOHNS | WN | 1179 | 15 minute
STJOHNS | WS | 8127 | 15 minute
WATERMAN | 1 | 0 | 1 hour
WATERMAN | 11 | 0 | 1 hour
WATERMAN | 12 | 0 | 1 hour
WATERMAN | 4 | 0 | 1 hour
WATERMAN | 6 | 0 | 1 hour
WATERMAN | 8 | 27 | 1 hour

**Comment by loriabendroth** [comment]
Thanks D, this is a good overview and helpful. But is for CSCAP sites and not TD sites. See listing above of sites - can you recreate for those?

**Comment by akrherz** [comment]
@loriabendroth here's what I get for the TD database

Site | Plot ID | Missing Count | Interval
----- | ---- | --- | ---
CLAY_C | FD | 0 | 1 hour
CLAY_R | CD | 0 | 1 hour
CLAY_R | SI | 745 | 1 hour
DPAC | NE | 0 | 1 hour
DPAC | NW | 0 | 1 hour
DPAC | SE | 0 | 1 hour
DPAC | SW | 0 | 1 hour
MUDS2 | 103 | 0 | 1 hour
MUDS2 | 104 | 0 | 1 hour
MUDS2 | 105 | 0 | 1 hour
MUDS2 | 106 | 0 | 1 hour
MUDS2 | 201 | 0 | 1 hour
MUDS2 | 202 | 0 | 1 hour
MUDS2 | 205 | 0 | 1 hour
MUDS2 | 206 | 0 | 1 hour
MUDS3_OLD | 101 | 0 | 1 hour
MUDS3_OLD | 102 | 0 | 1 hour
MUDS3_OLD | 202 | 0 | 1 hour
MUDS3_OLD | 203 | 0 | 1 hour
MUDS4 | 101 | 0 | 1 hour
MUDS4 | 102 | 0 | 1 hour
MUDS4 | 103 | 0 | 1 hour
MUDS4 | 104 | 0 | 1 hour
MUDS4 | 201 | 0 | 1 hour
MUDS4 | 202 | 0 | 1 hour
MUDS4 | 203 | 0 | 1 hour
MUDS4 | 204 | 0 | 1 hour
SERF_IA | S1 | 0 | 15 minute
SERF_IA | S2 | 0 | 1 hour
SERF_IA | S3 | 0 | 15 minute
SERF_IA | S4 | 0 | 15 minute
SERF_IA | S5 | 0 | 15 minute
SERF_IA | S6 | 0 | 15 minute
SERF_SD | Plot7 | 0 | 15 minute
SERF_SD | Plot8 | 0 | 15 minute
STJOHNS | WN | 3976 | 15 minute
STJOHNS | WS | 3976 | 15 minute
STORY | 11 | 0 | 1 hour
STORY | 2 | 0 | 1 hour
STORY | 3 | 0 | 1 hour
STORY | 5 | 0 | 1 hour
STORY | 8 | 0 | 1 hour
STORY | 9 | 0 | 1 hour
UBWC | B2 | 0 | 1 hour
UBWC | B4 | 0 | 1 hour

**Comment by giorgichi** [comment]
@akrherz CLAY_C and CLAY_R - intervals are 10 min. There are some missing data, mostly in the beginning or the end of the year. For example at CLAY_R in 2014 plot SI has last reading in 11/6/2014, while the adjacent plot CD has last reading in 12/12/2014. 

DPAC has missing data in every year at least in two plots (if not in all four). Same with SERF_SD and SERF_IA, and I assume STJOHNS have more missing values. Also, time intervals in SERF_IA varies from 5 to 15 min, no hourly measurements. Time intervals are messed up for other sites too, but it is not important for now. 

The reason for not catching those gaps is that you used tile flow from CSV file I provided earlier this year. Those CSV files had "long" structure, which allowed me to get rid of redundant missing values. Therefore, **NAs are no explicitly stated, but rather implicitly present in those data files**. 

Let me know if I can be of more help in this. Or I can run it myself by reading original files and counting NAs in R.

**Comment by akrherz** [comment]
@giorgichi OK, my script would only consider gaps between the start and end timestamp of observations from individual plot ids.  So I am unsure what I can do here as I only have processed your data files, unless I am missing something :/
