### ISSUE TITLE
Misc TD items in data and visualization

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#170]
I had jotted these notes awhile ago and have checked now and believe they are still valid. But if you disagree, then please cross out! Can you work on when have time? 

- [x] consistently handle NO IRRIGATION entries. For example, all of Fausey sites are NO and entered in backend for each year as such except for AUGLA which is not. Also, not all years are entered in backend such as HARDIN which only is 2013 and 2014. https://docs.google.com/spreadsheets/d/1m797EoMbtAvasqum-pB5ykVMeHsGWwcVvre8MbvE-xM/edit#gid=511781979

- [x] remove seed applied treatment from management tool > pesticides, and on backend sheet including any data that may exist.

- [x] run a check against all of the plotIDs used in spreadsheets against master sheet. I think there are some being introduced that are inconsistent.

- [x] possible to finish job #162?  I think we just need weather locations for: IA > BEAR2, DIKE, HICKORY, SHEARER; MN > WILKIN1-3

~~- [ ] add on-site precip data to EXPORT weather page
https://sites.google.com/site/transformingdrainage/database/weather-data-download~~

~~- [ ] move completed water, agronomic, nitrate load data to visualization tools. Such as 2016 SERF_IA WT.~~

~~- [ ] move on-site precip data to tile flow visualization export so can plot alongside flow data. This would be for all 2017 data and prior years that were missing or have been edited.~~

- [x] double-check Jia data for 2017; I had a note that some of data was potentially not reviewed since it came in right at the time of the meeting?

**Comment by giorgichi** [comment]
@loriabendroth why do you want to remove this?
> remove seed applied treatment from management tool > pesticides, and on backend sheet including any data that may exist.

**Comment by giorgichi** [comment]
@loriabendroth I checked HARDIN and there are entries for 2008-2014. Where did you see only 2013 and 2014 entered? 
> consistently handle NO IRRIGATION entries. For example, all of Fausey sites are NO and entered in backend for each year as such except for AUGLA which is not. Also, not all years are entered in backend such as HARDIN which only is 2013 and 2014.

**Comment by loriabendroth** [comment]
@giorgichi my imagination on the irrigation issue. You are right - all looks fine.

**Comment by giorgichi** [comment]
@loriabendroth I had to add entries for AUGLA, but the rest looked done by Steph

**Comment by giorgichi** [comment]
@akrherz can you remove or comment L23 in pest-tab4.html at [TD Management Form](https://script.google.com/d/1n-60g4jcvts6i_EPhW-sSCaeH6vP6ldsaaXO_kQlTGWsnaAYkvC5weym/edit) to address this:
>  remove seed applied treatment from management tool > pesticides

**Comment by akrherz** [comment]
> @akrherz can you remove or comment L23 in pest-tab4.html

This is now done.

**Comment by giorgichi** [comment]
> run a check against all of the plotIDs used in spreadsheets against master sheet. I think there are some being introduced that are inconsistent.

This should be done unless you refer to other **spreadsheets** and **master** sheet.
