### ISSUE TITLE
Corn/Soybean Yield at Zone of Influence

### ISSUE THREAD

**Issue by giorgichi** [isudatateam/datateam#172]
Corn and soybean yields based on the zone of influence are reported for DWM plots at [DEFI_M](https://docs.google.com/spreadsheets/d/1tbyjbZFlevyy3lqGzfLBNj_dPrc5ZGtyvDtsrkL2W7g/edit#gid=1631808670), [HARDIN](https://docs.google.com/spreadsheets/d/1yi31gFYqb-kKEZifxbCaBC0yfV68AncB7kuQ28STf24/edit#gid=655764009), and [HARDIN_NW](https://docs.google.com/spreadsheets/d/1JIkHe8Vlqp9J6TAoyRQsp7twxZGBFxMzhCl91BWN6P4/edit#gid=1205741966). 

@loriabendroth should we include them for publishing?

**Comment by loriabendroth** [comment]
@giorgichi I think so but will need to create a new row in data dictionary for them. Since we have the data and users like Ehsan would want it, I'd go ahead.

**Comment by giorgichi** [comment]
Two variables have been added to the [TD Site Data Collected](https://docs.google.com/spreadsheets/d/1CZJVPVXghb3fJFKl7BKUrH9JOlIuGoCC8krtJQLfw84/edit#gid=0):

- **AGR67** Corn grain yield at 15.5% MB at DWM zone of influence
- **AGR69** Soybean grain yield at 13.0 % MB at DWM zone of influence

Corresponding entries have been added to Data Dictionary.
