### ISSUE TITLE
Forage Biomass

### ISSUE THREAD

**Issue by giorgichi** [isudatateam/datateam#173]
Forage (cereal rye and sorghum-sudangrass) has been collected several times per year and reported individually at [MUDS3-OLD](https://docs.google.com/spreadsheets/d/1OSjlqokhUK87FobEo16LEQmN0StB4eX6isBT61p6n_A/edit#gid=34262355). Dates of harvest have been incorporated into the column name.

@loriabendroth should we keep each harvest separately or combine forage for a corresponding (calendar or water) year?

**Comment by loriabendroth** [comment]
@giorgichi Leave as individual entries. If we didnt have the issue with water year and calendar year, I would say to combine for one annual value. But users will vary how they consider year so better keep at individual measurements.

**Comment by giorgichi** [comment]
@loriabendroth how do you want me to represent them in DD? In particular, how do we incorporate/handle dates?

**Comment by giorgichi** [comment]
Harvest dates have been extracted from the column names and added as a separate variable in a new column called `date`.
