### ISSUE TITLE
List of Weather Variables

### ISSUE THREAD

**Issue by giorgichi** [isudatateam/datateam#181]
A number of weather variables provided vary across sites. Most of the sites have only on-site precipitation. But few of them has a "complete" set of weather variables reported. I think some of those variables (that are of less importance and available for limited sites) can be dropped off. For example, **wind run** can be excluded from the database. 

@akrherz can you suggest a common set of weather variables to include in the database (for hourly and daily data individually)?  For example, we have _daily min, max,_ and _average air temp_ for some sites. But I have noticed that weather stations customarily do NOT report/include **average air temp** at daily scale.

**Comment by akrherz** [comment]
Hi @giorgichi, I am unsure there is a simple answer to this question as most all weather variables can be of interest if they are properly observed and reported.  For example, if `average temperature` is just the mean of the `max` and `min` values, then it is not very useful.  But, if it is the average of higher frequency observations, like 15 second samples throughout the day, then it has more value.  So my answer is if the value is easily derived, then omit it.

**Comment by giorgichi** [comment]
@akrherz, if the **daily average** is calculated based on hourly data (24 readings), does it have a value too?

**Comment by akrherz** [comment]
> if the **daily average** is calculated based on hourly data (24 readings), does it have a value too?

I believe so.

**Comment by giorgichi** [comment]
Currently, there are 36 variables in **daily weather data**. Few of them seems to be redundant. For example, the following variables seem to be the same:  
* `Relative Humidity` and `Ave Relative Humidity`
* `Solar Radiation` and `Ave Solar Radiation`
 
Also, `Bare Soil Temperature (10 cm depth)` and `Bare Soil Temperature (4" depth)` seems to designate identical measurements. 

@loriabendroth and @akrherz, do you agree to combine these variables? And, do you see additional variables that I can merge?

```
VARIABLE                             NUMBER_OF_SITES
Precipitation,                             31
Snowfall,                                   2
Pan Evaporation,                            2
Reference ET,                               3
Reference ET (Penman-Monteith),             1
Reference ET (Short Crop),                  3
Reference ET (Short Grass),                 1
Reference ET (Tall Grass),                  1
Relative Humidity,                         10
Ave Relative Humidity,                      1
Min Relative Humidity,                      1
Max Relative Humidity,                      1
Ave Air Temperature,                       14
Min Air Temperature,                       18
Max Air Temperature,                       18
Dew-Point Temperature,                      1
Ave Bare Soil Temperature (10 cm depth),    1
Min Bare Soil Temperature (10 cm depth),    1
Max Bare Soil Temperature (10 cm depth),    1
Min Bare Soil Temperature (2" depth),       2
Max Bare Soil Temperature (2" depth),       2
Min Bare Soil Temperature (4" depth),       2
Max Bare Soil Temperature (4" depth),       2
Min Bare Soil Temperature (8" depth),       2
Max Bare Soil Temperature (8" depth),       2
Solar Radiation,                           13
Ave Solar Radiation,                        1
Min Solar Radiation,                        1
Max Solar Radiation,                        1
Photosynthetically Active Radiation,        1
Total Energy Density,                       1
Wind Speed,                                12
Max Wind Speed,                             5
Wind Gust,                                  1
Wind Run,                                   2
Wind Direction,                             7
```

**Comment by loriabendroth** [comment]
@giorgichi I would remove the variables that only have one site. I don't think those will be highly valuable to external users and it complicates the export. Can we also change it so that depth is a column for soil temperature so that we can combine all into just min/max? To me, the averages can be merged with their main headings - such as Ave Solar Radiation to Solar Radiation. I would think the equipment is similar in approach to measuring and people just call them slightly different terms.

**Comment by akrherz** [comment]
Gio, Yes combining 10cm and 4in is OK.  With regards to the RH variable being the same, that is hard to say without knowing the calculation methodology.  I am also unsure what `Total Energy Density` is?  I don't think we need a column to more regularize the soil temperature data.  Otherwise, that column becomes vague for the non-soil values.

**Comment by giorgichi** [comment]
The weather data will need to be updated once corrected data is provided for **ACRE**.  For farther details refer to #182.
