### ISSUE TITLE
Reconcile Hourly Weather Data

### ISSUE THREAD

**Issue by giorgichi** [isudatateam/datateam#182]
Weather variables collected at hourly intervals to be reconciled:
- [x] Air Temperature
- [x] Precipitation
- [x] Relative Humidity
- [x] Solar Radiation
- [x] Wind Speed
- [x] Wind Direction
- [x] Wind Gust

Other Issues:
- [x] Make time interval uniform (aggregate into hourly data)

**Comment by giorgichi** [comment]
`Wind Speed` and `Wind Gust` at FULTON and VANWERT contains erroneous readings. Intervals containing those measurements should be removed from the published data.

![weather_hourly_WIND_SPEED](https://user-images.githubusercontent.com/19730308/59886936-d500a200-9386-11e9-965a-0472408ea9c6.png)

![weather_hourly_WIND_GUST](https://user-images.githubusercontent.com/19730308/59886942-d9c55600-9386-11e9-9e95-4f57a3f07c21.png)

**Comment by giorgichi** [comment]
Some of the problematic data were corrected as part of the TD Data Review 2019. In particular, data from WRSIS sites.

**Comment by giorgichi** [comment]
Despite data cleaning done as TD Data Review 2019, `Solar Radiation` ar WRSIS still look unusual some site-years (for instance, values are often > 1000 W/m2, reaching 1500 in summer).

Since I did not have a good guess for possible sources of errors, they were not corrected. 

![weather_hourly_SR_2019-07-05](https://user-images.githubusercontent.com/19730308/60737812-a1df1680-9f21-11e9-9e6a-8f9a60b16c4d.png)

**Comment by akrherz** [comment]
Gio, what's the issue with having solar radiation over 1,000 W/m2 ?

**Comment by giorgichi** [comment]
@akrherz I think there was some upgrading of weather stations or changes made to data processing. As a result (of assumed changes) `Solar Radiation` before 2007 at **DEFI_R**, **FULTON** and **VANWERT** are about 1.5 times greater than other years. Or maybe this is valid data, what do you think?

**Comment by giorgichi** [comment]
Some errors were identified in `Relative Humidity` and `Air Temperature` data at **ACRE** during TD Data Review 2019. Laura Bowling (and Charlotte Lee) are going to address the problem. Once they update ACRE Weather data I will need to reread it.

**Comment by akrherz** [comment]
> before 2007 at **DEFI_R**, **FULTON** and **VANWERT** are about 1.5 times greater than other years

No, that would not be natural variation.  Values above 1000 are certainly possible during the summer season

**Comment by giorgichi** [comment]
@akrherz I've been reading about `Solar Radiation` (aka [Solar Irradiance](https://en.wikipedia.org/wiki/Solar_irradiance)) to understand its variation. Apparently, a typical peak value is ~ **1100 W/m2** on a terrestrial surface facing the sun on a clear day at sea level. At the top of the Earth's atmosphere (before attenuation) it is **1361 W/m2**. 

This confirms my doubts about unusually high measurements of `Solar Radiation` at **DEFI_R**, **FULTON**, and **VANWERT** (reaching 1500 W/m2 in some years). 

@loriabendroth and @akrherz, should I remove `Solar Radiation` readings for those years, or do you prefer to keep them in the database?

**Comment by akrherz** [comment]
If not an instantaneous value, `1500` is certainly too high.  But I am unsure what a good threshold could be, if you zap anything higher than 1500, are you then leaving values of 1499?

**Comment by giorgichi** [comment]
@akrherz, I see it as a problem affecting an entire period (calendar year) rather than individual instances. Therefore, more accurate action will be to remove those periods. For example, in the case of **FULTON**, I would discard the first three years (2004-2006) when annual peaks are certainly above the threshold.

Does it sound reasonable?

**Comment by akrherz** [comment]
Sounds reasonable to me.

**Comment by giorgichi** [comment]
> @akrherz, I see it as a problem affecting an entire period (calendar year) rather than individual instances. Therefore, more accurate action will be to remove those periods. For example, in the case of **FULTON**, I would discard the first three years (2004-2006) when annual peaks are certainly above the threshold.

Periods with erroneous `solar radiation` readings were removed from the final dataset as follows:

- **DEFI_R** from 2003 to 2006
- **FULTON** from 2004 to 2006
- **VANWERT** all years
