### ISSUE TITLE
Compile tile flow data

### ISSUE THREAD

**Issue by giorgichi** [isudatateam/datateam#185]
Following issues need to be addressed in order to finalize tile flow (TF) data:
- [x] **Original vs Filled data**
- _Should we include Gap-Filled data?_
- [x] **Temporal Resolution**
- _WRSIS and WILKINs are at very high resolution, while others have only daily tile flow or discharge data. Few sites have mixed data with different temporal granularities. Should we empose some minimum resolution or combine data with different granularities together?_
- [x] **N Loads**
- _Should I compile only available N load data, or should I calculate it for sites based on N concentration and daily tile flow data?_
- [x] **Original Data**
- _I have to compile original data with the highest temporal resolution and extended variables for future users. The copes should be stored locally and @akrherz's server in Agronomy._
- [x] **Tile water temperature data**
- SERF_SD has included hourly tile water temperature data along with tile flow measurement. I have to aggregate it into daily and add to the rest of WQ dataset.

**Comment by loriabendroth** [comment]
@giorgichi I want to include original and filled data in the export interface. Would like to have two drop-downs where people select the type of data given a short description of the difference. We will provide both for USDA NAL also.

**Comment by loriabendroth** [comment]
@giorgichi I think daily resolution should be minimum. I feel like team members have mentioned this a few times throughout. We could include a note on export interface that sub-daily exists and if people need it, to contact us directly. But I think for general audience, daily is best.
