### ISSUE TITLE
Compile soil data

### ISSUE THREAD

**Issue by giorgichi** [isudatateam/datateam#186]
There are two groups of soil data: discrete (including semi-continuous) and continuous (such as soil moisture content and temperature). Due to different temporal resolutions, they will be compiled into separate files.

- [x] **Soil moisture & temperature**
- combine daily and hourly data
- [x] **Soil quality variables**
- standardize variable names, units
- distinguish variables by extraction methods
- [x] **Averaged values**
- some variables are reported as an average over multiple plots

**Comment by giorgichi** [comment]
>  Averaged values

This has been resolved by (a) adding `location` column to sample identifiers and (b) rectifying other identifiers.

**Comment by giorgichi** [comment]
There are two sources of `soil moisture` data for **HICKS_B**: hourly from CSCAP/TD web-interface and daily from a file received from Jeff Strock. These two datasets only partially agree with each other. Furthermore, hourly data contains more gaps than daily. Some sections of missing data seem to come from actual measurements, while few look to be linearly interpolated. 

What should I do: keep both versions separately in the final database, or keep only one?

![HICKS_B_BW_sm_2014](https://user-images.githubusercontent.com/19730308/71601135-c5bd9680-2b17-11ea-940f-f06f2d4cede3.png)
(black dots are from daily data, blue comes from hourly)

**Comment by akrherz** [comment]
That's an interesting finding.  Does the site's PI have a recommendation on what to do?

**Comment by giorgichi** [comment]
@akrherz, I have not communicated this with the PI. I will do it and let you know of his response.

**Comment by loriabendroth** [comment]
I'd keep daily data to match other sites and because of gaps in hourly. But can see what he responds.

**Comment by giorgichi** [comment]
@akrherz, I did email PI about problems at __HICKS_B__, but have not heard back. I proceeded as @loriabendroth suggested and used daily data for calendar years 2014-2017. Daily `soil moisture` and `soil temperature` for 2012 and 2013 were calculated from hourly data obtained from the CSCAP web-interface.
