### ISSUE TITLE
Finilize field management data

### ISSUE THREAD

**Issue by giorgichi** [isudatateam/datateam#187]
- [x] standardize field managment data
- [x] add and cross-check `plotid`s
- [x] check self-consistancy of the data

**Comment by giorgichi** [comment]
@loriabendroth - `manure application rate` is reported in `gpa` in TD backend sheet. Should I convert it to something else or keep as it is?

**Comment by loriabendroth** [comment]
@giorgichi yes, these should be L per hectare. I checked and that is what we have in the DD. I tried to edit within the management form since we have L as an option but get fail so not sure that code is active. Not worth fixing now though. The gpa can be converted to L ha-1 by multiplying by 9.354.
