### ISSUE TITLE
Inventory of IWQIS (Data Number #10)

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#191]
We need to inventory IWQIS so we know how much water quality data exists for our watersheds. Don't need to bring in any data, simply inventory. We are only concerned about N; don't need to report other elements. 
 
https://iwqis.iowawis.org/
Select Launch IWQIS and on upper right of screen with Iowa map, select the flask and Water Quality Sensors.

- [x] Create a spreadsheet identifying whether or not each priority watershed of ours has a sensor. Eight priority watersheds are https://sites.google.com/iastate.edu/inrc/watersheds?authuser=0

If yes, report the following metadata: 
- [x] Identify presence of a water sensor for each watershed (yes, no)
- [x] Select More Data for each sensor and report the type of water source measured (stream, drain tile, etc), Years Sampled, Sensor ID, Drainage Area, what type of N source data is available (N load, Nitrate + Nitrite as N, etc), and general location of sensor relative to our HUC12 watershed (northern edge, southeast corner, central, etc). 
- [x] Any other information you think helpful

- [x] Place inventory here: https://drive.google.com/drive/u/0/folders/1dTLNvCwAnhT45ziME-TlXCYS7-egv76R

**Comment by giorgichi** [comment]
I extracted all relative data from the [IWQIS](https://iwqis.iowawis.org/) as you requested and entered them [here](https://docs.google.com/spreadsheets/d/1BwC4LNMrf7CHV2ffDPXdNeNqKJDnOnQ2rP32xRshon4/edit#gid=0).

**Comment by loriabendroth** [comment]
@giorgichi looks good, thanks. Can you add variables to data dictionary with as much as you can for detail? https://docs.google.com/spreadsheets/d/18HjkF_g-ETocFxlCDX3MW8UG7RXWSs-eYdeXf8UNCg8/edit#gid=496262310

**Comment by giorgichi** [comment]
> @giorgichi looks good, thanks. Can you add variables to data dictionary with as much as you can for detail? https://docs.google.com/spreadsheets/d/18HjkF_g-ETocFxlCDX3MW8UG7RXWSs-eYdeXf8UNCg8/edit#gid=496262310

DONE
