### ISSUE TITLE
Sus Corn Interface 

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#192]
Few misc items to adjust as makes sense:

- [x] Reword: "It is recommended to "Select All"..." to "We recommend you "Select All"..." on Sites Tab.
https://datateam.agron.iastate.edu/cscap/dl/#tab_data

- [x] Reword last sentence in first paragraph on Water Data, Tools tab from:
It is strongly recommended to download these supporting data to properly interpret and synthesize water data contained here.
TO 
This supporting data must be downloaded to properly interpret and synthesize water data contained here. 
https://datateam.agron.iastate.edu/cscap/dl/#tab_wdata 

- ~~Replace blank cells in tile flow data with missing notation as preferenced by user. For example, download SERF tile flow 2012 data - empty cells exist for tile flow.~~ (will implement for TD, #193)

- [x] Check assignment of zeros rather than n/a in soil moisture data. For example, GILMORE 11-1, I think some zeros should be n/a's? Easy to adjust or leave this? 

- [x] COLUMBIA is misspelled in the the town column for Site Meta tab.

**Comment by akrherz** [comment]
@loriabendroth, regarding

> Replace blank cells in tile flow data with missing notation as preferenced by user.

Do you want this done for all the "Water Data, Tools" tabs?  I don't think it is currently implemented for any of them.

**Comment by loriabendroth** [comment]
@akrherz you're right. I was thinking on this later and how much work would be required toy make it work since we don't have that setup in the same way as other data. Skip these items. We can just implement for TD project.

**Comment by akrherz** [comment]
> * For example, GILMORE 11-1, I think some zeros should be n/a's?

So for some reason, it appeared that I never ran the `qc_decagon.py` script against the GILMORE data.  That has been run now.  Do things look better now?  If not, please let me know an example valid time and depth level of observation.

**Comment by akrherz** [comment]
I believe this issue to be resolved, can open a new one if this soil moisture issue persists.
