### ISSUE TITLE
QC on Data #18 Cost Share Data

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#195]
@giorgichi , some straight forward QC work on a cost share data set coming from multiple sources of funding which is why some columns have a mix of data types. These are first steps and then we will look at the subset data and go from there. Ignore Reference files for now; only work with main spreadsheet. 
https://drive.google.com/drive/u/0/folders/1qwdZFl9hAeSsrTZQcpWAxW1IkedX7UvJ

- [x] Move original to DNU folder and create new version given edits below
- [x] Remove all watersheds from df not within our priority watersheds.
- [x] Remove PracticeCategory of: Component, ErosionAndEdge, In-Stream, Livestock, Urban, Sterambank Stabilization. Screen through others and see if additional should be excluded so only include those practices contained within other ISBI data sets. 
- [x] Do you currently have any source available of lat/long for townships (TRSLS)? If so, add lat/long. If not, it't not urgent but just thinking if a way to assign coordinates to these instead of TRSLS. 
- [x] Filter to blank for huc12code (unless these no longer exist given the deletions that occurred under step 2 above). Will need to add huc12code given TRSLS. 
- [x] Remove huc8code since have huc12codes and to reduce possibility for error. Can always map to a master file that has both.

**Comment by giorgichi** [comment]
I found this source for **township coordinates**: https://www.iowadatacenter.org/maps/codes

**Comment by giorgichi** [comment]
I will need to use additional data to connect DN_18 and above. I found it here: https://www.extension.iastate.edu/agdm/wholefarm/html/c2-88.html

**Comment by giorgichi** [comment]
Need to clean these files I found as they contain some errors :(

**Comment by giorgichi** [comment]
@loriabendroth I used `TRSLS` data to identify corresponding HUC12 watersheds. For most of the townships,  the project watersheds have been already identified. There were only 13 cases without corresponding HUC12 codes (which I will add). For the rest, the HUC12 code identified by me usually agrees with the existing code, but there are 553 cases when they disagree. 

What should we do here? Should we use already existing HUC12 codes, or replace them with those I obtained?

FYI, for those 553 cases, I used a section number to identify the exact location, in other words, my resolution is roughly 1 mile.

**Comment by loriabendroth** [comment]
@giorgichi wow, awesome work on this. I would say to replace them but we better double-check with Laurie to make sure we aren't missing some detail. Can you drop her a note explaining what has been done and the 553 cases?

**Comment by giorgichi** [comment]
One question, do you know if SWCD (Soil and Water Conservation District) is strictly defined by the county boundaries or not?

I will email Laurie about mismatching cases.

**Comment by loriabendroth** [comment]
I think they are county bound. I found this website too which would validate that:
https://idals-farms.iowa.gov/index.php/districtMap

**Comment by giorgichi** [comment]
Thanks a lot @loriabendroth. Then, we also have 6 cases when the district name does not agree with the county (identified based on TRSLS info).

**Comment by giorgichi** [comment]
I checked, and it does not always follow the county boundaries. For example, there is Chickasaw SWCD, but there is no county with that name.

**Comment by loriabendroth** [comment]
Huh. OK. I think there are 100 SWCD total and there are 99 counties so I just figured they aligned and then there must be a bonus SWCD somewhere? Thanks for emailing Laurie.

**Comment by giorgichi** [comment]
Oh, the other dropdown says `Major City`, while I was assuming to be a list of counties. Anyways, I will email Laurie and figure that out.

**Comment by giorgichi** [comment]
> Do you currently have any source available of lat/long for townships (TRSLS)? If so, add lat/long. If not, it't not urgent but just thinking if a way to assign coordinates to these instead of TRSLS

I assigned huc12 watersheds. This way it is aligns with those entries that do not have TRSLS and coordinates.

**Comment by giorgichi** [comment]
In the final table, I also removed any column that did not have entry.

**Comment by loriabendroth** [comment]
Need to refilter original data based on Y/N column populated yesterday by Laurie. This will change the number of incongruencies between township, huc12, etc. 
https://docs.google.com/spreadsheets/d/1kGqKquegnEdb2hEQ0tiBuJnXSANK9Djyj2b6TSAEa8M/edit#gid=1607549501
