### ISSUE TITLE
DN #18 Table, Maps

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#196]
@giorgichi few additional items for DN 18. It is looking great. 
- [x] Create a table with all items in column P and the frequency of each item. We can remove a few more items from list but want to verify with Laurie and Jamie so this will help see how many occurrences there are. 
- [x] Once we hear back on column P, can you create colored maps of each variable with the huc12 watershed colored by frequency?

**Comment by giorgichi** [comment]
All figures are in the [DN_18 Google folder](https://drive.google.com/drive/u/0/folders/1qwdZFl9hAeSsrTZQcpWAxW1IkedX7UvJ)
