### ISSUE TITLE
Homepage directs

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#197]
From home page:

- [x] Insert forward arrow at bottom right with no text.
- [x] Create landing page that this directs to with two options: "Visualization and Plotting Tools" and 
 "Research Data from Experimental Sites". Text will be added to this page eventually so think it is best to do this versus having two arrows on the previous page. The first will link to https://datateam.agron.iastate.edu/td/dl/#tab_wdata
The second will link to https://datateam.agron.iastate.edu/td/dl/#tab_sites
- [x] Remove the following tabs under Research Data: GHG, IPM. 
- [x] Reorder remaining Research Data tabs to be: Sites, Treatments, Water, Agronomic, Soil, Year, Management and Metadata, Export Options
- [x] Remove Soc Econ Data upper tab

**Comment by akrherz** [comment]
> * Insert forward arrow at bottom right with no text.

Sorry, what does that mean?  What is the forward arrow going to?

**Comment by loriabendroth** [comment]
Good question. Use the same blue box and arrow as at lower right of CSCAP (https://datateam.agron.iastate.edu/cscap/) but since the next page will contain data and visualization, I thought that would be too much text so put on the blue box. This is why I said to leave blank. But it can say "Tools and Data". This will go to the "landing" page I mentioned above in second checkbox. So it is inserting an additional page between what now exists of the home page and research data export tool on CSCAP. Does that clarify? I can see what you have done and edit that if needed.

**Comment by akrherz** [comment]
> Use the same blue box and arrow as at lower right of CSCAP

Ah, understood.  I have taken a swing at this now.  Lets create new issues for further iteration.
