### ISSUE TITLE
Research Site Maps, Photos

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#198]
At Research Sites (https://datateam.agron.iastate.edu/td/dl/#tab_sites):

- [x] Remove farmer sites from this Google map: https://www.google.com/maps/d/u/0/edit?mid=1Ubw9c2nAILMhNFclLT0IxNI1yFw&ll=39.4224892230572%2C-86.81664699999999&z=5 
- [x] Replace existing Google map with this new version
- [x] Text under Plot Map Considerations: Keep all but change Sus Corn CAP to Transforming Drainage Project.
- [x] @giorgichi , generate folders for plot maps and photographs under a generic TD google account? These folders should not be set with permissions and only include a subset of all of the maps and photos we have. Note how it was done on CSCAP. Don't need to populate maps or photos in yet but create folders so we can link on page. 
- [x] Populate new site IDs in from TD site metadata + history master Google sheet. These are state_county.
- [x] Change table on webpage with data in the TD site metadata + history master sheet. Remove state column. The Research Site Code column is the column from previous job. The Principal Investigator column is the Lead PI column. Research Site Official Name is column Official Farm Name. Institution is Institution Name. Plot Map and Photograph Links are Google Folders generated above. 
- [x] Change logos at bottom to be same as homepage.

**Comment by giorgichi** [comment]
Google folder with subfolders for photos and maps are in the **_Ag_Data_Commons** folder

**Comment by akrherz** [comment]
> * Populate new site IDs in from TD site metadata + history master Google sheet.

@giorgichi, did you check this as done? Which column in the Google Sheet is this now found?  So In general, I likely missed the boat here, but are these new site IDs the "baseline" for all data, such that the old "Unique IDs" are no longer ever to be used?

**Comment by giorgichi** [comment]
@akrherz, 

- the **new IDs** are replacing old ids. I have swapped them already for all data that we have to post. If you need a key I can send you a file. 
- **Do not use Google Sheets**! They might contain errors or inaccuracies that I have weeded out. But all the updated data are only available as `csv` files. You can find them in [this Google Drive](https://drive.google.com/drive/u/0/folders/1zblZuTiEUdZOq1_IHgO_gEtR018TidRq). 
- For **TD site metadata + history** see a file called **meta_site_history.csv**

**Comment by giorgichi** [comment]
@akrherz, in general, `csv` file names are explanatory and partially follow the names used for their 'parent' files or sheets.

I have appended 'mngt' to the beginning of all files that contain field management data (corresponding to **Management DataStore (TD backend for mandata)** google sheet).

Metadata has 'meta' in the beginning (such as **Methods**, **Plot Identifiers**). 

The rest is 'actual' data.

**Comment by akrherz** [comment]
thanks @giorgichi , for the **TD site metadata + history** information, why is a csv file being used and not the google sheet?  How is the .csv file being edited?  Do you have a spreadsheet locally that you are just dumping to CSV or ?  I guess I am asking how edits happen?

**Comment by loriabendroth** [comment]
> Google folder with subfolders for photos and maps are in the **_Ag_Data_Commons** folder

@giorgichi , these are all created with you as owner. It is best to have a non-personal account as owner so if anyone needs to make edits they can sign-in to the generic account. I had made all the folders at the time under the Sustainable Corn generic account. I had intended to upload all PDFs under this also but see most are under my name which is a mistake. It is best if all generic.

**Comment by akrherz** [comment]
@giorgichi, I have created a csv file that maps the `siteid` to a google drive folder for maps and photos.  Please merge this information into your schema as appropriate.
[drive.txt](https://github.com/isudatateam/datateam/files/4677045/drive.txt)

**Comment by akrherz** [comment]
I believe the items on this issue to be resolved.  Any loose ends to fix before closing @loriabendroth ?

**Comment by loriabendroth** [comment]
@akrherz your work looks good. Could include icons for map and photos like done in CSCAP but not crucial at this point. Can do later if decide.

**Comment by akrherz** [comment]
> Could include icons for map and photos like done in CSCAP

Sure, done now.
