### ISSUE TITLE
Visualization Tool Page

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#199]
Have map and dropdown of options on main page and then based on user selection, can embed on the same page as done with IEM (https://mesonet.agron.iastate.edu/climodat/index.phtml?network=IACLIMATE&station=IA7979&report=28) or open up to new page. The latter is likely easier in the current time frame.  

Initial steps include:
- [ ] Create three drop-down options:
Select Treatment 
Select Experimental Site -> with subheading Or Select from Map
Select Type of Water Data
- [ ] Create clickable map based on Latitude and Longitude columns (R, S) in TD site metadata and history sheet. Color code each site based on the treatment. Blue for CD, Purple for DWR, Green for SB, and White for Other. The treatment categorization for each site is listed under the Drainage Retention Practice column in TD site metadata. 
- [ ] Options for Select Treatment drop down are:
Controlled Drainage
Drainage Water Recycling
Saturated Buffer
Other
- [ ] Options for Water Data dropdown are: Tile Flow, Nitrate Load, Nitrate Concentration, Water Table, and Soil Moisture.

**Comment by akrherz** [comment]
I am unsure of the mechanics of the interaction between the map and the "Select Treatment" pulldown menu.  If the pull down menu comes first, then it would already filter out the sites displayed on the map, right?  Should the map display all the site regardless of which  "Select Treatment" is selected?

**Comment by loriabendroth** [comment]
I am unsure too. ha. Forget the map. It is unnecessary. Also, for the treatment drop down, only make the soil nitrate live right now. That is all we need for the meeting so lets get that working and not worry about others now.

**Comment by loriabendroth** [comment]
For time-series aggregation, only have daily, monthly, and annual. Remove hourly.

**Comment by loriabendroth** [comment]
Closed because issues are no longer relevant.
