### ISSUE TITLE
Allow for HighCharts based editing of data

### ISSUE THREAD

**Issue by akrherz** [isudatateam/datateam#2]
Want to allow users to edit data.  Lots of things to fix and consider here.  This issue is the tracker of it!

**Comment by akrherz** [comment]
[  ] So High Charts has a concept of 'flags' series type, so I can use this to place flags on where edits were made.

**Comment by akrherz** [comment]
@loriabendroth chimed in asking for this for the TD site of the website, so shall see about making that happen!

**Comment by loriabendroth** [comment]
@akrherz thanks. Can you check tile flow edit capability? When I click on data points, nothing happens. Water table and soil moisture editing works.

**Comment by akrherz** [comment]
@loriabendroth fixed, sorry about that

**Comment by loriabendroth** [comment]
@akrherz great!

**Comment by akrherz** [comment]
@loriabendroth, is this editing functionality ever used?  I am inclined to ask if we can remove it, if nobody is using it.

**Comment by loriabendroth** [comment]
@akrherz go ahead and remove it. It was great but unfortunately very few used it.
