### ISSUE TITLE
TD theses and refereed journals listing?

### ISSUE THREAD

**Issue by akrherz** [isudatateam/datateam#204]
@loriabendroth for CSCAP, we have two database tables that track Smart Sheets containing theses and journal articles.  Does the same exist for TD?  If not, can we remove that portion from the website?

**Comment by loriabendroth** [comment]
Yes, it does exist in Smartsheet for TD as well. So keep them on the website. I will get you links from Smartsheet for these today.

**Comment by loriabendroth** [comment]
Here are public links to files. I believe this is what I shared last time that you used to populate website. OK??

refereed journals. All column headings are in same order and vocab matches except Vol is now Vol(lss).
https://app.smartsheet.com/b/publish?EQBCT=d37c31b3f7b14e6db5c7355f2fdda6db

theses/diss. All column headings are in same order and match vocab exactly.
https://app.smartsheet.com/b/publish?EQBCT=921db6ce1fe6497887d0089daed1ee02
