### ISSUE TITLE
Google Map 

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#206]
@giorgichi , edit existing Google map or make a duplicate and edit that one for publishing on external page. Changes from existing map that are needed:

- [x] Switch to state_county site names  
- [x] Check that all plot ids and site pop-ups match what will be in data
- [x] Change Water Management Practices within a site to match those listed in data export: https://datateam.agron.iastate.edu/td/dl/#tab_data
- [x] Change DW Treatments in left-hand sidebar to match those listed in data export: https://datateam.agron.iastate.edu/td/dl/#tab_data
- [x] Remove polygons for all on-farm sites that had lat and long resolution lowered
- [x] Remove internal site webpage links

**Comment by loriabendroth** [comment]
@giorgichi I have itemized list of edits needed to the map in my original post.

**Comment by giorgichi** [comment]
> Remove polygons for all on-farm sites that had lat and long resolution lowered 

@loriabendroth I could not find any. Please let me know if there is one that you noticed.

**Comment by loriabendroth** [comment]
I was thinking sites like WILKIN (for example) weren’t going to show the farm where it was located. So that would mean that the field boundaries and field layout rectangles need to be removed.

In data power notes, we posed this question followed by the consensus:


  *   Should coordinates (longitude and latitude) or other geographic identifiers (nearest city, county, FIPS code) be removed to protect identities of private farmers?
     *   This would also result in removal from the TD Google Map.
Do 1 decimal point with X after it to represent that it has been removed for farmer locations. Main thing is to not include names. OK to include in Google map. Have 2 or 3 for whole field instead of 4 for all sites. Some concerned with data privacy issues.

**Comment by loriabendroth** [comment]
@giorgichi, the statement "OK to include in Google map" contradicts with my memory but could be wrong. What do you remember? 
(I'm logging off now)

**Comment by giorgichi** [comment]
@loriabendroth, as I recall you added those comments during the meeting, hence not everything rings a bell for me. But one thing I remember is that privacy issues vary across the sites. According to some PIs (e.g. Fausey), masking locations of the private farms were prime, while for other PIs (e.g. Jia) the name of the farm and its owner were essential. Therefore, for the former it is **"OK to include in Google map"**.

**Comment by giorgichi** [comment]
@loriabendroth, should we close this issue? Or is there anything I need to address in regards to TD Google Map?

**Comment by loriabendroth** [comment]
@giorgichi , the polygons outlining the practice type exist at all private farms. This means that anyone could locate the sites if wanted. I will email Ben about this and his thoughts.

**Comment by loriabendroth** [comment]
@giorgichi , please order the sites alphabetically in Google Map within each subcategory (Sat Buff, CD, etc). I can't edit the map.

**Comment by giorgichi** [comment]
> order the sites alphabetically in Google Map within each subcategory (Sat Buff, CD, etc).

@loriabendroth this is done

**Comment by giorgichi** [comment]
> the polygons outlining the practice type exist at all private farms. This means that anyone could locate the sites if wanted. I will email Ben about this and his thoughts.

@loriabendroth removed **MUDS4** based on Kelly Nelson's response. Just sent an email asking your and Ben's feedback about Dan Janeys' and Kevin King's sites. 

Emailed Jeff Strock to confirm about inclusion of **HICKS** sites in the map.

**Comment by giorgichi** [comment]
Dan Jaynes' sites have been anonymized as he requested. Polygons denoting research fields and treatments have been deleted. The pins have been moved 5 miles away from the true location.

**Comment by loriabendroth** [comment]
> Dan Jaynes' sites have been anonymized as he requested. Polygons denoting research fields and treatments have been deleted. The pins have been moved 5 miles away from the true location.

@giorgichi , I can see that most of the points are at intersections. How did you decide where to put the pins? I am not sure this is quite best because misleading as it looks like it is right there. I think best to create a big square polygon that covers a 5 mile square... is that possible versus a pin? Make a note also in the comment box that the location is not specific.

**Comment by giorgichi** [comment]
@loriabendroth what you suggested about polygons is possible. However, they will not show as a pin on the map. Someone to see a polygon needs to zoom in. In addition, when you make a polygon around research site, most likely the actual location will be near the center of that polygon, hence somewhat revealing or hinting at the true location. Of course, it does not need to be in the center, but you also do not want it to be at the border. Anyways, my concern is the former problem, those polygons will be almost “invisible” in Google Map.

What I did is, I moved pin about 5 miles away from the true locations and put them in the cross-section of roads so it is clearly not a field. I assumed this to be a better way to handle the problem.

**Comment by giorgichi** [comment]
@loriabendroth the option Ben suggested - **scale dependant rendering** - seems to be possible, but requires some javascript coding. A short snippet of the code is provided [here](https://gis.stackexchange.com/questions/20160/is-it-possible-to-do-scale-dependent-rendering-in-google-maps-with-kml). However I have not done this before and not sure how I can implement this in a timely manner unless @akrherz can step in (assuming he knows how). 

As I understand this will require us to change how Google Map is embedded in the webpage (currently it is a simple iframe).  We will need to use [Google Maps Platform](https://developers.google.com/maps/documentation/javascript/get-api-key), which will enable us to use [Apps Script](https://developers.google.com/apps-script/reference/maps) to modify the look and behavior of the map. @akrherz, correct me if I am making this too complicated.

**Comment by akrherz** [comment]
@giorgichi , I don't really have experience in this space.  My suggestion would be to add ambiguity and not give a false sense of precision.  So make the polygon huge.

**Comment by giorgichi** [comment]
@akrherz we diced to replace the embedded Google map with a figure showing site location (I will provide the figure once finilized). Below that figure, we want to add a text with a hyperlink to the TD Google Map (I assume Lori will provide the text).

@loriabendroth the Google map is updated now and it only includes not-anonymized sites.

**Comment by loriabendroth** [comment]
@giorgichi , when I look at the website, the new map is not there and I have not sent text. Did you intend to close it?

**Comment by akrherz** [comment]
OK, I am awaiting guidance on what text and link to put underneath the static map.

**Comment by loriabendroth** [comment]
@akrherz reduce map in size by 50%. Text to insert underneath the map:
View the Google Map with plot dimensions and infrastructure highlighted. Some sites are not included in the Google map because of privacy for research located on farmer fields. 
Hyperlink Google Map text to https://drive.google.com/drive/folders/123nkLLWggCyXvdU37S9R0W91mDOw-u7Z

**Comment by akrherz** [comment]
> @akrherz reduce map in size by 50%. Text to insert underneath the map:

OK, how does it look now?

**Comment by giorgichi** [comment]
> @giorgichi , when I look at the website, the new map is not there and I have not sent text. Did you intend to close it?

@loriabendroth, I closed it since this issue was related to the TD Google Map which has been reconciled, and did not want to mix with issues related to the website look and/or content.

**Comment by giorgichi** [comment]
@loriabendroth @akrherz should we also change the map under "**Data Visualization**" tab?

**Comment by loriabendroth** [comment]
> > @akrherz reduce map in size by 50%. Text to insert underneath the map:
> 
> OK, how does it look now?

Good for size. Switch text to this: View the Google Map which has plots and infrastructure locations identified. Some sites are not included in the Google map because of privacy concerns for research located on farmer fields.

**Comment by loriabendroth** [comment]
@akrherz , use this link for Google map instead so goes directly to map; https://www.google.com/maps/d/u/1/edit?mid=1Ubw9c2nAILMhNFclLT0IxNI1yFw&ll=39.86558648764423%2C-90.09503297118817&z=5

**Comment by loriabendroth** [comment]
> @loriabendroth @akrherz should we also change the map under "**Data Visualization**" tab?

Yes, lets insert the static map as well as text underneath from main page to the Data Viz page. Keep existing sentence that is at top of page for now.

**Comment by akrherz** [comment]
> Yes, lets insert the static map as well as text underneath from main page to the Data Viz page. Keep existing sentence that is at top of page for now.

Should be done now.

**Comment by loriabendroth** [comment]
@akrherz looks good, will close.
