### ISSUE TITLE
TD home page

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#207]
- [ ] Replace existing photo with the attached instead. 
![2018AnnualMeeting_GroupPhoto](https://user-images.githubusercontent.com/27225264/82607878-46d90100-9b7f-11ea-83df-fa30590273c8.png)
- [ ] Replace all text on main page with this:

This website contains research data measured across a set of experiments carried out by the “Managing Water for Increased Resiliency of Drained Agricultural Landscapes” project or Transforming Drainage. This project is funded from 2015-2020 by the United States Department of Agriculture, National Institute of Food and Agriculture (USDA-NIFA, Award No. 2015-68007-23193). 

The Transforming Drainage Project worked to advance the process of designing and implementing agricultural drainage systems for storing water in the landscape to improve the resiliency and productivity of agricultural systems. Drainage is an essential component of the landscape to provide suitable growing conditions for the crops that feed and support both local and global communities. Increasing water storage on the landscape can provide greater water security for crop production while reducing the loss of water and nutrients through this infrastructure.  

Research data were collected across 40 experimental sites focused on controlled drainage, drainage water recycling, and saturated buffers, beginning in 1996. 

The Transforming Drainage Project's annual reports, proposals, technical reports, and publications are available at the Iowa State/Purude University Digital Repository (website TBD). The Transforming Drainage Project research data are also stored at the USDA National Agricultural Library Ag Data Commons (website TBD). 

Project Director: Jane Frankenberger
Project Manager: Ben Reinhart
Research Data and Visualization Tools: Lori Abendroth, Giorgi Chighladze, Daryl Herzmann (isudatateam@iastate.edu)

**Comment by akrherz** [comment]
@loriabendroth The image uploaded here appears to be a PNG, which is not a great format for real time pictures.  Do you have a JPG variant?  Thanks

**Comment by loriabendroth** [comment]
@akrherz I will check!

**Comment by loriabendroth** [comment]
JPEG attached!
![IMG_5441_edit](https://user-images.githubusercontent.com/27225264/82698864-397c4f00-9c31-11ea-8dac-beb3b629c6bb.jpg)
