### ISSUE TITLE
Research Data > Data Variables 

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#208]
Create checkboxes for users to select which variables they want exported. I have listed Headers for each grouping. You can organize the groupings however fit best on each page; they don’t necessarily need to be same as here. 

The variables are itemized for each tab. Other variables which are not listed will automatically come along, such as site, plotid, etc.
 
For all: Text to go next to each checkbox is the column header edited. Capitalize first letter of each word and replace underscore with space. final_plant_population becomes Final Plant Population. 

- [x] AGRONOMIC Tab; data comes from agronomic_data.csv
HEADER: (leave empty for now; can’t decide)
leaf_area_index
final_plant_population
HEADER: **Crop Yield**
grain_moisture
crop_yield
biomass_yield
HEADER: **Plant and Grain Biomass**
whole_plant_biomass
vegetative_biomass
grain_biomass
corn_cob_biomass
HEADER: **Total Nitrogen Content**
whole_plant_total_N
vegetative_total_N
grain_total_N
corn_cob_total_N
HEADER: **Total Carbon Content**
vegetative_total_C
grain_total_C
corn_cob_total_C 

- [x] Soil; data comes from soil_properties_data
HEADER: **Soil Texture**
soil_texture
percent_sand
percent_silt
percent_clay
HEADER: **Soil Properties**
bulk_density
hydraulic_conductivity
infiltration_rate
matric_potential
water_content
som
pH_water
pH_salt
lime_index
neutralizable_acidity
cec
K_saturation
Ca_saturation
Mg_saturation
Na_saturation
K_concentration
Ca_concentation
Mg_concentration
Na_concentration
K_amount
Ca_amount
Mg_amount
sar
salinity_paste
salinity_water
HEADER: **Soil Carbon**
Soc
HEADER: **Soil Nitrogen**
total_N
NO3_concentration
NH4_concentration
NO3_amount
NH4_amount
P_B1_concentration
P_M3_concentration
P_B1_amount
P_M3_amount

- [x] Water; data comes from different tables based on header
HEADER: **Soil Moisture**; from soil_moisture_data
soil_moisture
soil_temperature
soil_ec
HEADER: **Tile Flow and Load**; from tile_flow_and_N_loads_data
tile_flow
discharge
nitrate_N_load
nitrate_N_removed
tile_flow_filled
nitrate_N_load_filled
HEADER: **Water Quality**; from water_quality_data
nitrate_N_concentration
ammonia_N_concentration
total_N_filtered_concentration
total_N_unfiltered_concentration
ortho_P_filtered_concentration
ortho_P_unfiltered_concentration
total_P_filtered_concentration
total_P_unfiltered_concentration
pH
water_ec

Note:  All other data tables such as management, methods, and meta will be automatically checked under the Management and Metadata tab for all exports. The weather data is on-site weather data and will be under the Weather Data tab that is outside the Research Data export (as it is in CSCAP).

**Comment by giorgichi** [comment]
@loriabendroth I think `biomass_yield` should be under the **GRAIN YIELD** header.  Because this variable includes biomass of crops (such as sorghum) that were grown and harvested for forage purposes. That is why it is separate from `whole_plant_biomass` and `vegetative_biomass`. 

Also, I would change the name of **GRAIN YIELD** to **YIELD** or **CROP YIELD**, because it also contains yield from non-grain crops (such as sugar beets).

**Comment by loriabendroth** [comment]
@giorgichi , can you edit the text above or do I need to? This all sounds good. On the biomass_yield, I could not remember how that was defined exactly.

**Comment by akrherz** [comment]
I believe this issue is done.

**Comment by loriabendroth** [comment]
yep, looks good
