### ISSUE TITLE
Research Data > Treatment Tab

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#209]
@giorgichi , look at first three jobs. @akrherz, last couple once previous ones are addressed. 

Jobs deal with ability to list treatments for checkbox export tool. Treatments come from dwm_treatment and irrigation_type columns in meta_plot_identifier table.

- [x] Review the treatment verbage. In particular, I'd like a "dwr" in the treatment name so it is crystal clear for users. We have SB and CD. The DWR are plots with irrigation treatments, correct? Put CD and DWR in name somehow? 

- [x] There are a few with NA or varies for treatment. Need to define these somehow or remove. I think varies are because CLAY changed treatments by year? But if we look at treatments*year, they would be defined, correct? 

- [x] Edit text below for Daryl so that DWR is present.

- [x] ~HEADER: "Drainage Water Management" with options:
Saturated Buffer
Controlled Drainage
Controlled Drainage with Subirrigation
Free Drainage
Free Subsurface and Surface Drainage
Shallow Drainage
Non-Drained~

**Comment by loriabendroth** [comment]
@giorgichi as I look at it more, I think it will be clearest for Daryl programmatically and users if a column is added that defines each site as CD, SB, DWR, or other. I know some have multiple but can you assign what that site is best known for? We can put a note that explains DWR systems have CD embedded within them if people are confused. Once you add this in to the table, then it should be clearer for querying.

**Comment by giorgichi** [comment]
`meta_site_history.csv` (corresponds to **TD Site Metadata + History (Master)**) has a column called `drainage_retention_practice` that defines treatment (**CD**, **SB**, **DWR**, or **other**) for a whole research site.

**Comment by giorgichi** [comment]
`meta_plot_identifier.csv` defines drainage treatment at the plot level, while `meta_site_history.csv` provides information on the site level.

**Comment by giorgichi** [comment]
CLAY_R is not the only site that changed the treatment. Actually, there are 5 sites that "varies".

**Comment by giorgichi** [comment]
**Treatment*year**  will not always work. You should look at `comments` for additional info in those cases.

**Comment by giorgichi** [comment]
"NA"s are for cases when an identifier is not related to a plot, but to some location such as a pond. I cannot assign drainage treatment to those locations. That is why NA.

**Comment by loriabendroth** [comment]
@giorgichi, OK, understood on all of this. But how can we have DWR as a checkbox for users to select? Or stated differently, is listing treatments an option to select from or is it simply the sites overall characterization that is the treatments (SB, CD, DWR, Other)?

**Comment by giorgichi** [comment]
I am not sure if I correctly understand your question, but I will try to respond. TD Site Metadata + History (Master) provides the site's overall characterization in terms of practice being studied. For example, if site is defined as CD, it means the controlled drainage practice was the main practice studied. For those sites, controlled drainage practice is the main treatment, but it will include plots with other (control) treatments, such as free drainage, non-drained, etc.

**Comment by loriabendroth** [comment]
@akrherz , @giorgichi and I discussed and corrected the job above. You can add the treatments to the tab as shown above. Gio will upload tables that list each treatment by plotid and day and year to allow you to map each treatment to the water variables (daily) and agro/soil (year). There are some instances where the treatment changes mid-year which is the reason you will need trt by day and year.

**Comment by giorgichi** [comment]
@loriabendroth, I have scrutinized DWR treatments and diversity of DWMs associated with them, and finally figured out that the original organization of `meta_plot_identifier.csv` table is the only way to go without creating any convoluted structures. 

In short, DWR cannot be assigned to the plots the same way as other drainage treatments. The main reason is that drainage water recycle can happen in controlled drainage, free drainage (see **SWROC**), and even in non-drained plots (see **MUDS1**).  If we simply dub all these plots DWR, than we will lose the key information about the drainage system being in place. So, non-drained plots at MUDS1, free drainage plots at SWROC, and subirrigated plots at other sites will all become DWR. Which is misleading at least.

The solution is to separate drainage (how water is taking out from the field) from irrigation (how water is added to the field). So, I created file that lists both drainage treatment `dwm` and irrigation method `dwr` for all site-plot-years. The two columns will be sufficient to enable a very clear and straightforward filtering of treatments.

**Comment by giorgichi** [comment]
@akrherz @loriabendroth 

The treatment tab will have two headers, instead of one, as follows:

- [ ] HEADER: **"Drainage Water Management"** with options:
Non-Drained
Controlled Drainage
Controlled Drainage with Subirrigation
Free Drainage
Surface Drainage
Shallow Drainage
Saturated Buffer

- [ ] HEADER: **"Drainage Water Recycle"** with options:
Non-Irrigated
Drip Irrigation  
Overhead Irrigation 
Subsurface Irrigation

[This file](https://drive.google.com/open?id=1lYBtREEEYGe0lkb7rTM0BUPRNU7RTB2s) contains **dwm** and **dwr** treatment identifiers for each plot-year.

**Comment by giorgichi** [comment]
@akrherz I have updated `tile_flow_and_N_loads_data.csv` file. Now it contains a column called `dwm_treatment` that defines drainage treatment at a daily resolution for each plot. 

For **all other data** (including soil moisture, water quality, agronomic, etc.) you should use `meta_treatment_identifier.csv` to get the treatment.

**Comment by loriabendroth** [comment]
@giorgichi thanks for hours of extra scrutiny on this! Your solution looks great.

**Comment by akrherz** [comment]
I've implemented the treatments listed in the comment above, but the backend filtering logic is not fully flushed out yet.  Please leave this open until I get this all straight in my head.

**Comment by loriabendroth** [comment]
It's looking good daryl! Let us know if can help on filtering logic.

**Comment by loriabendroth** [comment]
@akrherz OK if I close? I will run through tests and pick up if there are filtering logic issues... and then repost.

**Comment by akrherz** [comment]
Sounds good @loriabendroth , thanks!
