### ISSUE TITLE
Research Data > Site Selection

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#211]
- [x] @giorgichi , where does Auglaize1 and Defiance1 fit best? Both are "varies". 

@akrherz , 4 treatment groupings to use for the site selection page:

- [x] HEADER "Saturated Buffer" with options:
IA_Boone
IA_Grundy
IA_Hamilton1
IA_Hamilton2
IA_Hamilton3
IA_Story1
IA_Tama
MN_Wilkin3

- [x] HEADER "Controlled Drainage" with options:
IA_Story2
IA_Washington
IN_Randolph
MN_Redwood1, MN_Redwood2
MN_Wilkin1
MN_Wilkin2
MO_Knox1
MO_Knox3
MO_Knox4
NC_Washington
ND_Richland
OH_Auglaize1
OH_Auglaize2
OH_Crawford
OH_Defiance1
OH_Delaware
OH_Hardin1
OH_Hardin2
OH_Henry
SD_Clay

- [x] HEADER "Drainage Water Recycling" with options:
MN_Clay1, MN_Clay2, MN_Clay3 
MN_Redwood3
MO_Knox2
MO_Shelby
OH_Defiance2
OH_Fulton
OH_Vanwert

- [x] HEADER: "Other"
IN_Tippecanoe

**Comment by loriabendroth** [comment]
I see the site categorizations in meta_site_history now column S. So used those to edit the list above. For CLAY1 and 3, they are categorized as Other but are they needed to understand CLAY2 as a whole? I left them under DWR as such.

**Comment by giorgichi** [comment]
MN_Redwood2 is supposed to help to understand MN_Redwood1. Should we bring move that to CD then?

**Comment by giorgichi** [comment]
I would change HEADER **"Prarie, Wetland"** to **"Other"**

**Comment by loriabendroth** [comment]
@giorgichi I changed to Other up above. I think any sites that need to go together for context should be grouped in the export. For example, "Clay1, Clay2, Clay3" would only have one checkbox and all three sites export together. Can you list out which sites this is for daryl?

**Comment by giorgichi** [comment]
@loriabendroth those are the only ones. **Clay** sites will all go together and **MN_Redwood** sites.

**Comment by loriabendroth** [comment]
I have updated the original text to include this grouping.
