### ISSUE TITLE
Enforce standard format for Date & Time

### ISSUE THREAD

**Issue by giorgichi** [isudatateam/datateam#22]
- Unify Date & Time format in all Google Sheets in both databases. 
- Combine **date** and ** time** in one column.

**Comment by akrherz** [comment]
What about time zone inclusion and representation? :)

**Comment by giorgichi** [comment]
Do you want it to be included in the Google sheets? I am afraid to confuse users, since they often directly interact with those sheets.

**Comment by akrherz** [comment]
this is related to work in #34 now.  This is tricky business as we got end-user feedback that they want the hour+minute split out into its own column.

**Comment by giorgichi** [comment]
@akrherz after considering the diversity of timestamped data, I have decided to **split date and time into separate columns**. 

The main reason is that very often the same variable is reported with and without time (only date) depending on research sites and years (samples were collected). Combining those variables from all locations and years becomes problematic as I need to combine `YMD` with `YMD HMS`, which will result in creating dummy timestamps (by adding virtual `HMS` to the former).

The second reason is related to what you have mentioned in #34. Most of the time I have no information if the timestamp (`YMD HMS`) is reported with DST or not. 

I will use only local time corrected for daylight saving (when applicable/possible). This will ensure that a data user will not run into duplicated timestamps at 2 am on the first Sunday of November.

**Comment by giorgichi** [comment]
The timestamp will be represented as follows in four separate columns:

**`column 1: DATE [YYYY-MM-DD]`**
**`column 2: TIME [hh:mm]`** as local standard time
**`column 3: UTC [YYYY-MM-DDThh:mm:ss+00:00]`** as UTC timestamp according to ISO 8601 format
**`column 4: TIMESTAMP TYPE {I, D}`** where I = instant, D = daily measurement

@akrherz does the UTC format looks good to you?
