### ISSUE TITLE
add variable identifier to `meta_methods.csv`

### ISSUE THREAD

**Issue by akrherz** [isudatateam/datateam#224]
@giorgichi , it would be very helpful if the `meta_methods.csv` would contain an additional column with the abbreviated variable name that is used within the data csv files to represent the data.  Presently, I have no known means to associate the two.  If there's anther sheet that does this, please let me know!

**Comment by giorgichi** [comment]
@akrherz, there are two issues here: 

- some entries in the methods are not associated with any particular measurement (for example, one entry can provide info about how soil samples were collected in the field, which is not related to a single variable).
- some entries are associated with multiple measurements (for example, soil particle analysis is related to 4 variables: percent sand, percent silt, percent clay, and soil texture).

There are others that I can uniquely relate to individual variables. But not all (as I noted above). Because of this, I did not want to have a column assigning variable names. But if you want me to do so, please let me know who do you want me to handle those two cases mentioned above.

**Comment by loriabendroth** [comment]
I think we can just export by site. If someone requests data for site A, export everything for site A. That will be simplest and then can sort thru what is relevant.

**Comment by giorgichi** [comment]
@loriabendroth, you are right. I think if we want to filter `meta` data, it should be limited to **siteid**.

**Comment by akrherz** [comment]
Thanks for the responses.  I am unsure what to suggest.  For the CSCAP export, I would add a textual label for each of the cryptic data headers found in the excel file.  I was hoping to do the same for TD, but have not found such a cross reference between the variable names and a longer plain-text description.  That is what I was driving after here.

**Comment by loriabendroth** [comment]
I was thinking of the Notes section when I replied earlier which I think we just exported everything. Forgot that you had customized the methods section.

**Comment by loriabendroth** [comment]
@giorgichi , few edits:

- [ ] Edit this: "Soil Particle?Size Distribution" so no question mark.
- [ ] Variable names match old terminology such as corn plant population versus plant population and then corn in the description. Can all of these be changed to align with new? I think this is needed to ensure comprehension by users. 
- [ ] In soybean plant population description it says RX. Soybean would be R8. 
- [ ] Regarding the issues above that havent been resolved, I think most could be categorized by variable name if match to data dictionary.

**Comment by giorgichi** [comment]
> In soybean plant population description it says RX. Soybean would be R8.

According to Tamas: "FINAL PLANT POPULATION: for sure we have established (V6) and final for corn ..., not sure for soybeans." That is why I put RX.

**Comment by loriabendroth** [comment]
Plant populations – when considered as “final” - are taken prior to harvest which could be anytime in July or later. People tend to list the physiological maturity stage to represent it is final but not necessarily taken at that R stage. Could remove R stage in dictionary for all crops and just say final.

**Comment by giorgichi** [comment]
[Data Dictionary](https://docs.google.com/spreadsheets/d/1QU858NHlkZ4L23dmAZ7zwFsVdEmmu-vhbF5o1EFk8pw) does not define the stage for plant population count. It reads as "Final plant population at harvest".

**Comment by loriabendroth** [comment]
> [Data Dictionary](https://docs.google.com/spreadsheets/d/1QU858NHlkZ4L23dmAZ7zwFsVdEmmu-vhbF5o1EFk8pw) does not define the stage for plant population count. It reads as "Final plant population at harvest".

Yes. I was meaning notes but no problem. All is fine. Only part left is translating column C in methods to current dictionary codes when possible. Some will not be possible because general but many can be converted. Let me know if you want me to do this.

**Comment by giorgichi** [comment]
**`meta_methods.csv`** was edited to match **`variable_name`** with those listed in the **data dictionary** when applicable. Updated files was uploaded to ADC Google Drive.
