### ISSUE TITLE
Misc items for TD export page

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#225]
Few things to improve flow/clarity:

~~- [ ] Can the water visualization tools not be embedded within the research data tab? So that if you click on the View Tools, it brings you to a separate webpage than the Research Data portal? This means that when someone goes to the research data portal, they only see four tabs: research sites, research data, weather data, publications.~~ 

- [x] Update picture on main page from #207 - or maybe this is still to do? 

- [x] Change text for visualization to: "Interactive plotting tool with downloadable figures"
https://datateam.agron.iastate.edu/td/data.phtml

- [x] For all plotting tools, remove download data capabilities. Only have figure download options. 

- [x] Under Sites tab, only have state_county for site ids. Remove the full names that follow. https://datateam.agron.iastate.edu/td/dl/#tab_data

- [x] Remove Pesticides option on Management and Metadata tab. No pesticides data exists.

**Comment by akrherz** [comment]
> * Update picture on main page from #207 - or maybe this is still to do?

Maybe your browser has this image cached?  Please try shift-reloading the page.

**Comment by akrherz** [comment]
> * For all plotting tools, remove download data capabilities. Only have figure download options.

You sure you want this?  Just last week I added the custom missing functionality for #213

**Comment by giorgichi** [comment]
@akrherz, if we are going to limit the plotting tool to **figure download**, do you think it will be helpful to provide simplified data for that purpose? So, your code does not have to do complex filtering, merging and aggregation?

**Comment by loriabendroth** [comment]
@akrherz , you're correct on image. Tried diff browser and was there.

**Comment by loriabendroth** [comment]
Regarding download data -> I hate that you worked on it and now it will go away. But my preference is to not allow it users are then forced to get the data how we want them to. They have to check-off on the data usage agreement and also get supporting metadata to make sure they interpret things correctly.

**Comment by loriabendroth** [comment]
I added couple minor things to first post : )

**Comment by loriabendroth** [comment]
@akrherz , skip the first item in list for now. Will see what we think later down the road. For now, please only:

- [ ] Rename "Water Data, Tools" tab to "Data Visualization"
- [ ] Move the visualization tool to the further right tab (5th tab)

**Comment by loriabendroth** [comment]
@akrherz can you complete last two items here so I can close out?

**Comment by akrherz** [comment]
> @akrherz can you complete last two items here so I can close out?

Should be done and server updated now.
