### ISSUE TITLE
Review, finalize GHG data

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#23]
Items necessary to complete regarding GHG data to finalize it for export:

- [x] Bring in GHG15 (soil NO3-N) and soil NH4-N for MN in 2012 from 3 sheets labeled "CSCAP_GHG_SoilNFieldX_2012" (https://drive.google.com/drive/folders/0B2ek1NMPaNIgdTlFTmN1bVJiNkU) to the "GHG Data 2012" sheet. Note, soil NH4-N does not exist in master data collected or SS yet; add this in first and then add column to 2012 MN spreadsheets for B, G, and P. 

- [x] Move Equipment tab comments into SS; delete tab in Google sheet. First tab are basic chamber metadata collected for the tool calculations; keep but do not move into SS or db. Keep the third tab as it allows tool to function.  
https://docs.google.com/spreadsheets/d/1ixZuJ5_qw1ca9hbl4PXcmneS075HSvYjV54VUfaChlw/edit#gid=388987636

- [x] The site master treatment and data collected sheets are 100% correct. Use these, along with GHG data sheets to cross-check yes/no into each applicable site plot ID sheet for GHG column. Daryl populated in so all should be OK; e.g. 
https://docs.google.com/spreadsheets/d/14iUq_4w_jVj2NMY5KoxlEkkkesy6wVQZeJ66EFUCd-o/edit#gid=0 

- [x] Identify sites with any GHG plot identifiers that do not match exactly with agro/soil plot identifiers. For example, MASON and KELLOGG. Will likely put an explanatory note about this somewhere on interface since wont match maps exactly and to ensure people understand how to match it up with other data sets. For MI sites, they have early and late kill also as a treatment which I did not think we had represented fully in treatment structure. 

- [x] Determine if new categories for chamber position are needed to account for WI GHG chamber placement relative to fertilizer band. If so, then may need to rework all chamber designations across sites. (Lori do this)

- [x] Merge 5 Google files into 1 for Daryl to bring into db. Only work with files labeled as "GHG Data YEAR"; ignore folder "MN_GHG_Data" as these have already been processed and ingested. 
https://drive.google.com/drive/folders/0B2ek1NMPaNIgdTlFTmN1bVJiNkU 

- [x] Produce boxplots for each variable across all sites to see general range; this will identify problem sites if any. Javed has reviewed data as it has come in manually, I believe. 

- [x] Review email feedback from Javed on 8/7/2017+. 

- [x] Edit MAR, KELLOGG, and MASON as noted in 8/17 comment below. (amendment: KELLOGG only remaining)

**Comment by giorgichi** [comment]
### about item 3 in the list (cross-check yes/no for GHG column)

Following sites have incorrectly identified plots with GHG data:
1. HOYTVILLE.LTR
2. KELLOGG
3. NWREC
4. WOOSTER.COV
5. WOOSTER.LTR

As I understand the problem stems from the fact that yes/no columns did not have filter, while the rest of the columns did. Hence, GHG and other yes/no columns were not included in the sorting of the Google sheets. 

I corrected all Google sheets for GHG, but have not checked other 4 columns. I recommend @akrherz rerun his code to repopulate yes/no for AGRO, SOIL,, IPM_CSCAP and IPM_USB columns.

**Comment by giorgichi** [comment]
### about item 4 in the list (matching plot identifiers)

All GHG plot ids match with those we have in Plot Identifiers sheets for AGRO and SOIL data, except for MN sites. This creates difficulties in populating yes/no in GHG column of corresponding Plot Identifiers sheets (item 3 in the list).

Maps that Jeff sent show GHG sampling location, but do not depict plot boundaries and names, hence hard to make use of them. (Those maps only delineate treatment boundaries). Need additional info about plots in order to assign GHG data.

**Comment by akrherz** [comment]
@giorgichi here are the differences found and updated with running the plotid checking scripts
```text
HICKS.B
  GHG  plotid: BE40 :: yes -> no
  GHG  plotid: BW19 :: yes -> no
HICKS.G
  GHG  plotid: GA7 :: yes -> no
  GHG  plotid: GB20 :: yes -> no
  GHG  plotid: GC21 :: yes -> no
  GHG  plotid: GD23 :: yes -> no
HICKS.P
  GHG  plotid: P2 :: yes -> no
KELLOGG
  GHG  plotid: 206E :: no -> yes
  GHG  plotid: 207E :: no -> yes
  GHG  plotid: 302E :: no -> yes
  GHG  plotid: 304E :: no -> yes
  GHG  plotid: 406E :: no -> yes
  GHG  plotid: 407E :: no -> yes
  GHG  plotid: 506E :: no -> yes
  GHG  plotid: 601E :: no -> yes
KELLOGG
  AGR  plotid: 101 :: yes -> no
  SOIL plotid: 101 :: no -> yes
  AGR  plotid: 102 :: yes -> no
  SOIL plotid: 102 :: no -> yes
  AGR  plotid: 203 :: yes -> no
  AGR  plotid: 204 :: yes -> no
  SOIL plotid: 205 :: no -> yes
  SOIL plotid: 206 :: no -> yes
  SOIL plotid: 302 :: no -> yes
  SOIL plotid: 303 :: no -> yes
  SOIL plotid: 304 :: no -> yes
  AGR  plotid: 305 :: yes -> no
  SOIL plotid: 305 :: no -> yes
  AGR  plotid: 306 :: yes -> no
  AGR  plotid: 307 :: yes -> no
  SOIL plotid: 307 :: yes -> no
  AGR  plotid: 308 :: yes -> no
  AGR  plotid: 401 :: yes -> no
  SOIL plotid: 401 :: no -> yes
  AGR  plotid: 402 :: yes -> no
  SOIL plotid: 402 :: no -> yes
  AGR  plotid: 403 :: yes -> no
  SOIL plotid: 403 :: yes -> no
  AGR  plotid: 404 :: yes -> no
  SOIL plotid: 407 :: no -> yes
  SOIL plotid: 408 :: no -> yes
  AGR  plotid: 503 :: yes -> no
  AGR  plotid: 504 :: yes -> no
  SOIL plotid: 505 :: no -> yes
  SOIL plotid: 506 :: no -> yes
  SOIL plotid: 507 :: no -> yes
  SOIL plotid: 508 :: no -> yes
  SOIL plotid: 602 :: no -> yes
  SOIL plotid: 603 :: no -> yes
  SOIL plotid: 604 :: no -> yes
  SOIL plotid: 605 :: no -> yes
  SOIL plotid: 606 :: no -> yes
  AGR  plotid: 106E :: no -> yes
  AGR  plotid: 106W :: no -> yes
  AGR  plotid: 107E :: no -> yes
  AGR  plotid: 107W :: no -> yes
  AGR  plotid: 206E :: no -> yes
  AGR  plotid: 206W :: no -> yes
  AGR  plotid: 207E :: no -> yes
  AGR  plotid: 207W :: no -> yes
  AGR  plotid: 302E :: no -> yes
  AGR  plotid: 302W :: no -> yes
  AGR  plotid: 304E :: no -> yes
  AGR  plotid: 304W :: no -> yes
  AGR  plotid: 406E :: no -> yes
  AGR  plotid: 406W :: no -> yes
  AGR  plotid: 407E :: no -> yes
  AGR  plotid: 407W :: no -> yes
  AGR  plotid: 506E :: no -> yes
  AGR  plotid: 506W :: no -> yes
  AGR  plotid: 507E :: no -> yes
  AGR  plotid: 507W :: no -> yes
  AGR  plotid: 601E :: no -> yes
  AGR  plotid: 601W :: no -> yes
  AGR  plotid: 604E :: no -> yes
  AGR  plotid: 604W :: no -> yes
MASON
  AGR  plotid: 102N :: no -> yes
  AGR  plotid: 102S :: no -> yes
  AGR  plotid: 103N :: no -> yes
  AGR  plotid: 103S :: no -> yes
  SOIL plotid: 108 :: no -> yes
  SOIL plotid: 201 :: no -> yes
  SOIL plotid: 202 :: no -> yes
  AGR  plotid: 305N :: no -> yes
  AGR  plotid: 305S :: no -> yes
  SOIL plotid: 301 :: no -> yes
  SOIL plotid: 302 :: no -> yes
  AGR  plotid: 406E :: no -> yes
  AGR  plotid: 406W :: no -> yes
  AGR  plotid: 407E :: no -> yes
  AGR  plotid: 407W :: no -> yes
  SOIL plotid: 403 :: no -> yes
  SOIL plotid: 404 :: no -> yes
  AGR  plotid: 206N :: no -> yes
  AGR  plotid: 206S :: no -> yes
  AGR  plotid: 208N :: no -> yes
  AGR  plotid: 208S :: no -> yes
  AGR  plotid: 307N :: no -> yes
  AGR  plotid: 307S :: no -> yes
  SOIL plotid: 501 :: no -> yes
  SOIL plotid: 502 :: no -> yes
  AGR  plotid: 506N :: no -> yes
  AGR  plotid: 506S :: no -> yes
  AGR  plotid: 507N :: no -> yes
  AGR  plotid: 507S :: no -> yes
  AGR  plotid: 601N :: no -> yes
  AGR  plotid: 601S :: no -> yes
  AGR  plotid: 604N :: no -> yes
  AGR  plotid: 604S :: no -> yes
  SOIL plotid: 607 :: no -> yes
  SOIL plotid: 608 :: no -> yes
NWREC
  AGR  plotid: 1031 :: yes -> no
  SOIL plotid: 1031 :: yes -> no
  AGR  plotid: 1032 :: yes -> no
  SOIL plotid: 1032 :: yes -> no
  AGR  plotid: 1041 :: yes -> no
  SOIL plotid: 1041 :: yes -> no
  AGR  plotid: 1042 :: yes -> no
  SOIL plotid: 1042 :: yes -> no
  AGR  plotid: 1051 :: yes -> no
  SOIL plotid: 1051 :: yes -> no
  AGR  plotid: 1052 :: yes -> no
  SOIL plotid: 1052 :: yes -> no
  AGR  plotid: 2021 :: yes -> no
  SOIL plotid: 2021 :: yes -> no
  AGR  plotid: 2022 :: yes -> no
  SOIL plotid: 2022 :: yes -> no
  AGR  plotid: 2041 :: yes -> no
  SOIL plotid: 2041 :: yes -> no
  AGR  plotid: 2042 :: yes -> no
  SOIL plotid: 2042 :: yes -> no
  AGR  plotid: 2081 :: yes -> no
  SOIL plotid: 2081 :: yes -> no
  AGR  plotid: 2082 :: yes -> no
  SOIL plotid: 2082 :: yes -> no
  AGR  plotid: 3021 :: yes -> no
  SOIL plotid: 3021 :: yes -> no
  AGR  plotid: 3022 :: yes -> no
  SOIL plotid: 3022 :: yes -> no
  AGR  plotid: 3041 :: yes -> no
  SOIL plotid: 3041 :: yes -> no
  AGR  plotid: 3042 :: yes -> no
  SOIL plotid: 3042 :: yes -> no
  SOIL plotid: 3081 :: no -> yes
  SOIL plotid: 3082 :: no -> yes
  SOIL plotid: 3091 :: no -> yes
  SOIL plotid: 3092 :: no -> yes
  SOIL plotid: 3101 :: no -> yes
  SOIL plotid: 3102 :: no -> yes
  SOIL plotid: 4021 :: no -> yes
  SOIL plotid: 4022 :: no -> yes
  SOIL plotid: 4041 :: no -> yes
  SOIL plotid: 4042 :: no -> yes
  SOIL plotid: 4051 :: no -> yes
  SOIL plotid: 4052 :: no -> yes
  SOIL plotid: 4061 :: no -> yes
  SOIL plotid: 4062 :: no -> yes
  SOIL plotid: 4081 :: no -> yes
  SOIL plotid: 4082 :: no -> yes
  SOIL plotid: 4091 :: no -> yes
  SOIL plotid: 4092 :: no -> yes
  SOIL plotid: 4101 :: no -> yes
  SOIL plotid: 4102 :: no -> yes
WOOSTER.COV
  SOIL plotid: 105 :: no -> yes
  SOIL plotid: 107 :: yes -> no
  SOIL plotid: 110 :: no -> yes
  SOIL plotid: 111 :: yes -> no
  SOIL plotid: 113 :: no -> yes
  SOIL plotid: 116 :: yes -> no
  SOIL plotid: 117 :: no -> yes
  SOIL plotid: 118 :: yes -> no
  SOIL plotid: 120 :: no -> yes
  SOIL plotid: 121 :: yes -> no
  SOIL plotid: 124 :: no -> yes
  SOIL plotid: 202 :: yes -> no
  SOIL plotid: 205 :: no -> yes
  SOIL plotid: 206 :: yes -> no
  SOIL plotid: 207 :: no -> yes
  SOIL plotid: 208 :: yes -> no
  SOIL plotid: 210 :: no -> yes
  SOIL plotid: 215 :: yes -> no
  SOIL plotid: 216 :: no -> yes
  SOIL plotid: 218 :: yes -> no
  SOIL plotid: 219 :: no -> yes
  SOIL plotid: 220 :: yes -> no
  SOIL plotid: 222 :: no -> yes
  SOIL plotid: 223 :: yes -> no
ORR
  AGR  plotid: 3051 :: yes -> no
  SOIL plotid: 3051 :: yes -> no
  SOIL plotid: 4082 :: no -> yes
NAEW.WS127
  AGR  plotid: 127T :: yes -> no
  AGR  plotid: 127M :: yes -> no
  AGR  plotid: 127B :: yes -> no
NAEW.WS123
  AGR  plotid: 123T :: yes -> no
  AGR  plotid: 123M :: yes -> no
  AGR  plotid: 123B :: yes -> no
NAEW.WS118
  AGR  plotid: 118T :: yes -> no
  AGR  plotid: 118M :: yes -> no
  AGR  plotid: 118B :: yes -> no
NAEW.WS115
  AGR  plotid: 115T :: yes -> no
  AGR  plotid: 115M :: yes -> no
  AGR  plotid: 115B :: yes -> no
NAEW.WS113
  AGR  plotid: 113T :: yes -> no
  AGR  plotid: 113M :: yes -> no
  AGR  plotid: 113B :: yes -> no
NAEW.WS111
  AGR  plotid: 111T :: yes -> no
  AGR  plotid: 111M :: yes -> no
  AGR  plotid: 111B :: yes -> no
NAEW.WS109
  AGR  plotid: 109T :: yes -> no
  AGR  plotid: 109M :: yes -> no
  AGR  plotid: 109B :: yes -> no
ORR
  IPM_USB  plotid: 3051 :: no -> yes
  IPM_USB  plotid: 4072 :: yes -> no
  IPM_USB  plotid: 4081 :: no -> yes
  IPM_USB  plotid: 4041 :: no -> yes
NWREC
  IPM_USB  plotid: 1031 :: no -> yes
  IPM_USB  plotid: 1032 :: no -> yes
  IPM_USB  plotid: 1041 :: yes -> no
  IPM_USB  plotid: 1042 :: yes -> no
  IPM_USB  plotid: 1061 :: yes -> no
  IPM_USB  plotid: 1062 :: yes -> no
  IPM_USB  plotid: 1101 :: no -> yes
  IPM_USB  plotid: 1102 :: no -> yes
  IPM_USB  plotid: 2031 :: no -> yes
  IPM_USB  plotid: 2032 :: no -> yes
  IPM_USB  plotid: 2041 :: yes -> no
  IPM_USB  plotid: 2042 :: yes -> no
  IPM_USB  plotid: 2051 :: yes -> no
  IPM_USB  plotid: 2052 :: yes -> no
  IPM_USB  plotid: 3011 :: yes -> no
  IPM_USB  plotid: 3012 :: yes -> no
  IPM_USB  plotid: 3021 :: yes -> no
  IPM_USB  plotid: 3022 :: yes -> no
  IPM_USB  plotid: 3041 :: no -> yes
  IPM_USB  plotid: 3042 :: no -> yes
  IPM_USB  plotid: 3071 :: no -> yes
  IPM_USB  plotid: 3072 :: no -> yes
  IPM_USB  plotid: 3081 :: no -> yes
  IPM_USB  plotid: 3082 :: no -> yes
  IPM_USB  plotid: 3091 :: no -> yes
  IPM_USB  plotid: 3092 :: no -> yes
  IPM_USB  plotid: 3101 :: no -> yes
  IPM_USB  plotid: 3102 :: no -> yes
  IPM_USB  plotid: 4011 :: no -> yes
  IPM_USB  plotid: 4012 :: no -> yes
  IPM_USB  plotid: 4021 :: no -> yes
  IPM_USB  plotid: 4022 :: no -> yes
  IPM_USB  plotid: 4041 :: no -> yes
  IPM_USB  plotid: 4042 :: no -> yes
  IPM_USB  plotid: 4051 :: no -> yes
  IPM_USB  plotid: 4052 :: no -> yes
  IPM_USB  plotid: 4061 :: no -> yes
  IPM_USB  plotid: 4062 :: no -> yes
  IPM_USB  plotid: 4071 :: no -> yes
  IPM_USB  plotid: 4072 :: no -> yes
  IPM_USB  plotid: 4091 :: no -> yes
  IPM_USB  plotid: 4092 :: no -> yes
  IPM_USB  plotid: 4101 :: no -> yes
  IPM_USB  plotid: 4102 :: no -> yes
MASON
  IPM_USB  plotid: 105 :: no -> yes
  IPM_USB  plotid: 106 :: no -> yes
  IPM_USB  plotid: 107 :: no -> yes
  IPM_USB  plotid: 108 :: no -> yes
  IPM_USB  plotid: 201 :: no -> yes
  IPM_USB  plotid: 202 :: no -> yes
  IPM_USB  plotid: 203 :: no -> yes
  IPM_USB  plotid: 204 :: no -> yes
  IPM_USB  plotid: 301 :: no -> yes
  IPM_USB  plotid: 302 :: no -> yes
  IPM_USB  plotid: 303 :: no -> yes
  IPM_USB  plotid: 304 :: no -> yes
  IPM_USB  plotid: 401 :: no -> yes
  IPM_USB  plotid: 402 :: no -> yes
  IPM_USB  plotid: 403 :: no -> yes
  IPM_USB  plotid: 404 :: no -> yes
  IPM_USB  plotid: 501 :: no -> yes
  IPM_USB  plotid: 502 :: no -> yes
  IPM_USB  plotid: 503 :: no -> yes
  IPM_USB  plotid: 504 :: no -> yes
  IPM_USB  plotid: 605 :: no -> yes
  IPM_USB  plotid: 606 :: no -> yes
  IPM_USB  plotid: 607 :: no -> yes
  IPM_USB  plotid: 608 :: no -> yes
KELLOGG
  IPM_USB  plotid: 101 :: no -> yes
  IPM_USB  plotid: 102 :: no -> yes
  IPM_USB  plotid: 105 :: no -> yes
  IPM_USB  plotid: 108 :: yes -> no
  IPM_USB  plotid: 204 :: no -> yes
  IPM_USB  plotid: 207 :: no -> yes
  IPM_USB  plotid: 302 :: no -> yes
  IPM_USB  plotid: 303 :: no -> yes
  IPM_USB  plotid: 304 :: no -> yes
  IPM_USB  plotid: 305 :: no -> yes
  IPM_USB  plotid: 308 :: no -> yes
  IPM_USB  plotid: 401 :: no -> yes
  IPM_USB  plotid: 402 :: no -> yes
  IPM_USB  plotid: 404 :: no -> yes
  IPM_USB  plotid: 406 :: no -> yes
  IPM_USB  plotid: 407 :: no -> yes
  IPM_USB  plotid: 408 :: no -> yes
  IPM_USB  plotid: 505 :: no -> yes
  IPM_USB  plotid: 506 :: no -> yes
  IPM_USB  plotid: 507 :: no -> yes
  IPM_USB  plotid: 508 :: no -> yes
  IPM_USB  plotid: 601 :: no -> yes
  IPM_USB  plotid: 602 :: no -> yes
  IPM_USB  plotid: 603 :: no -> yes
  IPM_USB  plotid: 604 :: no -> yes
  IPM_USB  plotid: 605 :: no -> yes
  IPM_USB  plotid: 606 :: no -> yes
  IPM_USB  plotid: 607 :: no -> yes
  IPM_USB  plotid: 608 :: no -> yes
  IPM_USB  plotid: 206E :: yes -> no
  IPM_USB  plotid: 207W :: yes -> no
  IPM_USB  plotid: 302W :: yes -> no
  IPM_USB  plotid: 304E :: yes -> no
  IPM_USB  plotid: 304W :: yes -> no
  IPM_USB  plotid: 405E :: yes -> no
  IPM_USB  plotid: 406E :: yes -> no
  IPM_USB  plotid: 407W :: yes -> no
  IPM_USB  plotid: 506E :: yes -> no
MAR
  IPM_USB  plotid: 107 :: yes -> no
  IPM_USB  plotid: 105 :: no -> yes
  IPM_USB  plotid: 307 :: yes -> no
  IPM_USB  plotid: 306 :: no -> yes
```

**Comment by giorgichi** [comment]
Thanks Daryl. 

Just want to note that you did not find differences in GHG for **HOYTVILLE.LTR**, **NWREC**, **WOOSTER.COV**, and **WOOSTER.LTR**, because I fixed them yesterday, while **KELLOGG** and **HICKS** sites were corrected only today.

**Comment by giorgichi** [comment]
@akrherz, please revert yes/no status for GHG as it was. Those plots had correct status for GHG.

**Comment by akrherz** [comment]
@giorgichi I have revered the GHG values

**Comment by loriabendroth** [comment]
@giorgichi fertilizer nuances at WI are related to chamber position designations; should not affect your review of the data. 
- [ ] determine if new categories for chamber position are needed to account for WI GHG chamber placement relative to fertilizer band
- [ ] transform all sites to align with new labels

**Comment by giorgichi** [comment]
@loriabendroth currently there are following positions for GHG chamber: 
1. inside_band
2. inside_band+outside_band
3. on_broadcast
4. outside_band

**Comment by loriabendroth** [comment]
Emailed Mike Castellano on 6/16/17 with issues. @giorgichi address once feedback received. 

•	sp_GHG03 (CO2) – are values up around 400 feasible? Are there lower or upper bounds to use? 
•	sp_GHG05 and sp_GHG05_trimmed (N2O) – are HICKS.G and HICKS.P (MN sites) values possible (GHG05)? In the trimmed graphic, these have been removed so you can see other sites up close.  Are there lower or upper bounds we should apply to HICKS.G, MASON, SERF, or WATERMAN? These value don’t seem plausible relative to other sites.  
•	sp_GHG07 (NH3) – are values below -100 feasible? 
•	sp_GHG09 (CH4) – is the range at NWREC and WATERMAN ok? Quite a bit different from other sites. 
•	sp_GHG13 (VSM) – soil moisture values above 60% are unlikely unless measuring in muddy water. Do you think people were out collecting in saturated conditions? In 2012 there was some flooding in MN (HICKS sites), which may explain high soil moisture content, but not sure about FREEMAN measurements. What are your thoughts on the validity of this, keep in? 
•	sp_GHG14 (Temp) – soil temperature in ARL and LAN reaches 70 C (160 F) and FREEMAN is up to 130 F. Is this of value to retain for GHG?
•	sp_GHG15 (NO3) and CSCAP_soil_nitrate – soil nitrate at ISUAG and SERF are beyond what we have in the main database from soil samples pulled (see CSCAP_soil_nitrate). If we look at the soil samples pulled, the soil nitrate max is 50 and 12 mg/kg in ISUAG and SERF respectively. Whereas here it is up to 2000. Do you want these high values retained with the GHG data? Is it possibly a calculation error?  
•	sp_GHG16 (NH4) – values ok? Don’t have other sites for reference but HICKS has been high on other gases.
•	R2 data – is there value in making this available to the public, or was it only valuable for you and Javed? All sites ranged from 0 to 1.

**Comment by giorgichi** [comment]
- [x] reconcile HICKS (B, G, and P) plot IDs used in the GHG data with master plot IDs

**Comment by loriabendroth** [comment]
Changed chamber placements at ARL and LAN to allow for nuances relative to fertilizer band. Changed codes across all sites with bands to align with new terminology (on/off versus in/out). MAR is only site needing clarification and changes.

**Comment by loriabendroth** [comment]
MAR and MASON are done. KELLOGG 2014 needs plot IDs clarified to remove late kill plots. For MASON and KELLOGG will use tabs with "_export". Cardinal directions removed entirely; do similar on agro/soil if possible to simplify plotid export.

**Comment by loriabendroth** [comment]
@giorgichi send daryl an updated GHG file to reflect all changes; only KELLOGG will need changes as noted above.

**Comment by giorgichi** [comment]
@loriabendroth new GHG data was sent to @akrherz today (9/18/2017)

**Comment by loriabendroth** [comment]
@akrherz I need you to reingest KELLOGG GHG data (unless it does it automagically). You had brought in this sheet (https://docs.google.com/spreadsheets/d/12NqffqVMQ0M4PMT_CP5hYfmydC-vzXQ0lFHbKwwfqzg/edit#gid=1029606281) and this is still the correct one although I deleted about 30 rows from it to eliminate early/late kill issues for GHG data.

**Comment by akrherz** [comment]
@loriabendroth regarding
> I need you to reingest KELLOGG GHG data

@giorgichi had previously collected up all the data for me to import, so I was not using these directly.

**Comment by giorgichi** [comment]
@akrherz I need to find that script that reads them all. I will send you an email when done.
