### ISSUE TITLE
Change from CSCAP to TD

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#230]
- [ ] Change text below dropdowns to this:

Transforming Drainage Project Research Data (USDA-NIFA Award No. 2015-68007-23193) Usage Agreement

Please reference this data set in publications as:

[author list TBD] 2021. Transforming Drainage Project Research Data (USDA-NIFA Award No. 2015-68007-23193). National Agricultural Library - ARS - USDA. [doi TBD]

You are encouraged to contact the Transforming Drainage Project personnel listed above to ensure proper data interpretation and may also consider co-authoring with them. You shall have no claim of ownership to any intellectual property rights in any part of the data, content, functions, features, code, data exploration tools, logos or other intellectual property comprising this database.

The coauthors individually and the Transforming Drainage Project collectively shall NOT be responsible or liable for the accuracy, reliability and completeness of any information included in the database nor the suitability of its application for any particular purpose. Data users are encouraged to notify the coauthors regarding data quality and other issues concerning the data, tools, and functionality of this website. Contact isudatateam@iastate.edu with any questions or concerns regarding usage and application of the data available at this site.

I agree with the above terms of usage.

**Comment by akrherz** [comment]
I am unsure what you are referencing by "text below dropdowns", on which pages and what is meant by dropdowns?

**Comment by loriabendroth** [comment]
ha yah, a bit vague. Here: 
https://datateam.agron.iastate.edu/cscap/dl/#tab_data

**Comment by loriabendroth** [comment]
Under the Export Options tab
