### ISSUE TITLE
Add text explaining filled data

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#235]
On water download page, add text to give context to checkboxes:
https://datateam.agron.iastate.edu/td/dl/#tab_data

- [x] Add a superscript 1 after Tile Flow and Nitrate N Load checkboxes
- [x] Add a superscript 2 after Tile Flow Filled and Nitrate N Load Filled checkboxes
- [x] Somewhere in lower left of page, add text:

"1 Data are provided for each in-field collection. However, based on equipment setup, some sites collect a composite sample which represents the sum for a series of days while other sites collect daily measurements.
2 Data are provided on a daily basis with interpolations performed when needed based on gap-filling methods developed specifically by the Transforming Drainage team. This is the RECOMMENDED data to use unless you are familiar with interpolating time-series water data."

**Comment by giorgichi** [comment]
@loriabendroth, we added what you asked, although the description is not in the left side, but rather across the whole page. Does it work?

**Comment by loriabendroth** [comment]
looks perfect! Can superscript the 1 and 2 in footer as well but not big deal.
