### ISSUE TITLE
plotids vs locations for Nitrate Load Data Plotting

### ISSUE THREAD

**Issue by giorgichi** [isudatateam/datateam#240]
There is a three-way identifier for N loads: `siteid`, `plotid`, and `location`. The plotting tool is utilizing only the first two and ignoring the `location`. As a result, some plots look messy or incorrect. 

Fortunately, `plotid` and `location` for this data do not overlap. In other words, N loads are never associated with both identifiers. So we can use this as an advantage - when `plotid` is missing we can switch to `location` for grouping. 

@akrherz can you implement this change?

**Comment by akrherz** [comment]
Should the interface then ask for the `siteid` and then plot any available `plotid` or `location` for that `siteid` on the chart?

**Comment by giorgichi** [comment]
I think the interface should only ask for the `siteid`. Then it will plot whatever is available for that site. No need to ask for `plotid` or `location`.
