### ISSUE TITLE
How to do 'group by treatment' for nitrate load plot

### ISSUE THREAD

**Issue by akrherz** [isudatateam/datateam#244]
@giorgichi I am unsure how to implement "Group by Treatment" for the nitrate load plot.  Could you kindly detail how I should cross reference the `plotid` / `location` to some grouping term?

**Comment by giorgichi** [comment]
Grouping should be preformed only for the following treatments: 
- Free Drainage                         
- Shallow Drainage
- Controlled Drainage                   
- Controlled Drainage with Subirrigation

If `dwm_treatment` is missing or says **Saturated Buffer**, then it should be excluded from "Group by Treatment".
 
After that filtering, you need to group by `siteid`, `dwm_treatment` and `date` and calculate daily average for plotting.

Monthly and annual loads should be aggregated based on above data.
