### ISSUE TITLE
Remove low-frequency data types from /dl interface

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#25]
- [x] Drop following AGR variables entirely from /dl interface:
[AGR8] Wheat plant biomass at maturity; b/c only at 4 NAEW sites with 3 subsamples; not useful.
[AGR29] Wheat grain total carbon at maturity; b/c only at 4 NAEW sites with 3 subsamples; not useful.
[AGR30] Wheat grain total nitrogen at maturity; b/c only at 4 NAEW sites with 3 subsamples; not useful.
[AGR31] Corn stalk nitrate samples; b/c only GILMORE and WOOSTER.COV have data for 7 site-years total; not useful.
[AGR37] Cover crop (rye) and weedy biomass in late fall; b/c only BRADFORD.C has one year of data; not useful. 
[AGR38] Weedy biomass (only) in late fall; b/c only BRADFORD.B1 and BRADFORD.C have three site-years of data; not useful. 
[AGR47] Weedy biomass (only) total nitrogen at spring; b/c only SEPAC has 4 site-years of data. 
[AGR48] Wheat plant biomass total carbon at maturity; b/c only at 4 NAEW sites and one year of data each on a whole-field basis; not useful.
[AGR49] Wheat plant biomass total nitrogen at maturity; b/c only at 4 NAEW sites and one year of data each on a whole-field basis; not useful.
[AGR50] Weedy biomass (only) total carbon at spring; b/c not at any exported sites. 
[AGR51] Weedy biomass (only) total nitrogen at fall; b/c not at any exported sites. 
[AGR52] Weedy biomass (only) total carbon at fall; b/c not at any exported sites. 

- [x] Questionable; withdraw later if Norm has hesitations including:
[AGR44] Red clover or mixed cover crop biomass in spring of spreadsheet year
[AGR45] Red clover or mixed cover crop total nitrogen in spring of spreadsheet year
[AGR46] Red clover or mixed cover crop total carbon in spring of spreadsheet year
 
- [x] Drop following SOIL variables entirely from /dl interface:
[SOIL8] Penetration resistance; b/c only at WATERMAN.
[SOIL18] Particulate organic matter (POM); b/c only at MASON and KELLOGG with subset of plots sampled.
[SOIL20] Salinity; b/c only at WATERMAN.
[SOIL40] Soil Total Aggregation %; b/c not at any exported sites.
[SOIL99] Total Inorganic N; b/c only at MASON in 2012.

- [x] Only include IPM variables IPM20, 21, 22, 23, and 24. Do not include others (IPM2, 5, 6, 7, 13, 14, 16, 17, 18, 19)

- [x] Drop following WATER variables entirely from /dl interface:
[WAT24] Tile Ammonium-N concentration; b/c only at BRADFORD.A.
[WAT25] Tile Ammonium-N loss; b/c only at BRADFORD.A. 
[WAT14] Tile pH; b/c only at BRADFORD.A and WATERMAN.
[WAT10] Tile Electrical Conductivity (EC); b/c only at WATERMAN.
[WAT26] Tile Reactive P loss; b/c only at GILMORE

- [x] Questionable if include WAT 3, 5, 6, or 21; @giorgichi what do you think of value? 
[WAT3] Dissolved Organic Carbon (DOC) Concentration; only at NAEW sites and WATERMAN.
[WAT5] Water runoff rate; only at NAEW sites.
[WAT6] Time to runoff; only at NAEW sites.
[WAT21] Other Water Nitrate-N concentration; only at NAEW sites.

- [x] Create SS column denoting yes/no on inclusion per variable in /dl.

**Comment by loriabendroth** [comment]
@akrherz I am now done removing variables from the export tool.

**Comment by akrherz** [comment]
`AGR` and `SOIL` vars dropped as per list.

**Comment by giorgichi** [comment]
Since we are dropping WAT24, WAT25, WAT26, WAT14 and WAT10, I think than we should also drop WAT3, WAT5, WAT6 and WAT21. 

p.s. I would have suggested to keep WAT3 if WATERMAN had good quality data.
