### ISSUE TITLE
Merge, reconcile master watershed data 

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#252]
Create one file with all descriptors of our priority watersheds and then remove the duplicate columns in other files to ensure we are using one master for all work. To do this:

- [x] See file "Watershed_SiteMetadata" under *Universal folder. This was a start of variables needed. Bring other variables into this file to serve as MASTER. 

- [x] The WatershedMetadata in DN07 was generated from BMP database but data describes whole watershed (not a particular practice) so should be integrated with prior sheet. When done, move this into DNU folder or delete. 

- [x] Retain only projectID and project name in other DN sheets. For example, in DN18, remove columns C-G after checking that everything matches. I have starred all DN folders that we have worked with; ignore non-starred folders.

**Comment by giorgichi** [comment]
@loriabendroth, there are four watersheds that do not agree with those in the **WatershedMetadata** in DN07 (see columns C and D in the ***Watershed_SiteMetadata** under *Universal folder). Which dataset is more assoritative, DN07 or the universal?

**Comment by loriabendroth** [comment]
@giorgichi, neither should be considered authoritative if they are incorrect. The BMP would have come from the BMP website and done by Sam. I cannot remember where the HUC12 came from that are in the universal list. We need to find an authoritative source that connects HUC12 with these watersheds. I was thinking that we had a source but can't recall right now - do you have a source that comes to mind?

**Comment by giorgichi** [comment]
@loriabendroth, there was a shapefile Sam used to map the watersheds and huc12s.

**Comment by giorgichi** [comment]
@loriabendroth, the ***Watershed_SiteMetadata** was populated by you in Oct 29, 2019. But I do not know where did you get it from since there is no other (original) file related to that in the same folder.

**Comment by giorgichi** [comment]
@loriabendroth, do you remember where did you get the HUC12 from in the universal list? Or should I ignore it and proceed with whatever I used for other datasets (DS_01, DS_02, etc.)?

**Comment by giorgichi** [comment]
> The WatershedMetadata in DN07 was generated from BMP database but data describes whole watershed (not a particular practice) so should be integrated with prior sheet. When done, move this into DNU folder or delete.

Moved some columns to the ***Watershed_SiteMetadata** and move the file to DNU folder.

**Comment by giorgichi** [comment]
@loriabendroth, do you want me to move any other column from the WatershedMetadata in DN07 to ***Watershed_SiteMetadata**? Please see the Data Dictionary for the columns that remained in the DN07.

**Comment by giorgichi** [comment]
@loriabendroth, how do you want to populate the following columns:

- fips
- countyName
- districtName

Each HUC12 can cover multiple counties.

**Comment by loriabendroth** [comment]
@giorgichi , in response to your questions:

@loriabendroth, do you remember where did you get the HUC12 from in the universal list? Or should I ignore it and proceed with whatever I used for other datasets (DS_01, DS_02, etc.)? 
-> no, it would have been in a list from someone because I did not create those. Go ahead and ignore the HUC12 in the universal list and use those from other datasets. 

@loriabendroth, do you want me to move any other column from the WatershedMetadata in DN07 to *Watershed_SiteMetadata? Please see the Data Dictionary for the columns that remained in the DN07. 
-> Bring in all that you have colored red since these describe the priority watershed and are sub-components to it. Main thing is to not include descriptions of the conservation practice from DN07. But if they describe the watershed, we want those in the master.  

@loriabendroth, how do you want to populate the following columns:
fips
countyName
districtName
Each HUC12 can cover multiple counties. 
-> Correct. Include all that are a part of the priority watershed. You could pull this from DN_18 likely and get all of the applicable counties/districts. The priority watershed is the unit of interest - not HUC12. HUC12 are a part of the priority watersheds. 

On all of these issues, use your best judgement knowing the goals of the team and what would be helpful in the Master list for identifiers. The goal of this is to have a master copy that can provide the mapping information needed regardless of data source so all can be linked together.

**Comment by loriabendroth** [comment]
I unstarred the folders btw because of confusion by other users. If you are unsure which folders to work with, let me know.

**Comment by giorgichi** [comment]
>  Retain only projectID and project name in other DN sheets. For example, in DN18, remove columns C-G after checking that everything matches. I have starred all DN folders that we have worked with; ignore non-starred folders.

Deleted columns C and G in DN_18.

**Comment by loriabendroth** [comment]
@giorgichi please update DD with your changes also and then close out. Looks good.

**Comment by giorgichi** [comment]
> update DD with your changes also and then close out. Looks good.

Done
