### ISSUE TITLE
Classify DN01 events by centroid

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#253]
@giorgichi , please add a classifer for all events in DN01 as to whether they meet the same standards for distance as you did for DN02. 

Within the DN01 folder, go to Structured Annual Progress Reports and the Events and Outreach tab. No work is needed on other tabs. 

- [x] Add a yes/no/TBD Centroid column next to the Location column. Classify each event by whether the location listed falls within the 25 mile centroid method that you used for DN02. 

- [x] Add this centroid column to the data dictionary for DN01.

**Comment by giorgichi** [comment]
@loriabendroth, I opened the **[Structured Annual Progress Reports](https://docs.google.com/spreadsheets/d/1LyHN7hcPiNWjD6Ljj9Me1oCDIfMmeugkkjSApaKwY-c/edit#gid=607235473)**, but could not find the tab you mentioned (**Events and Outreach**). Did you rename the tab?

**Comment by loriabendroth** [comment]
It is Outreach and Education.

**Comment by giorgichi** [comment]
@loriabendroth, locations need to be checked and standardized. Do you want me or Steph to do it?

**Comment by loriabendroth** [comment]
Go ahead and standardize locations in a similar fashion as done on cost share, etc. Make sure to communicate with Steph that you have done this and what file source you used for future reference as she will likely populate a few more entries.
