### ISSUE TITLE
Metadata populated

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#254]
@giorgichi , few items to begin for NNK:

- [x] Review NN sites that are not included in NNK currently - example is MUDS2 in NN and MO_Novelty in NNK. These are different sites, correct? Same issue with Ontario.  
- [x] Populate "1. Site Information" sheet with relevant text from proposal narrative (found in Proposal folder) and collaborator agreements (found in individual data folders). Text includes start date, soil types, etc.  
- [x] Create duplicate of NN management entry tool for NNK. No changes are needed other than site names for drop down and the linking to backend sheet. I copied over backend sheet already to Master folder but it is blank.

**Comment by loriabendroth** [comment]
cross-checked sites for task 1 and updated spreadsheets and website.

**Comment by giorgichi** [comment]
**DUDLEY** is not listed in the proposal.

**Comment by loriabendroth** [comment]
DUDLEY will be included based on correspondence with Laura and desire to include post-2020 data. This is reason for my email to her on 7-23-2020.

**Comment by giorgichi** [comment]
I added few new columns (highlighted in green) to [**1. Site Information**](https://docs.google.com/spreadsheets/d/1FUcXmUzEbvLoDjysPw0x2kD6HxLIqGrydLusaf710Jo/edit#gid=1000345562) table.

**Comment by giorgichi** [comment]
> cross-checked sites for task 1 and updated spreadsheets and website.

Done
