### ISSUE TITLE
Extract and sum drained acres

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#255]
Derive the number of acres with artificial drainage:

- [x] download data as per Ben's instructions from PURR 
https://purr.purdue.edu/publications/3263/1
- [x] extract data for priority watersheds
- [x] create two values for each watershed: 
likely_drained - 1 only
potentially_drained - sum of 1 and 0.75 
- [x] take this area divided by total area in Universal folder to derive % drained area for likely and potentially drained.
- [x] put all of this into Model Output folder

**Comment by giorgichi** [comment]
@loriabendroth - the raster data is classified into four drainage classes: 

- 1 = Very poorly and poorly drained (“Likely to be drained”)
- 0.75 = Somewhat poorly drained (“Potentially drained”)
- 0 = Moderately well to excessively drained (“Unlikely to be drained”)
- No Data = Not agriculture 

Percentages of **likely_drained** and **potentially_drained** areas were calculated based on the total watershed area (e.i. the sum of both agricultural and none-agricultural lands).

**Comment by loriabendroth** [comment]
@giorgichi , was this file put somewhere that I can review? Regarding the four classes, that is what I understood also based on Ben's email. Was interested in coming up with two values per watershed of a conservative amount of drained area (only include "1" areas) and a more liberal amount (include "1" and "0.75") for us to use in the models.

**Comment by loriabendroth** [comment]
@giorgichi , disregard my question about location of file. I looked under NNK instead of ISBI!

**Comment by giorgichi** [comment]
@loriabendroth I have updated the data and variables in the **Drained Acres** sheet. Now percentages correspond to the fraction of agricultural land (only) that are likely or potentially drained. I think this can be used as an estimate for `nrspercentrowcropindrainage`.

I also added a map showing drainage classifications based on TD data and the boarded of the watershed projects.

**Comment by giorgichi** [comment]
Acres drained have been rounded up to the nearest hundreds because of the limited accuracy of the method used to estimate it.
