### ISSUE TITLE
Pull impervious layer for urban landscape from MRLC

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#256]
@giorgichi , for use in N model (NIT_07):

- [x] retrieve acres of land cover data for all years available (https://www.mrlc.gov/data/nlcd-land-cover-conus-all-years). Populate into DN_08 folder. 

- [x] extract impervious layer data and create spreadsheet with values per watershed per year. We will later fill in missing years to have annual change. 

- [x] write methods for NIT_07 under Model Input-Output folder.

**Comment by giorgichi** [comment]
@loriabendroth  Cannot unzip the downloaded file because of the size. There is not enough space in the hard disk to accommodate the unzipped file. It needs more than 156 GB of free space in order to extract zipped files. 
 

> ![image](https://user-images.githubusercontent.com/19730308/93146007-64445480-f6b3-11ea-8655-eb90c2335719.png)

**Comment by loriabendroth** [comment]
Can you send me the link where I download and I can try? Other option is to see if you can download to google drive and view from there.

**Comment by giorgichi** [comment]
Deleted some old data from my drive and bin in order to free space. This is a temporary measure in order to read the data and extract the information we need. Once it is done I will have to remove the MRLC data from my computer completely so it does not take all the space on my hard disk.

**Comment by giorgichi** [comment]
After unzipping 

> ![image](https://user-images.githubusercontent.com/19730308/93224507-ca25f000-f736-11ea-8f2a-16d1deb3707c.png)

**Comment by giorgichi** [comment]
@loriabendroth this is done now
