### ISSUE TITLE
Extract OpTIS data for tillage

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#257]
@giorgichi , you're already partially underway but adding here for traceability.

- [ ] Check statewide OpTIS tillage to statewide USDA tillage to verify similarity. Use 2017 data. Group using 3 tillage categories as done by NRCS. We had decided earlier that if within 10% between OpTIS and USDA, it is OK. 

- [x] Update methods file with conversion of tillage intensity to NRCS standards

- [ ] Add DN_09 variables to data dictionary

**Comment by giorgichi** [comment]
@loriabendroth can you provide reference to NRCS source describing tillage categories?

**Comment by loriabendroth** [comment]
This topic has been the focus of emails about tillage categories. There isn’t a NRCS reference that I or Laurie can find. Will need to wait on this component until figure out next steps.

**Comment by giorgichi** [comment]
@loriabendroth, I found that email. So we go as following:

- More than 30% (Conservation Tillage), 
- Between 15-30% (Reduced Till- age), 
- Less than 15% (Conventional Tillage)   

In this case, **No-Till** will not be separate and will become part of the **Conservation Tillage**.

**Comment by giorgichi** [comment]
@loriabendroth

**Comment by loriabendroth** [comment]
Wait on this. I am concerned about the narrowness of categories. What Steph found was different in the Census. Will need to dig into it more and across resources to figure out best approach.

**Comment by giorgichi** [comment]
> Group using 3 tillage categories as done by NRCS

I thought you have decided to adopt categories used in Corn CAP. Although, in the email, it's not clear which grouping is preferred to follow. Do you want me to reply to the email and ask the feedback or wait for additional info to come?
