### ISSUE TITLE
Extract OpTIS for cover crop

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#258]
@giorgichi , for cover crop data:

- [x] Extract cover crop data from OpTIS for HUC8 and state in all available years. Store in DN_09 folder.

- [ ] Compare statewide values for ~2017 across OpTIS, Census (DN_03), and Cost-Share (DN_18) values. We will need to decide how this collective data informs the acreage we believe are in cover crops per watershed. Ideally, Census and OpTIS will match but unlikely since Brian though OpTIS underreported. So it is likely OpTIS < Census. And then cost-share will be less than Census and give us a percent of acreage receiving funding.

**Comment by giorgichi** [comment]
@loriabendroth how do we compare cover crop acreage of OpTIS vs Cost-Share?

**Comment by giorgichi** [comment]
Based on the last ISBI meeting (2020-10-28) Laurie will compare OpTIS tillage data with NRS survey.
