### ISSUE TITLE
Structuring, review of Dunbar IPM data

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#26]
Two sets of IPM data exist for the CSCAP database: “Dunbar” and “USB”. 

Work needed on Dunbar itemized here: 

- [x] bring IPM Methods text into SS for applicable variables; I think this has been completed but cross-check.
https://drive.google.com/drive/folders/0B4fyEPcRW7IscDcweEwxUFV3YkU

- [x] remove subcategories to IPM19, IPM21, IPM22

- [x] transform data in “Pitfall” and “Sweep Nets” tabs so counts are in rows and not columns. Note that each column is of a particular insect and that insect has a specific genus, order, family, and common name. 
https://docs.google.com/spreadsheets/d/1WxB9pWvTB-_8cErQgXrybX7rklu5qXL8XyWtEf7yDVs/edit#gid=2003793642 

- [x] “Sticky traps” data is average of insects on each trap; so this is not the same type of count as first two tabs. The Sticky Trap data need to be transformed also to rows. 

- [x] do not bring Speed Scouting data into db

- [x] add genus, order, family, and common name into SS (if not already there) with an explanation and example provided. 

- [x] standardize date under Placement Date to match other datasets (include year and in number format). 

- [x] cross-check plot ids against master sheets. Dunbar data was collected from some plots in which other data variables (agro, soil) were not. Once Dunbar plot IDs are represented in plot ID masters, delete crop and treatment column as it is not following standardized codes; or retain but don’t bring into db. 

- [x] check values are appropriate for all counts; 0 to an upper limit that is reasonable for a small plot. 

- [x] update site master data collected for data collected at each site with updated IPM codes.

**Comment by loriabendroth** [comment]
@giorgichi there is a new column in SS Master Data Dictionary titled "CSCAP DB Export" with yes/no. I populated yes for IPM 20, 21, 22, 23 as these are Dunbar data types. You'll want to delete out subcategories of each code, once you have restructured data as they wont be necessary.

**Comment by giorgichi** [comment]
DUNBAR IPM data does not contains values < 0. The ranges seem reasonable (see figure below).

![image](https://user-images.githubusercontent.com/19730308/27346838-1786e962-55b4-11e7-9dec-3503878c2d0f.png)

**Comment by giorgichi** [comment]
There were 18 plots from 3 sites in Dunbar IPM data that did not match with master plot IDs. Following 14 plots were added to the Plot Identifier Google sheets for corresponding sites.
-  GILMORE   13.3
-  GILMORE   18.2
-  GILMORE   26.3
-  GILMORE    8.3
-  ISUAG    102
-  ISUAG    108
-  ISUAG    204
-  ISUAG    206
-  ISUAG    304
-  ISUAG    306
-  ISUAG    409
-  ISUAG    412
-  LAN    167
-  LAN    221

Following 4 plots from ISUAG were not added due to very high or no fertilizer application as a treatment:
-  ISUAG    212
-  ISUAG    309
-  ISUAG    312
-  ISUAG    405

**Comment by loriabendroth** [comment]
Dunbar and USB data reconciled and aligned with 14 new IPM codes.
