### ISSUE TITLE
Methods entry mechanism needed

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#260]
@giorgichi :

- [x] provide mechanism to enter methods for each variable per site in NNK. I recommend website form to allow users to enter. That way, we see what we get from them and then edit later if/as needed. But if you prefer different method, fine. 

- [x] post to website for team to see.

**Comment by giorgichi** [comment]
@loriabendroth - can you check [this form](https://docs.google.com/forms/d/e/1FAIpQLSdGPjdHSD-si4tjWyofU9fq3Dnqia8K5nsEPU-uYp49LRkvJg/viewform) and let me know if we need to make any changes.

**Comment by loriabendroth** [comment]
@giorgichi the form is great. I ran through some scenarios and worked smoothly. Will need to delete out junk from backend. Few minor comments:

- [ ] The comment after submission doesn't fit regarding emailing with a resolution. Reword this. 
- [ ] Have them rename their file upload with sitename in it so we can identify it apart from other files uploaded in the Google folder? I can see it is hyperlinked in the form though so can tell that way. 
- [ ] When I select "See previous responses" at the end, it says "No responses yet for this question" even though I entered text. Doubt that feature will be used by us or others though. 
- [ ] No way to edit form once browser is closed that I can see. But this isn't critical and don't know how much people used this feature in NN anyway.

**Comment by giorgichi** [comment]
> When I select "See previous responses" at the end, it says "No responses yet for this question" even though I entered text. Doubt that feature will be used by us or others though.

This works for me. I can see the analytics. I have tried with my other accounts and it works for them too. So it is not related to the ownership of the file. Not sure why it does not work for you. But you are correct, most likely it will not be of interest to others.

**Comment by giorgichi** [comment]
The message is changed to: "**The method has been successfully uploaded. If you want to submit another one or to edit already submitted click the corresponding link below.**"

**Comment by giorgichi** [comment]
@loriabendroth do you like an option to upload a file? Should we let to upload more than one file for each method entered? Now I have limited to only one file.

**Comment by giorgichi** [comment]
> Have them rename their file upload with sitename in it so we can identify it apart from other files uploaded in the Google folder? I can see it is hyperlinked in the form though so can tell that way

There is no option to change the file name during submission. We can do it post-factum. I can try to write an R script that does this. But to make it automatized I will need to figure out some other way.

**Comment by giorgichi** [comment]
> No way to edit form once browser is closed that I can see. But this isn't critical and don't know how much people used this feature in NN anyway.

There is a way to do it by adding Google Script. But then the form will need to be authenticated and allowed to do all that by the user - similar to what we have for management entry form.  Do you want me to try it?

**Comment by loriabendroth** [comment]
> @loriabendroth do you like an option to upload a file? Should we let to upload more than one file for each method entered? Now I have limited to only one file.

Yes, I like that! I'd increase from 1 in case people have a method and photo or something they want to include.

**Comment by loriabendroth** [comment]
> > Have them rename their file upload with sitename in it so we can identify it apart from other files uploaded in the Google folder? I can see it is hyperlinked in the form though so can tell that way
> 
> There is no option to change the file name during submission. We can do it post-factum. I can try to write an R script that does this. But to make it automatized I will need to figure out some other way.

You dont need to do that - not worth it. I was thinking of just including a statement in the question encouraging them to rename the file.

**Comment by loriabendroth** [comment]
> > No way to edit form once browser is closed that I can see. But this isn't critical and don't know how much people used this feature in NN anyway.
> 
> There is a way to do it by adding Google Script. But then the form will need to be authenticated and allowed to do all that by the user - similar to what we have for management entry form. Do you want me to try it?

No, don't bother w Google Script. It's nice to not validate when possible for ease of user. Keep as you have it.

**Comment by giorgichi** [comment]
@loriabendroth - removed all entries, modified file upload option, and linked the form to the website.
