### ISSUE TITLE
Text changes

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#262]
@akrherz 

- [x] Change text on Diss/Thesis tab (https://datateam.agron.iastate.edu/td/dl/#tab_pubs) to this instead of existing text:
Several graduate students were supported by and contributed to the scientific discoveries and publications of the Transforming Drainage team. Their theses and dissertations are provided here via links to their major University library. 

- [x] On refereed journals tab:
Do not have a space between authors and year. Ben is forcing this already within SS. 

- [x] Change "40" to "39" in third set of sentences on home page (https://datateam.agron.iastate.edu/td/)
 
- [x] On the Research Maps page, specifically the table below listed site names, photos, maps:
Add a column to the right of Institution that says "One Page Summary". The column width can be the same as photos and maps. We will eventually populate the icons and links in for these but waiting on final versions from Ben.

**Comment by akrherz** [comment]
Issue should be ready for closing?

**Comment by loriabendroth** [comment]
yes @akrherz looks good!
