### ISSUE TITLE
Standardize research site official names

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#263]
@giorgichi , standardize the research site official name column located on the Research Site tab (https://datateam.agron.iastate.edu/td/dl/#tab_sites), specifically the table below the map. This comes from the TD site metadata + history sheet. Have @akrherz reload into the webpage once done. 

Items I noticed as needing standardized:

- [x] State sometimes listed at end, sometimes not. 
- [x] Farm sometimes capitalized for Private Farm, sometimes not.
- [x] Multiple sites with same Official Name sometimes labeled as Site 1, Site 2, etc. and sometimes not.

**Comment by giorgichi** [comment]
The names are standardized already. It was done as follows:
- Sites that already had names were kept as they were (for example "Greenley Memorial Research Center")
- Sites with no names or that needed to be concealed due to privacy issue were changed to "**Private Farm at X County, STATE**"

There is only one case that says **Site 1** and **Site 2**, because that is the way Dan Jaynes used to refer them (if I am correct he used this naming in his publications as well). We can remove it to make the names more consistent.

p.s. I did correct the names for several sites - replaced "Private Farm **in** ..." with "Private Farm **at** ..."

**Comment by akrherz** [comment]
Hi @giorgichi, what's the authoritative source I should sync the site metadata from?  Presently, the site listing on the download page is generated from the database table of `meta_site_history`.

**Comment by giorgichi** [comment]
Hi @akrherz that it the authoritative file I have generated for metadata.

**Comment by giorgichi** [comment]
@loriabendroth, should we close this tub?

**Comment by loriabendroth** [comment]
@giorgichi , I am not sure what files have been updated and what file @akrherz should upload. The original google sheet doesn't have all of the edits you note as being made but the ADC file doesn't appear to be the final version either (notice how state does not follow private farms always). Please check and verify edits have been made by checking boxes in original job and then direct @akrherz on file to upload to external website.

**Comment by giorgichi** [comment]
@loriabendroth, changes are made in the Google sheet (see a column  named Official Farm Name). If everything looks fine in the master google sheet I will update the csv file for ADC.

**Comment by giorgichi** [comment]
@loriabendroth, this explains the editing of the official farm names.

> The names are standardized already. It was done as follows:
> 
> * Sites that already had names were kept as they were (for example "Greenley Memorial Research Center")
> * Sites with no names or that needed to be concealed due to privacy issue were changed to "**Private Farm at X County, STATE**"
> 
> There is only one case that says **Site 1** and **Site 2**, because that is the way Dan Jaynes used to refer them (if I am not wrong he used this naming in his publications as well). We can remove it to make the names more consistent.
> 
> p.s. I did correct the names for several sites - replaced "Private Farm **in** ..." with "Private Farm **at** ..."

**Comment by loriabendroth** [comment]
> @loriabendroth, changes are made in the Google sheet (see a column named Official Farm Name). If everything looks fine in the master google sheet I will update the csv file for ADC.

Yes, this is the sheet I was looking at when I posted yesterday. Not all sites in the official farm name have the changes you note above.

**Comment by giorgichi** [comment]
@loriabendroth I added county and state to all private farms.
