### ISSUE TITLE
Refereed Journals, Thesis/Diss Edits

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#27]
- [x] if weblink is "N/A" under Thesis/Diss, do not include it

- [x] 5 occurrences of "N/A" within Ref Journals tab with 4 under Volume and 1 under Page Number. Do not include these. I can also alter SS, if you prefer that. (daryl: I did not find any of these anymore)

- [x] for hyperlinks under both tabs, change so they open up in new browser

- [x] move Referred Journals tab to right of Research Sites

- [x] delete "CSCAP Research Publications" text at top of Ref. Journals tab. Will supply text soon to include here instead.

**Comment by loriabendroth** [comment]
Refereed journals and thesis/diss could be grouped under Publications. I am figuring a third category will eventually exist - one that lists the non-team papers that use our data btw.

**Comment by akrherz** [comment]
All done except the count value.  Do you still want this?

**Comment by loriabendroth** [comment]
Lori

Lori Abendroth
Project Manager
515.294.5692
labend@iastate.edu<mailto:labend@iastate.edu>

On Jul 12, 2017, at 11:23 AM, daryl herzmann <notifications@github.com<mailto:notifications@github.com>> wrote:


All done except the count value. Do you still want this?

**Comment by loriabendroth** [comment]
No, it's not critical.



On Jul 12, 2017, at 11:23 AM, daryl herzmann <notifications@github.com<mailto:notifications@github.com>> wrote:


All done except the count value. Do you still want this?

**Comment by loriabendroth** [comment]
@akrherz few things:
- [ ] N/A's still exist; 5 of them. Search by "N/A" on page.
- [ ] Possible to create two subcategories under Publications for (1) Refereed Journals and (2) Thesis and Dissertations? This is my preference, but earlier comment was unclear. So that when someone goes to Publications they select one of the two. Publications would have no content but just be tab title. 
- [ ] Delete "CSCAP Team Publications" header at top and only have "Articles with open access..." text for Refereed Journals.

**Comment by akrherz** [comment]
@loriabendroth 

- Those N/A values on the page are for the `volume` value and not the web link.  You want those removed too?

**Comment by loriabendroth** [comment]
Yes if possible. But I can remove in original file if difficult.

**Comment by akrherz** [comment]
@loriabendroth OK, done
