### ISSUE TITLE
Edits needed to DWM data

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#273]
@giorgichi , edits are needed to the DWM tab. I have completed a few of them already. Please complete others. 

- [x] In comments, remove inch abbreviation (") and "inch" throughout and switch to "inches" 
- [x] In comments, convert all "inches" to standard metric units of cm
- [x] In comments, make sure all sentences end in (.), especially important when text follows to separate comments. 
- [x] In comments, some instances of "v-notch" are upper and others lowercase. Standardize. 
- [x] In comments, remove all references to people, i.e. Barbara, Ralph, Bruce, Eric, etc. Don't want this in external data. If sentences are critical, anonymize. If not critical, delete.
- [x] In comments, it often says "controlled drainage" or "free drainage". This needs to be a complete sentence. Does this mean it was put into controlled drainage mode from free drainage mode? And vice versa for free drainage? 
- [x] Several comments are sentence fragments. Best to write out as a complete sentence to ensure comprehension by users. 
- [x] Ensure standard language used across sites. For example, what are "drop logs" compared to "boards"? And at Hicks, there is "fall raise", "spring raise", etc which is different terminology than other sites such as "Plates removed". 
- [x] HEIGHT is capitalized often in comments. Is this appropriate? 
- [x] In box_structure, should zone be capitalized at DEFI_R?

**Comment by giorgichi** [comment]
@loriabendroth, all **v-notch**s are replaced with **V-notch**.

**Comment by giorgichi** [comment]
I think I found all personal references and removed them. Few comments were modified to passive voice.

**Comment by giorgichi** [comment]
> In comments, it often says "controlled drainage" or "free drainage". This needs to be a complete sentence. Does this mean it was put into controlled drainage mode from free drainage mode? And vice versa for free drainage?

I assume so too. I will change "**controlled drainage**" or "**free drainage**"  to "**Controlled drainage treatment plot was put in managed drainage mode.**" or "**Controlled drainage treatment plot was put in free drainage mode.**" respectively. This is a wording that is used by the same PI (Kelly Nelson) for other entries.

**Comment by giorgichi** [comment]
@loriabendroth, 

I also changed "**Controlled Drainage mode**" and "**Drainage mode**" to "**Controlled drainage treatment plot was put in managed drainage mode.**" and "**Controlled drainage treatment plot was put in free drainage mode.**" respectively. This is a wording that is used by **Kelly Nelson** for other entries.

**Comment by giorgichi** [comment]
> In box_structure, should zone be capitalized at DEFI_R?

There is no need to capitalize **zone**. I will keep it as it is.

**Comment by loriabendroth** [comment]
@giorgichi , I like the changes you made for drainage mode explanation in comments.

**Comment by giorgichi** [comment]
>  HEIGHT is capitalized often in comments. Is this appropriate?

@loriabendroth, this is an important detail. Usually, outlet depth is reported as **DEPTH** from the soil surface. However, for WIRSIS sites this is reported as **HEIGHT** from the bottom of the control structure. Even those both are measuring the same thing, the reference point (and direction of measurement) are different. 

One way to eliminate this is to create a new variable called `outletheight`, which will contain that data. 

One more thing, **FULTON** has only one entry. Knowing board hight at one specific time doe not really have much value, so I am going to mark it `remove` in the `action` column.

Your thought about the last two points.

**Comment by giorgichi** [comment]
**All opened on 2015-07-10** changed to **The plot was put in free drainage mode.**

**Comment by giorgichi** [comment]
> HEIGHT is capitalized often in comments. Is this 

A new column `outletheight` added to accommodate corresponding data. Some comments contained information about outlet heights (most of OH sites), which were also moved there (and removed from the comments as ap[propriate).

**Comment by giorgichi** [comment]
>  Ensure standard language used across sites. For example, what are "drop logs" compared to "boards"?

Left intact as it often corresponds to the language used by PIs in their peer-reviewed publications.

**Comment by giorgichi** [comment]
Some comments at CLAY_R were redundant and replaced with "n/a".

- The depth from top to weir: 160.0 cm in SI structure and 111.8 cm in CD structure, from 2014-05-01 to 2014-06-29.
- The depth from top to weir: 111.8 cm in SI structure and 55.9 cm in CD structure, from 2014-07-25 to 2014-08-28.
- The depth from top to weir: 238.8 cm in SI structure and 2515 mm in CD structure, from 2014-09-11 to 2014-09-24.
- The depth from top to weir: 111.8 cm in SI structure and 55.9 cm in CD structure, from 2015-06-16 to 2015-06-24.
- The depth from top to weir: 142.2 cm in SI structure and 81.3 cm in CD structure, on 2015-06-30.

**Comment by giorgichi** [comment]
Some comments at DEFI_M were redundant and replaced with "n/a".

- 81.3 cm from bottom of control structure to outlet depth (apex of V-notch).
- 3.8 cm from bottom of control structure to outlet depth (apex of V-notch).
- 63.5 cm from bottom of control structure to outlet depth (apex of V-notch).
- 3.8 cm from bottom of control structure to outlet depth (apex of V-notch).
- 94.0 cm from bottom of control structure to outlet depth (apex of V-notch).
- 33.0 cm from bottom of control structure to outlet depth (apex of V-notch).
- 38.1 cm from bottom of control structure to outlet depth (apex of V-notch).
- 86.4 cm from bottom of control structure to outlet depth (apex of V-notch).
- 7.6 cm from bottom of control structure to outlet depth (apex of V-notch).
- 68.6 cm from bottom of control structure to outlet depth (apex of V-notch).
- 7.6 cm from bottom of control structure to outlet depth (apex of V-notch).
- 68.6 cm from bottom of control structure to outlet depth (apex of V-notch).
- 7.6 cm from bottom of control structure to outlet depth (apex of V-notch).

**Comment by loriabendroth** [comment]
> > HEIGHT is capitalized often in comments. Is this
> 
> A new column `outletheight` added to accommodate corresponding data. Some comments contained information about outlet heights (most of OH sites), which were also moved there (and removed from the comments as accordingly).

Good. I was going to respond to earlier comment to add column since it is a different variable. Update data dictionary accordingly.

**Comment by loriabendroth** [comment]
> > Ensure standard language used across sites. For example, what are "drop logs" compared to "boards"?
> 
> Left intact as it often corresponds to the language used by PIs in their peer-reviewed publications.

For clarity of the user, when the text is referring to the same thing ("board"), I think best to standardize. To retain specificity used in the journal article, can you put in quotes following text such as "drop logs (i.e. "boards")".

**Comment by loriabendroth** [comment]
Regarding: One more thing, FULTON has only one entry. Knowing board hight at one specific time doe not really have much value, so I am going to mark it remove in the action column.

Agree. Fine to remove. Put a note in Notes that no board heights were reported for the site years.

**Comment by loriabendroth** [comment]
> I think I found all personal references and removed them. Few comments were modified to passive voice.

One remaining reference: DEFI_R 2003 has "I stopped..."

**Comment by loriabendroth** [comment]
@giorgichi couple remaining comments that could possibly be generalized more for external user or removed. Such as reference to DARA at DEFI_R sites. I haven't seen DARA abbreviation before so if retain, make sure to define. "Plates removed..." terminology at SERF_IA seems like it should be standardized how you changed others to be "controlled drainage treatments plots had..." Also, in 2017 and 2018, comments at SERF_IA are including plot numbers which are unnecessary. Same with TIDE in 2007. And UBWC - remove reference to multiple plots when row entries are for 1 specific plot.

**Comment by giorgichi** [comment]
Remove plot names in comments at SERF_IA.

**Comment by giorgichi** [comment]
Removed plot names in comments at TIDE.

**Comment by giorgichi** [comment]
Comments with plot names rewritten at UBWC.

**Comment by giorgichi** [comment]
**DARA** remove from the comments at DEFI_R.

**Comment by giorgichi** [comment]
Comments updated at SERF_IA.

>  "Plates removed..." terminology at SERF_IA seems like it should be standardized how you changed others to be "controlled drainage treatments plots had..."

**Comment by giorgichi** [comment]
The name was standardized as applicable. Flashboard, drop log, plate, outlet board, riser boards, and gate were replaced with the board.
