### ISSUE TITLE
Site Metadata edits needed

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#274]
@giorgichi , 

- [x] need area for each field (i.e. plot) at ACRE to be included. Not sure if you have this or if will need to reach out to Charlotte and Laura. This information will need to be included in Site Metadata sheet. As of now, it says site area is 68.8 and plot size is 1.2. But this varies by field. 
- [x] does purple text denote edits needed in plot size column? 
- [x] lower or uppercase Experimental Design column consistently 
- [x] landscape slope column is blue; does this denote edits needed? 
- [x] TBDs across spreadsheet need to be populated or n/a or unknown.
- [x] address red font in lat long
- [x] Additional Information column should be reviewed for necessity and reworded as complete sentences if retained. 
- [x] soil texture columns are upper and lower case text. Standardize.

**Comment by giorgichi** [comment]
Soil texture are converted to lower cases.

**Comment by giorgichi** [comment]
Eperimental design are converted to title case.

**Comment by giorgichi** [comment]
I think Plot Size should be removed from the site metadata & history table, because all this is provided in plot identifier table.

**Comment by giorgichi** [comment]
> address red font in lat long

I am not sure why they are red.

**Comment by giorgichi** [comment]
Landscape slope for WILKIN sites contains direction, while no other site provides that detail. Should we have only the slope value, or should we leave as it is?

**Comment by giorgichi** [comment]
Plot identifier table lists drainage area for each plot. At ACRE we have plot areas for Inlet_A and Inlet_B, which represents two drainage treatment fields.

**Comment by giorgichi** [comment]
Additional Information is not retained, hence no need for revision.

**Comment by loriabendroth** [comment]
> I think Plot Size should be removed from the site metadata & history table, because all this is provided in plot identifier table. Thought, Site Area will maintain the table. @loriabendroth, do you agree?

Yes, that is fine. Remove.

**Comment by loriabendroth** [comment]
> Eperimental design are converted to title case.

NONE does not need to be in all caps. Should be None. For the others, should be capitalized similarly as RCBD, etc... such as Split-field Design, Split-Block Design, etc. Insert hyphen as here in example: https://doi.org/10.1016/j.jspi.2004.06.021

**Comment by loriabendroth** [comment]
> Soil texture are converted to lower cases.

Is this change made in the original? Still issues with soil texture columns.

**Comment by loriabendroth** [comment]
> Landscape slope for WILKIN sites contains direction, while no other site provides that detail. Should we have only the slope value, or should we leave as it is?

Only include slope without direction is my vote. Otherwise need to specify in data dictionary this nuance among sites.

**Comment by giorgichi** [comment]
> NONE does not need to be in all caps. Should be None. 

Done

**Comment by giorgichi** [comment]
> For the others, should be capitalized similarly as RCBD, etc... such as Split-field Design, Split-block Design, etc. 

Done

**Comment by giorgichi** [comment]
> > Soil texture are converted to lower cases.
> 
> Is this change made in the original? Still issues with soil texture columns.

To see all changes see the corresponding csv file in ADC folder. Some changes are done via R code, hence not all edits can be found in the Google Sheet.

**Comment by giorgichi** [comment]
> > Landscape slope for WILKIN sites contains direction, while no other site provides that detail. Should we have only the slope value, or should we leave as it is?
> 
> Only include slope without direction is my vote. Otherwise need to specify in data dictionary this nuance among sites.

Done

**Comment by giorgichi** [comment]
meta_site_history.csv has been updated.

**Comment by loriabendroth** [comment]
@giorgichi , looks terrific. thanks for clarifying where to look for changes.
