### ISSUE TITLE
Check ACRE Plot 8 Yield 

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#275]
@giorgichi , missing one plot of data in agronomic spreadsheet:

- [  ] field 8 which has yield in 2010 and 2012 but missing field 8 in _Ag_Data_Commons agro spreadsheet. All other fields are there.

**Comment by giorgichi** [comment]
@loriabendroth, based on Charlotte Lee's suggestion I removed yield data from plots <2 acres. That is why field 8 is missing.

**Comment by giorgichi** [comment]
I asked L. Bowling about this and she gave me a green light.

**Comment by loriabendroth** [comment]
OK @giorgichi
