### ISSUE TITLE
Remove CLAY_C 2012 yield per PI request

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#276]
@giorgichi , 

- [x] remove 2012 yield data for CLAY CD/SI field as per email from Jia on 2020.01.15. As of now, the yield is included in ADC export version. It wasn't included in DWR paper either. 
"The landowner in the CD/SI field used a new late variety, but experienced a severe drought condition with a poor germination rate in the spring, and a poor yield. Using the data will change the results. **I think this would be better to stay as internal data**."

**Comment by giorgichi** [comment]
2012 agronomic data removed at **CLAR_R** and corresponding csv file is updated in [ADC Google Drive](https://drive.google.com/drive/u/1/folders/1zblZuTiEUdZOq1_IHgO_gEtR018TidRq).
