### ISSUE TITLE
Convert to metric units

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#279]
@skbowd , convert all inches and feet text in comments to metric for NNK management data.

**Comment by skbowd** [comment]
@loriabendroth  Should I convert all English to metric?  I.e. bu/acre, lb/acre, etc?

**Comment by loriabendroth** [comment]
@skbowd , yes review all text in comments and make sure everything is in metric. thanks

**Comment by skbowd** [comment]
Done through 2021.01.12.
