### ISSUE TITLE
Edit lat, long in ADC file

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#285]
@giorgichi , changes needed based on decisions from power session:

- [ ] edits are needed to resolution for private farms (MO_KNOX3, IA_STORY2, MN_CLAY1-3, IA_HAMILTON1-3, IA_TAMA, IA_GRUNDY, IA_STORY1, IA_BOONE, ND_RICHLAND). Lat and long should be one decimal place with X in hundredth place based on decision by PIs, i.e. 41.1X to flag that this has been removed to users. Make a note of this in data dictionary also. Currently, resolution is to tenth only at 5 of the private farms.

**Comment by giorgichi** [comment]
@loriabendroth, s there a reason fo excluding OH private sites from your list?

**Comment by giorgichi** [comment]
Lat and Long of all 29 private sites have been masked accordingly.
