### ISSUE TITLE
Edit decimals for drainage system specs

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#286]
@giorgichi , Matt had noted these specs to us earlier. Please change ADC file to align:

- [x] Drainage coefficient reported to xx.x
- [x] Drainage depth reported to x.xx
- [x] Drainage spacing reported to xx.x

**Comment by giorgichi** [comment]
@loriabendroth, do you also imply to show the trailing zeros? For example, If the drainage depth is 1, should I make it to 1.00?

**Comment by loriabendroth** [comment]
Yes, we need to show same precision across all variables even if zero.

Lori
________________________________
