### ISSUE TITLE
Verify weather stations used

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#287]
@akrherz , I noticed the IEM station we listed in the TD Site Metadata + History google sheet is different for 4 sites from what is populated on external site. Which is correct? The four that differ are highlighted orange in ss but also listed here:

state_county -> Google ss -> website
IA_Story1 -> IAC005 -> IA0241
IA_Tama -> IA8568 -> IA0600
OH_Hardin2 -> OH4189 -> OH2786
OH_Henry -> OH3874 -> OH8822

**Comment by akrherz** [comment]
@loriabendroth, the website is correct.  Sadly, I am struggling to find the Google SS to update.  Could you kindly point me to it?

**Comment by loriabendroth** [comment]
@akrherz , see column BA here https://docs.google.com/spreadsheets/d/1oZ2NEmoa0XHSGTWKaBLt0DJK1kIbpWO6iSZ0I2OE2gA/edit?pli=1#gid=0

**Comment by akrherz** [comment]
Thanks, updated.
