### ISSUE TITLE
Create Management Tab & Populate

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#29]
- [x] create "Site History, Management" tab after YEAR tab in /dl. 

- [x] add 4 tabs (Field Operations, Pesticides, Management, DWM) from spreadsheet (https://docs.google.com/spreadsheets/d/1CdPi6IEnO3T35t-OFQajKYzFLpu7hwOaWdL2FG1_kVA/edit#gid=0) as options for people to download. Change "Management" to "Residue, Irrigation" and "DWM" to "Drainage Control Structure Management". Do not bring in Notes. 

- [x] add Site Metadata (https://docs.google.com/spreadsheets/d/1tQvw-TQFtBI6xcsbZpaCHtYF7oKZEXNXy-CZHBr8Lh8/edit?hl=en_US&pli=1&hl=en_US&pli=1#gid=0) to Site History, Management tab also. Include blue columns only.

- [x] bring in lat, long coordinates; @giorgichi determine which are most appropriate from columns G - Q. My preference are four corners if possible. Ensure matches Google map. Standardize format as differs by site. 

- [x] add Soil Series Description from Plot ID sheets (https://sites.google.com/site/sustainablecorn/database/plot-identifiers) to Site History, Mngt tab also. Bring in columns A, H, K-V for each site. Not sure if this will work very well though when selecting a lot of sites for download. thoughts?

- [x] update SS Master Dictionary "CSCAP DB Export" for each applicable variable here to yes/no.

- [x] lori determine whether text from Notes (https://docs.google.com/spreadsheets/d/1CdPi6IEnO3T35t-OFQajKYzFLpu7hwOaWdL2FG1_kVA/edit#gid=1342359877) or non-blue text from Site Metadata comes in (https://docs.google.com/spreadsheets/d/1tQvw-TQFtBI6xcsbZpaCHtYF7oKZEXNXy-CZHBr8Lh8/edit?hl=en_US&pli=1&hl=en_US&pli=1#gid=0)

**Comment by giorgichi** [comment]
@loriabendroth have no preference for Lat-Long data. We can use 4 corners but not all plots have 4 corners. And what should we do in case of ORR or GILMORE?

**Comment by loriabendroth** [comment]
@akrherz you're done with this once the third item is added into export. The last two items listed are me.
