### ISSUE TITLE
Site Metadata Comments

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#291]
@giorgichi , comments are important context to retain for sites but need edits:

- [ ] In column BK, anonymize names such as Ben, Chris, or rewrite so not relevant.
- [ ] spelling errors exist in some of text. 
- [ ] Read all text and remove non-essential for external users. I can see quite a bit that should be removed or rewritten to be clearer to users. 
- [ ] All text should be complete sentences with punctuation especially important for non-native speakers. ~~ 
- [ ] Soil series1 doesn't exist for 3 sites. Include a comment about this since there is obviously soil there so need to state that we know it is missing.

**Comment by loriabendroth** [comment]
@giorgichi , I see your comment about not retaining this information for users. I will rereview as I thought some was valuable.

**Comment by loriabendroth** [comment]
@giorgichi , ok to ignore comments. Main ones I thought were valuable were saturated buffer installation dates. Ignore first 4 items, but address soil series still.

**Comment by giorgichi** [comment]
> Soil series1 doesn't exist for 3 sites. Include a comment about this since there is obviously soil there so need to state that we know it is missing.

Soil series name (1) is specified fall all sites. I assume you are talking about soil complexes that do not have soil descriptions and other info. This is because these complexes do not have such information. Therefore I put "n/a"s.

**Comment by giorgichi** [comment]
@loriabendroth, I corrected some minor errors in the site history and updated the file in ADC Google Drive.
