### ISSUE TITLE
Remove id columns from trt or plot identifier sheet

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#294]
@giorgichi , there is some duplication between these two sheets and I'd like the details to only be in one for maximum clarity. My recommendation is the following. What do you think?

- [x] Move columns C-F from meta_plot_identifiers to meta_treatment_identifier so that all identifiers are together in one sheet for plot, drainage, irrigation monitoring. 
- [x] Rename meta_plot_identifiers to meta_plot_characteristics

In the meta_plot_characteristics sheet:
- [x] Recommend changing comment text so that first word is capitalized and text is interpretable and not just fragment. 
- [x] Change wording from "tile depth 2.5 - 3.5 ft" to "Tile depth is 2.5 to 3.5 ft". 
- [x] Change from "-" to "to" in all cases to eliminate any potential formatting that Excel may do when csv is converted. 
- [x] Convert all comment text to metric units. 
- [x] Rename meta_site_history to meta_site_characteristics to be similar verbage

**Comment by giorgichi** [comment]
@loriabendroth, all suggestions look good to me. But I have to work on NN now. I will get to this and other comments later this week (Thursday most likely). 

Please post any farther suggestions on GitHub.

**Comment by giorgichi** [comment]
@loriabendroth, I rewrote the comments, added some missing values, corrected a few erroneous entries, and updated the file in ADC Google Drive. 

DWM and irrigation treatment columns have been merged with the meta_treatment_identifier.

**Comment by giorgichi** [comment]
@loriabendroth, there are two columns `dwnid` and `irrid` in the **meta_plot_characteristics** that I decided not to move to the **meta_treatment_identifier**.  But I am not quite sure where is the best table for those two.

**Comment by giorgichi** [comment]
@loriabendroth, I think your suggestion to move `dmwid` and `irrid` to **meta_treatment_identifier** is a better option. So I updated files accordingly.
