### ISSUE TITLE
Edits to site history

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#295]
@giorgichi , few edits:

- [x] change "-" to "to" in the landscape slope, tile_depth, depth to restrictive layer, tile grade, and drainage coefficient columns
- [x] when I open the csv files in Excel, I am getting conversion to dates in landscape_slope for a couple Knox sites
- [x] have depth to restrictive layer reported to X.XX at most
- [x] in buffer vegetation option, change "Grass" to "grass"
- [x] drainage installation year for Knox Tile 3 has a semicolon, other cases use a "," only. Not big deal obviously. 
- [x] soil texture column has "NA" whereas others are "n/a"

**Comment by giorgichi** [comment]
Cannot find any of this.
> soil texture column has "NA" whereas others are "n/a"

I was doing some editing of the same table several hours ago. Maybe I corrected **NA**s before seeing your post.

**Comment by giorgichi** [comment]
@loriabendroth, the file has been updated and uploaded into ADC Google Drive.

**Comment by loriabendroth** [comment]
> Cannot find any of this.
> 
> > soil texture column has "NA" whereas others are "n/a"
> 
> I was doing some editing of the same table several hours ago. Maybe I corrected **NA**s before seeing your post.

@giorgichi , can you check again. I opened the newest ADC file in notepad and seeing NA while others are n/a.

**Comment by loriabendroth** [comment]
@giorgichi , some text is in quotes while others are not. Can you also check if all variables are same type (character, etc).

**Comment by loriabendroth** [comment]
> > Cannot find any of this.
> > > soil texture column has "NA" whereas others are "n/a"
> > 
> > 
> > I was doing some editing of the same table several hours ago. Maybe I corrected **NA**s before seeing your post.
> 
> @giorgichi , can you check again. I opened the newest ADC file in notepad and seeing NA while others are n/a.

It appears in other sheets that "NA" is primarily used. I am fine with either NA or n/a, can you ensure consistency across sheets?

**Comment by giorgichi** [comment]
> > Cannot find any of this.
> > > soil texture column has "NA" whereas others are "n/a"
> > 
> > 
> > I was doing some editing of the same table several hours ago. Maybe I corrected **NA**s before seeing your post.
> 
> @giorgichi , can you check again. I opened the newest ADC file in notepad and seeing NA while others are n/a.

I found them. Originally I was checking the Google Sheet and could not find and NAs there. But now I checked the file and found all of them. I think I populated them via script. I will find that piece of code and fix the problem.

**Comment by giorgichi** [comment]
I replaced "NA" with "n/a" and updated the file in ADC Google folder.
