### ISSUE TITLE
Boards managed at STORY 2008, 2009?

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#297]
@giorgichi , I noticed no entries were in backend for DWM management in 2008 or 2009, only 2006 and 2007. Can you check if you have this information? I reviewed SS checklist and don't see any applicable comments there about this. And nothing in the Notes tab of management form. 

I noticed this visually checking across mngt sheets. Can you programmatically check? Any year that is not in all of the management sheets, can be listed in the Notes tab. At least that is how we have it now with an explanation in some cases as to why it is missing or unknown.

**Comment by giorgichi** [comment]
@loriabendroth, I see DWM data for all four years (2006 to 2009) in the backend sheet. I assume the table was filtered when you were checking it.

**Comment by giorgichi** [comment]
Attached is a file listing sites with corresponding years of DWM information. 

[dwm_by_site_year.csv.gz](https://github.com/isudatateam/datateam/files/5839080/dwm_by_site_year.csv.gz)

**Comment by loriabendroth** [comment]
@giorgichi , yes I had a filter on that I didn't realize. The file you attached isn't viable but that's fine, I will simply close.
