### ISSUE TITLE
Reingest notes data

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#298]
@giorgichi , for the management notes data: 

- [x] I made changes to backend, resave to ADC folder
- [x] Six entries at end of ADC file are NA for site. Figure out issue here. Are these affiliated with a site that was removed?

**Comment by giorgichi** [comment]
> Six entries at end of ADC file are NA for site. Figure out issue here. Are these affiliated with a site that was removed?

@loriabendroth, good catch! This is caused by misspelling of the site unique ids. Instead of WILKIN, it says WILKIN**S**.  I corrected this error via script.

**Comment by giorgichi** [comment]
The file has been updated.
