### ISSUE TITLE
Reconcile soil, water, and weather dictionaries

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#300]
@giorgichi , the Google version and the SS versions should be reconciled to be identical other than the Google is a subset. I have been working on it but will not have time again until weekend. Please work on these dictionaries. I will do others. 

https://docs.google.com/spreadsheets/d/1QU858NHlkZ4L23dmAZ7zwFsVdEmmu-vhbF5o1EFk8pw/edit#gid=715750743
https://app.smartsheet.com/sheets/gvp622QHWM89QjWmwfVhRr6r7mhx9gVfqxwcj461 

- [x] Overall, in Google, under data type, you have "decimal". Do you mean "double"?
- [x] Populate missing cells and reconcile discrepancies in weather dictionary . Such as acceptable values, etc. We have the values in SS for many. 
- [x] Populate missing cells and reconcile discrepancies in water table dictionary. 
- [x] Populate missing cells and reconcile discrepancies in water stage dictionary. 
- [x] Populate missing cells and reconcile discrepancies in water quality dictionary. 
- [x] Populate missing cells and reconcile discrepancies in tile flow and N loads dictionary. 
- [x] Populate missing cells and reconcile discrepancies in soil properties dictionary.

**Comment by giorgichi** [comment]
Need to reconcile problematic discharge readings at OH_Defiance2.

**Comment by giorgichi** [comment]
Data dictionary will be updated to include new tables that I will create after splitting field management data by operations (in particular planting and fertilizing data will be devided into two tables).
