### ISSUE TITLE
Reconcile discrepancy in N applied

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#301]
@skbowd , Alison had asked Gio and I some questions after reviewing the data. One item for you:

- [ ] Look at item 6i in this list and provide a response as well as reconcile in spreadsheets if needed/possible.
https://docs.google.com/document/d/1b8Pnq-mGwyXt0YmrB5r1JRySDi1ZsPd_LY2CBci99vU/edit#

**Comment by skbowd** [comment]
@loriabendroth   
I am seeing 40 and 95 lbs N being applied for 2018 in the management form, not 40 and 90 lbs as indicated under 6i.  The applications are 44.83 and 106.48 kg N ha-1.  This is 151.31 kg N ha-1 or 135 lbs/acre.  The yearly treatment data by plot indicates 135 lbs N is correct.

https://docs.google.com/spreadsheets/d/1K0xCmm1R5KHBRRqyBQaoNtTx4T3qa8RKOKb85EWwlQw/edit#gid=0

https://docs.google.com/spreadsheets/d/1kTICpb3_QIb9w5523hwJJs0ectav_WRQ255ud59aLGU/edit#gid=1339691610

**Comment by loriabendroth** [comment]
@skbowd can you check the version that Gio uploaded and made available to Alison? That would be under the NN drive with "data sent to Alison". It may be OK there and just a typo in notes?

**Comment by skbowd** [comment]
@loriabendroth    I checked the most recent csv files Gio uploaded for Alison.  All of those have 135 lb N listed for those plots as well.

**Comment by loriabendroth** [comment]
thanks @skbowd
