### ISSUE TITLE
Finalize DWM management

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#302]
@giorgichi , items remaining and then done with this table:

- [ ] make sure n/a is populated for outletdepth or outletheight as appropriate. 
- [x] Change TBD to n/a.
- [ ] Make sure unknown is only in one column or the other, see Hardin_NW. 
- [x] Look at red entries for DEFI_R, why are these remove? All other cases of unknown are retained. See CLAY_R and HARDIN_NW.

**Comment by giorgichi** [comment]
> Make sure unknown is only in one column or the other, see Hardin_NW.

@loriabendroth I do not get what you want me to do about this? This request can introduce inconsistencies in the data.

**Comment by giorgichi** [comment]
> Look at red entries for DEFI_R, why are these remove? All other cases of unknown are retained. See CLAY_R and HARDIN_NW.

@loriabendroth, tile flow data at DEFI_R starts from 1999, hence any DWM management before that is not of interest.

**Comment by giorgichi** [comment]
@loriabendroth, you have marked some entries for TIDE in red and the `action` column says n/a. Could you reconcile those or let me know what should I do with them? 

p.s. the corresponding comment should also be deleted or edited.

**Comment by loriabendroth** [comment]
> > Make sure unknown is only in one column or the other, see Hardin_NW.
> 
> @loriabendroth I do not get what you want me to do about this? This request can introduce inconsistencies in the data.
> 
> The logic is following, generally, all three variables (`outletdepth`, `outletheight`, and `outlet_date`) are reported at HARDIN_NW. If any of them are missing we replace it with "unknown".

Unknown was listed for both outletdepth and outletheight at that site. But only one of those should be reported for each site, so one should always be n/a and the other would be a number or unknown.

**Comment by loriabendroth** [comment]
> > Look at red entries for DEFI_R, why are these remove? All other cases of unknown are retained. See CLAY_R and HARDIN_NW.
> 
> @loriabendroth, tile flow data at DEFI_R starts from 1999, hence any DWM management before that is not of interest.

OK, can you delete if not applicable?

**Comment by giorgichi** [comment]
> Unknown was listed for both outletdepth and outletheight at that site. But only one of those should be reported for each site, so one should always be n/a and the other would be a number or unknown.

I think both should be unknown. Otherwise, I will need to replace all "unknown"s with "n/a"s to keep the data consistent.

![image](https://user-images.githubusercontent.com/19730308/106818260-a6a80700-663d-11eb-9c7b-9a3fbc13c4f8.png)

**Comment by giorgichi** [comment]
I reconciled TIDE as folowing.

BEFORE
![image](https://user-images.githubusercontent.com/19730308/106819263-25ea0a80-663f-11eb-84a7-568c9f5119fa.png)

AFTER
![image](https://user-images.githubusercontent.com/19730308/106819437-69447900-663f-11eb-99af-4011263b9d4b.png)

This way the data is matching with one used in N Load synthesis paper and is formatted according to other sites (such as SERF_IA in 2013 and 2014).

**Comment by loriabendroth** [comment]
@giorgichi , that's a good approach to set them at a constant level.
