### ISSUE TITLE
Create TD portal on USDA NAL ADC

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#306]
@giorgichi , 

- [x] create a TD platform on USDA NAL ADC under your username. 
- [x] populate with document text that I will forward momentarily to your email from earlier TD portal that was under my username (but has been deleted).

**Comment by giorgichi** [comment]
@loriabendroth cannot populate the map the same way we did last time. Need to figure out how to add the state map.

Can you see the ADC page?
https://data.nal.usda.gov/dataset/transforming-drainage

**Comment by loriabendroth** [comment]
@giorgichi , unfortunately no. It says access is denied. Anywhere you can add me or should we check with NAL about this?

**Comment by giorgichi** [comment]
@loriabendroth got the state map in GeoJSON format.

**Comment by giorgichi** [comment]
@loriabendroth there is no way to share the dataset. Only one account can access it for editing. I can share the password with you if you want to check.

**Comment by loriabendroth** [comment]
@giorgichi terrific on map. For NAL, either you can share password with me today or share your screen during tomorrow's meeting.
