### ISSUE TITLE
Exporting hourly time series data

### ISSUE THREAD

**Issue by giorgichi** [isudatateam/datateam#31]
Due to potential problems associated with generating large files within timeout limits of the web browser, the export tool will allow user to **export only hourly aggregated time series data**.  For exporting not-aggregated data users will be prompt to use data visualization tool. To make the workflow faster:
- [ ] pregenerate hourly Water and Decagon data, so the server will not use its processing capacity to generate requested data on demand
- [ ] add both Water and Decagon data selection options to the Water tab.
- [ ] the list of variables to be exportable (besides timestamp and site/plot id):
* WAT1, WAT2, WAT4, WAT8, WAT9, WAT20  (based on #25)
* DECAGON: volumetric soil water content, soil temperature, soil EC

P.S. excel spreadsheet can fit 120 years of hourly data, which should be suffice for CSCAP water data.

**Comment by akrherz** [comment]
The prospect of pre-generating hourly summary data is an additional one-off that would need to be tracked as updates to the underlying data would require the hourly data to be regenerated.  The `decagon_data` table is currently 26 million rows, so doing on-demand aggregates over potentially that entire table won't be much fun.

**Comment by loriabendroth** [comment]
Let's forget the aggregation at this point and simply allow users to access the tools. The editing capability of the tools can remain for the next month while PIs are reviewing but will then need to be removed once goes external.

**Comment by loriabendroth** [comment]
Closing this job and adding new job regarding some water data edits needed. This is out of date.
