### ISSUE TITLE
Copy soil and plot maps into ADC folder

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#313]
@giorgichi , 

- [x] copy all of the soil maps from Field Research Sites > Research Site Maps > Soil Maps into maps folders at Data Spreadsheets > _Ag_Data_Commons > TD_Maps_and_Photos
- [x] do the same with plot maps also. It is fine to have several plot maps if there are different views or timeline shown.

**Comment by giorgichi** [comment]
@loriabendroth I will standardize file names, including replacing old site names with the new one.

**Comment by loriabendroth** [comment]
@giorgichi , will you be able to get done before tomorrow's meeting or should I try and get done? I want the folders to have items in them so people can see how it will work.

**Comment by giorgichi** [comment]
Edited some maps to remove old site names that were "printed" on them. 
Created few additional maps (for MO_Knox4)

**Comment by loriabendroth** [comment]
@giorgichi , thanks
