### ISSUE TITLE
Resort table by drainage practice

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#316]
@akrherz , resort the table on this page (https://datateam.agron.iastate.edu/td/dl/#tab_sites) by practice as outlined here under Sites (https://datateam.agron.iastate.edu/td/dl/#tab_data). To do:

- [x] move SB sites to top, followed by CD, then DWR, then Other
- [x] Add color to the table to align with map color. This way the sites are easily recognizable. So SB sites are green, CD are blue, DWR are purple-red, and Other are white. If you have an idea for how to color, go for it. Otherwise, could repeat the header above each group of applicable cells and color the header background or header text. Or could outline the applicable cells with a border color that matches.

**Comment by akrherz** [comment]
@loriabendroth I added a colored bar to the left hand side of the table.  That what you had in mind?

**Comment by loriabendroth** [comment]
@akrherz perfect!
