### ISSUE TITLE
Changes to plotting tool

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#317]
@akrherz , edits to the tool (as possible), these are for the nitrate load tool but I am assuming that once we get this one perfect, then you can "easily" replicate to the other measurements in the list? 
https://datateam.agron.iastate.edu/td/plot_nitrateload.phtml

- [x] Change from Aggregating to Deaggregating option. So that the default is to show by treatment instead of by plot. So change text to say "Show Plot Values instead of by Treatment" and a checkbox that they have to click. 
- [x] Have the site dropdown sorted by practice as listed here under Sites https://datateam.agron.iastate.edu/td/dl/#tab_data. Put a header above each group of sites... so it is like:
----Saturated Buffer----
IA_Boone
IA_Grundy
IA_Hamilton1
...
----Controlled Drainage----
IA_Story2
...

**Comment by akrherz** [comment]
look good @loriabendroth ?

**Comment by loriabendroth** [comment]
yes @akrherz !
