### ISSUE TITLE
Ambiguous plotid specification of landscape position

### ISSUE THREAD

**Issue by akrherz** [isudatateam/datateam#32]
I attempted to fill in the empty plotid sheet specifications of drainage and landscape position.  The following sites have either multiple or no items checked in the Site Treatments, so auto-filling the plotid sheet is not possible.

## For drainage:
- All OK

## For Landscape
- [x] FREEMAN
- [x]  VICMS
- [x] STJOHNS

**Comment by loriabendroth** [comment]
@akrherz all three are toeslopes (LND3). I have updated master sheet with this. 
@giorgichi not sure toeslope is really correct geologically but for now, this is used for all sites to represent flat land that does not have erosion potential. We may want to include a description of this in data dictionary.

**Comment by akrherz** [comment]
@loriabendroth OK, thanks.  I have synced things up after this change.

**Comment by giorgichi** [comment]
@loriabendroth toeslope is a correct topographic name of a landscape position.
