### ISSUE TITLE
Data Citation to include

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#321]
@akrherz , 

- [x] replace "[author list TBD]" on the Research Data > Export Options page with this list: 
Chighladze, G., L.J. Abendroth, D. Herzmann, M. Helmers, L. Ahiablame, B. Allred, L. Bowling, L. Brown, N. Fausey, J. Frankenberger, D. Jaynes, X. Jia, J. Kjaersgaard, K. King, E. Kladivko, K. Nelson, L. Pease, B. Reinhart, J. Strock, and M. Youssef.
- [x] populate this text to Data Usage Agreement page (https://datateam.agron.iastate.edu/td/usage.phtml). Make first sentence larger font like how did Sus Corn Data Usage agreement. Notice, there is one hyperlink at the end for our email address. 

Transforming Drainage Research Data (USDA-NIFA Award No. 2015-68007-23193) Usage Agreement 

Please reference this data set in publications as:

Chighladze, G., L.J. Abendroth, D. Herzmann, M. Helmers, L. Ahiablame, B. Allred, L. Bowling, L. Brown, N. Fausey, J. Frankenberger, D. Jaynes, X. Jia, J. Kjaersgaard, K. King, E. Kladivko, K. Nelson, L. Pease, B. Reinhart, J. Strock, and M. Youssef. 2021. Transforming Drainage Research Data (USDA-NIFA Award No. 2015-68007-23193). National Agricultural Library - ARS - USDA. https://dx.doi.org/##################.

You are encouraged to contact the Transforming Drainage personnel listed above to ensure proper data interpretation and may also consider co-authoring with them. You shall have no claim of ownership to any intellectual property rights in any part of the data, content, functions, features, code, data exploration tools, logos or other intellectual property comprising this database.

The coauthors individually and the Transforming Drainage team collectively shall NOT be responsible or liable for the accuracy, reliability and completeness of any information included in the database nor the suitability of its application for a particular purpose. Data users are encouraged to notify the coauthors regarding data quality and other issues concerning the data, tools, and functionality of this website. Contact isudata@iastate.edu with any questions or concerns regarding usage and application of the data available at this site.

- [x] @giorgichi , 
populate USDA NAL page with the author list

**Comment by akrherz** [comment]
this all good now @loriabendroth ?

**Comment by loriabendroth** [comment]
yes @akrherz !
