### ISSUE TITLE
Remove management variables

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#33]
Daryl, tackle first 5!

- [x] Field Operations tab, remove variables from export:
plantbrand, updated, editedby, productrate, nitrogen, phosphate, phosphorus, potash, potassium, sulfur, zinc, magnesium, calcium, iron, growthstage, canopyheight, neutralindex, targetph, currentph
*only elemental versions of nutrients will be included to reduce misinterpretation

- [x] Pesticides tab, remove variables from export:
target1, target2, target3, target4, target5, target6, target7, target8, target9, target10, stage, justify, reference, updated, editedby

- [x] Management tab, remove variables from export:
updated, editedby, organicamendments, organicamendmentstext 

- [x] DWM tab, remove variables from export:
updated, editedby

- [x] Notes tab, remove variables from export:
updated, editedby

- [x] Lori determine value of remaining "Management" tab data, embed elsewhere?

- [x] merge Notes tab with SS important comments; want only one listing of open text like this for users. Need to narrow down SS high-value comments to those necessary for users first. Lori or @giorgichi do this.

**Comment by giorgichi** [comment]
@loriabendroth what do you refer to "SS important comments"?

**Comment by loriabendroth** [comment]
@giorgichi I'm referring to sheets in SS under folder Site Edits Needed > CSCAP Site Edit Reports and those with "HV" ("High Value") at end in particular. There are some comments in these that I'd like to bring in, to provide for proper interpretation. This will require screening and time, but I think calling out main ones are needed. For example, this one from Jeff: "J.Strock (12/22/2016): ...For field B, particularly point 35. This sampling site is located near a glacial feature known as a kame, which is an irregularly shaped hill composed of sand and gravel that accumulated during the retreat of the last glacier. The soil at point 35 is likely sandier than the other points in the field, namely 32 and 40, and thus exhibits different physical and chemical properties like lower carbon and nitrogen."

**Comment by giorgichi** [comment]
@loriabendroth do you want those comments to be copied to the Notes manually?

**Comment by loriabendroth** [comment]
reviewed all data under Management tab and populated into other field operations as appropriate and validated other entries. Data variables under Mngt tab not needed as individual entries.
