### ISSUE TITLE
Add weekly aggregation option

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#332]
@akrherz , currently three options exist (daily, month, year). Add weekly too starting on Sunday through Saturday. 
https://datateam.agron.iastate.edu/td/plot_nitrateload.phtml

**Comment by akrherz** [comment]
@loriabendroth, so long story short, ISO-week's start on Monday :/  How much of a deal-breaker is it for weeks to not start on Sunday?

**Comment by loriabendroth** [comment]
@akrherz , that sounds like a better approach. ha! Go with that.

**Comment by akrherz** [comment]
> that sounds like a better approach. ha! Go with that.

I am unsure about better, it was significantly easier though.
