### ISSUE TITLE
Swap photo on home page

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#337]
@akrherz , replace existing team photo with attached instead. This should fill the width of the page. It is a gif, is that best? I noticed the logo footer seemed a bit fuzzy which is prob because I uploaded a png. 

https://datateam.agron.iastate.edu/td/ 

![Homepage](https://user-images.githubusercontent.com/27225264/106550567-ff11c400-64d8-11eb-8482-8d8b4da4391f.gif)

**Comment by akrherz** [comment]
OK, this is done, but the picture is rather grainy...  In general...

if your image has lots of text, use PNG or GIF.  There's not really much difference between the two.

if your image does not have text, use JPEG for best results.

**Comment by loriabendroth** [comment]
@akrherz , okey dokey. I will probably send you different images in future but good for now!
