### ISSUE TITLE
include text on homepage

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#338]
@akrherz , one more job :) 

- [x] insert "(drainagedata.org)" after the title "Transforming Drainage Project Team Research Data". Don't hyperlink it though.

**Comment by loriabendroth** [comment]
@akrherz , move the drainagedata.org out of the paragraph and up to the main title. So this should be above the photo. Thanks

**Comment by akrherz** [comment]
@loriabendroth better now?

**Comment by loriabendroth** [comment]
@akrherz close! Make it: 
Transforming Drainage Project Team Research Data (drainagedata.org)

**Comment by akrherz** [comment]
@loriabendroth how about now?

**Comment by loriabendroth** [comment]
Good, done!
