### ISSUE TITLE
Add UTC FAQ note to the appropriate pages

### ISSUE THREAD

**Issue by akrherz** [isudatateam/datateam#34]
@loriabendroth suggests the following text be added to the export pages that export timestamps in UTC

>The timestamps are converted to Coordinated Universal Time (UTC) which
standardizes time across all research sites. It does not take into account
daylight saving time so that the difference between UTC and your local time
zone differs based on time of year. To equate UTC to our regional time
zones:
>
>- UTC is 5 hours ahead of CT in the summer and 6 hours ahead of CT in the winter 
>- UTC is 4 hours ahead of ET in the summer and 5 hours ahead of ET in the winter
>Note: Daylight saving time (DST) begins on the second Sunday of March and ends the first Sunday of >November.

**Comment by akrherz** [comment]
And in general, I need to clean up how these values are reported in the export files.  People likely need the data expressed in different ways based on the naiveness of their software systems to timestamp handling.

**Comment by loriabendroth** [comment]
@akrherz , anything left on this or close out?

**Comment by akrherz** [comment]
> anything left on this or close out?

Yeah, we can close and open new more-specific issues as the need arises.
