### ISSUE TITLE
Update all management data

### ISSUE THREAD

**Issue by giorgichi** [isudatateam/datateam#340]
Update field management data and do the final QA/QC
- [x] planting/harvesting
- [x] fertilizing/tillage
- [x] pesticide
- [x] residue
- [x] dwm
- [x] irrigation
- [x] notes

**Comment by giorgichi** [comment]
@loriabendroth @skbowd 

There are two new planting entries at **MUDS3_OLD** (see figure below). Are these planting operations (highlighted in the figure) actually different than the ones above them?  

I think those are the same operations entered twice, once without operation date and the second time with the planting dates specified. 

![image](https://user-images.githubusercontent.com/19730308/106822444-c55dcc00-6644-11eb-83fb-931c85de842e.png)

**Comment by loriabendroth** [comment]
@giorgichi , this was duplicate entries. Removed.

**Comment by loriabendroth** [comment]
Done with my final review of plant & harvest data. Remaining item I see is "filter" annotation.

**Comment by giorgichi** [comment]
Fixed inconsistencies in DWM and Irrigation data:
- added missing irrigation structure identifiers for **VANWERT** (based on crop info provided in the comments)
- added DWM info for **WILKIN1** and **WILKIN2** (removed entries about missing DWM in the notes for corresponding site-years)
- comments that specified date until the boards were set up to a certain depth was added as a new entry, and comments were edited respectively.  
- edited comments for DWM and irrigation that I missed previously (A lot of comments were redundant after adding a new column for `outletheight`, in particular for OH sites. All these comments were removed.  Several comments included references to locations/zones that are not part of the identifications used within the TD project. These comments were corrected to refer to the valid ids or locations, or removed if redundant or not essential.

**Comment by giorgichi** [comment]
**Residue management** 
- Added missing cashcrop in 2012 and 2013 at **CLAY_C**

**Comment by giorgichi** [comment]
@loriabendroth, I just noticed that at **ACRE** we have planting and other agronomic information reported for sub-plots that we do not have yeild data for. For example, we have field management info for **Field 41** in 2007, while there is no [yield data](https://docs.google.com/spreadsheets/d/12mZGdjH8x8KNK-HN9FN28avIrg5vQTyRXFzDu0soRdM/edit#gid=1079413389) reported for that plot in 2007. Should we keep these sub-plots with no yield data, or should I remove them from the ADC files?

**Comment by loriabendroth** [comment]
@giorgichi , I will look at these today

**Comment by giorgichi** [comment]
**Planting**

Wrang _crops_ were assigned to plots (303 and 304) at **MUDS1** in 2008, 2009, and 2010. Normally, corn and soybean are planted in alteration at this site. All plots, including 303 and 304, follow the pattern except these three years (see below). I think this error was introduced by us (most likely me) when populating plot ids in the backend management form.  

@loriabendroth, if you agree with the above statement, I will made corresponding changes in the backend sheet. 

| year_crop  | 302       | 303       | 304        | 308 |
| ---------  | --------- | --------- | ---------  | --- |
| 2002       | corn      | soybean   | corn       | soybean |
| 2003       | soybean   | corn      | soybean    | corn |   
| 2004       | corn      | soybean   | corn       | soybean |
| 2005       | soybean   | corn      | soybean    | corn |   
| 2006       | corn      | soybean   | corn       | soybean |
| 2007       | soybean   | corn      | soybean    | corn |   
| 2008       | corn      | **corn**      | **soybean**    | soybean |
| 2009       | soybean   | **soybean**   | **corn**       | corn |   
| 2010       | corn      | **corn**      | **soybean**    | soybean |
| 2011       | soybean   | corn      | soybean    | corn |   
| 2012       | corn      | soybean   | corn       | soybean |
| 2013       | soybean   | corn      | soybean    | corn |   
| 2014       | corn      | soybean   | corn       | soybean |
| 2015       | soybean   | corn      | soybean    | corn |   
| 2016       | corn      | soybean   | corn       | soybean |
| 2017       | soybean   | corn      | soybean    | corn |   
| 2018       | corn      | soybean   | corn       | soybean

**Comment by giorgichi** [comment]
@loriabendroth, I checked the [MUDS1 Crop Yield Data](https://docs.google.com/spreadsheets/d/1NQd9v37fxPYgTm4ZJgaaIjPEWP35xrI1t7Ql9tIbITI/edit#gid=924849632) and cashcrops at 303 and 304 do match with the management form. I think plot ids for each site-year were populated by me based on agraonomic data, and that is why they agree. I wonder if the data was incorrectly entered in the Google sheet by Kelley Nelson. Should we leave as it is, or should I contact Kelley?

**Comment by loriabendroth** [comment]
> @loriabendroth, I checked the [MUDS1 Crop Yield Data](https://docs.google.com/spreadsheets/d/1NQd9v37fxPYgTm4ZJgaaIjPEWP35xrI1t7Ql9tIbITI/edit#gid=924849632) and cashcrops at 303 and 304 do match with the management form. I think plot ids for each site-year were populated by me based on agraonomic data, and that is why they agree. I wonder if the data was incorrectly entered in the Google sheet by Kelley Nelson. Should we leave as it is, or should I contact Kelley?

Go ahead and swap the plotids so the rotation is correct. We will assume that they were mis-entered. Everything else looks fine so I dont think we need to reach out to Kelly. Good catch.

**Comment by giorgichi** [comment]
@loriabendroth thanks a lot. I will make the changes and update both agronomic and field management data.

**Comment by loriabendroth** [comment]
> @loriabendroth, I just noticed that at **ACRE** we have planting and other agronomic information reported for sub-plots that we do not have yeild data for. For example, we have field management info for **Field 41** in 2007, while there is no [yield data](https://docs.google.com/spreadsheets/d/12mZGdjH8x8KNK-HN9FN28avIrg5vQTyRXFzDu0soRdM/edit#gid=1079413389) reported for that plot in 2007. Should we keep these sub-plots with no yield data, or should I remove them from the ADC files?
> 
> p.s. most likely we already discussed this and I do not remember about it

Retain all subplots in management operations and when yield data is missing, enter as NA. It is likely that it wasn't available (such as with research plots) and they forgot to enter that. So if you can run a master subplot list across all site-years, then use that to identify missing yield plots and populate in as NA.

**Comment by giorgichi** [comment]
Corrected `cropyear` from 2009 to 2010 for fertilizer application on 2009-09-14 at **MUDS3_OLD**. Cereal rye was planted the day after fertilizer application and was harvested on 2010-04-23, which justifies this change.

**Comment by giorgichi** [comment]
Corrected `cashcrop` from soybean to corn for tillage on 2015-10-20 at **CLAY_R**.

**Comment by giorgichi** [comment]
Corrected `cashcrop` from corn to soybean for tillage in 2009 at CLAY_R.

**Comment by giorgichi** [comment]
Corrected `action` from keep to remove for tillage on 2018-10-05 at **FAIRM** since it belongs to crop year 2019 (beyond TD project database).

**Comment by giorgichi** [comment]
Corrected `cropyear` from 2017 to 2018 for tillage on 2018-05-07 at **WILKIN1**.

**Comment by giorgichi** [comment]
Corrected `timing` from n/a to unknown for insecticide application in 2011 at **AUGLA**.

**Comment by giorgichi** [comment]
Corrected `cropyear` from 2016 to 2017 for herbicide application on 2016-11-21 at **DPAC**.

**Comment by giorgichi** [comment]
@loriabendroth, at **HENRY** there are two entries for herbicide application with `crop` = other. The comments do not specify the other crop. Do you remember why we have this? Should I replace it with cashcrop for those crop years?

**Comment by loriabendroth** [comment]
@giorgichi , I have not reviewed herb/pest/insecticides for the past year because none of that will be published. So can ignore all of that.

**Comment by giorgichi** [comment]
Corrected `fertilizercrop` from soybean to corn for fertilizer application on 2011-11-08 at **DPAC**.

**Comment by giorgichi** [comment]
@loriabendroth, I split **_planting_** and **_fertilizing_** data into the following tables: 

- planting 
- harvesting 
- fertilizing (also includes lime application)
- tillage

Soil sampling was discarded as redundant.  Dates for soil nitrate sampling are available in `soil_properties_data.csv` along with actual measurements. 

There are some columns that are redundant and we can remove them if you agree:
- `operation` at _**planting**_ and _**harvesting**_. Before splitting this column distinguished planting and tillage operations, now there is only one operation specified in each of these two tables.
- `operation` at _**tillage**_. Now it only says tillage.

**Comment by giorgichi** [comment]
Extended all management, but _**notes**_, entries to plot level. Now planting, harvesting, tillage, fertilizer application, residue management, dwm, and irrigation data are available at higher spatial resolution! 😃 

_p.s. it took a lot of merging, checking, correcting, and verifying, but it worth the effort._

**Comment by giorgichi** [comment]
Need to update [_**data dictionary**_](https://docs.google.com/spreadsheets/d/1QU858NHlkZ4L23dmAZ7zwFsVdEmmu-vhbF5o1EFk8pw/edit#gid=715750743) to reflect changes in management tables!

**Comment by loriabendroth** [comment]
@giorgichi , awesome work on this and getting all to plot level. This is big! I am going through and doing final review. Noticed a couple things also, so working on that.

**Comment by loriabendroth** [comment]
> @loriabendroth, I split **_planting_** and **_fertilizing_** data into the following tables:
> 
> * planting
> * harvesting
> * fertilizing (also includes lime application)
> * tillage
> 
> Soil sampling was discarded as redundant. Dates for soil nitrate sampling are available in `soil_properties_data.csv` along with actual measurements.
> 
> There are some columns that are redundant and we can remove them if you agree:
> 
> * `operation` at _**planting**_ and _**harvesting**_. Before splitting this column distinguished planting and tillage operations, now there is only one operation specified in each of these two tables.
> * `operation` at _**tillage**_. Now it only says tillage.

yes, these are now redundant and can be removed.

**Comment by loriabendroth** [comment]
performed spell-check across all of management sheets.

**Comment by loriabendroth** [comment]
@giorgichi , is the comment in DWM for AUGLA 2008 needed? To me, it sounds like we are providing the ground surface elevation data in our db. Is that true? Also, DEFI_R has a number of statements like this, "The distance from the floor of the control structure to the base of the weep hole (5.1 cm orifice): 63.5 cm." - what is a user supposed to do with this? Does it inform something they should take into account?

**Comment by loriabendroth** [comment]
@giorgichi , for UBWC, in Residue Mngt tab, there is this statement "Did not collect, but site personnel note says "safe to assume none"." - what is this in reference to? What did they not collect?

**Comment by loriabendroth** [comment]
@giorgichi , I am done with all mngt data. When you finish addressing the items here, can you repost to ADC folder?

**Comment by giorgichi** [comment]
@loriabendroth, information about the weep hole depth is important for understanding the wetland management and corresponding outflow at **DEFI_R**.  Unlike usual control structures in CD fields, here water will flow through the hole first before reaching the rim of the board and subsequently overflowing. The location of the hole can be changed and is not fixed. I can send you a document showing it if you want.

Comment for **AUGLA** can be removed. I will do it programmatically.

**Comment by giorgichi** [comment]
> @giorgichi , for UBWC, in Residue Mngt tab, there is this statement "Did not collect, but site personnel note says "safe to assume none"." - what is this in reference to? What did they not collect?

@loriabendroth, I have no idea about this. We can remove if you also do not understand this comment.

**Comment by giorgichi** [comment]
All management files were updated.
