### ISSUE TITLE
Review WILKIN data

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#341]
@loriabendroth , 
Review provided planting, harvesting, tillage, fertilizer application, soil sampling, and residue management info for:
- [x] WILKIN1
- [x] WILKIN2
- [x] WILKIN3

**Comment by loriabendroth** [comment]
@each site, set three tillage operations to "remove" because they are in the fall of 2018, so would be for the 2019 crop which we don't have in db.

**Comment by loriabendroth** [comment]
Done. Edits made as needed to planting and fertilizer entries for standardization and error correction.

**Comment by loriabendroth** [comment]
@giorgichi , looks like he entered irrigation as none. So only DWM info is outstanding.

**Comment by giorgichi** [comment]
@loriabendroth Jeppe emailed me saying that that's all he can get and other missing data would take him longer to get to us.
