### ISSUE TITLE
Agronomic data, secondary trts

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#343]
@giorgichi , few changes to handling of secondary treatments in agronomic spreadsheet:

- [x] in data dictionary, change "trt" and "trt_value" to"trt_2" and "trt_value_2" to represent these as the secondary treatments because primary is the drainage treatment. See items #5 and 6. https://docs.google.com/spreadsheets/d/1QU858NHlkZ4L23dmAZ7zwFsVdEmmu-vhbF5o1EFk8pw/edit#gid=715750743 
- [x] for Redwood3, have plotids match the plotids in management backend, fertilizer tab.
- [x] for Redwood3, have location be NA. This will match how other locations are handled when they have secondary treatments. 
- [x] for Shelby, 2004 and 2005, I talked w Kelly and decided to only report one N rate, the 250. No other options exist to report so no secondary treatment. Therefore, in this sheet, these become NA.
- [x] For Shelby, 2006 and 2007 corn, same but this time it is 150 N rate. 
- [x] for Shelby, 2009, 2010 soybean, change fungicide treatment to NA. I had talked w Kelly and decided to only report one fungicide product so there is no other option.
- [x] The hybrid and cultivar names differ in the agronomic sheet compared to management backend. I can edit these in agronomic sheets but please verify you want me to do this in Google sheet. 
- [x] Vanwert, 2007, change "C-shank field cult" to "field cultivate"
- [x] for the sheet (and others) as a whole, sort by site, year, plotid, trt

**Comment by giorgichi** [comment]
> Vanwert, 2007, change "C-shank field cult" to "field cultivate"

This is changed programmatically.

**Comment by giorgichi** [comment]
@loriabendroth, everything sounds good except changes to "Redwood3" plot identifiers. Plot ID should match across agronomic, water, and other variables. The users of the drainage database should be able to link any drainage data with other data from a corresponding plot. If you check `meta_plot_characteristics.csv` table, you will see that plotids do not change by variable type, only locations do. 

At "Redwood3" there only 24 individual drainage plots where tile flow is measured. If we introduce 144 plots in agronomic data, it will get confusing. 

I suggest adding `location` to the field management to designate 6 different locations within each plot.

**Comment by giorgichi** [comment]
> The hybrid and cultivar names differ in the agronomic sheet compared to management backend. I can edit these in agronomic sheets but please verify you want me to do this in Google sheet.

I found only 3 mismatching cases, all of them at **MUDS1** in 2009. Looks like an error introduced by autocompleting functionality of spreadsheets when dragging a cell. Corrected all three of them as following:
- DeKalb DKC61-74 &#8594; DeKalb DKC61-73 
- DeKalb DKC61-75 &#8594; DeKalb DKC61-73
- DeKalb DKC61-76 &#8594; DeKalb DKC61-73

**Comment by giorgichi** [comment]
@loriabendroth, if you are fine with [my suggestion](https://github.com/isudatateam/datateam/issues/343#issuecomment-775526594) about "Redwood3" than we can close this issue. 

The agro data has been updated and uploaded to the ADC Google folder.

**Comment by loriabendroth** [comment]
> @loriabendroth, if you are fine with [my suggestion](https://github.com/isudatateam/datateam/issues/343#issuecomment-775526594) about "Redwood3" than we can close this issue.
> 
> The agro data has been updated and uploaded to the ADC Google folder.

yes, this is a good way to approach it.

**Comment by loriabendroth** [comment]
> > The hybrid and cultivar names differ in the agronomic sheet compared to management backend. I can edit these in agronomic sheets but please verify you want me to do this in Google sheet.
> 
> I found only 3 mismatching cases, all of them at **MUDS1** in 2009. Looks like an error introduced by autocompleting functionality of spreadsheets when dragging a cell. Corrected all three of them as following:
> 
> * DeKalb DKC61-74 → DeKalb DKC61-73
> * DeKalb DKC61-75 → DeKalb DKC61-73
> * DeKalb DKC61-76 → DeKalb DKC61-73

Also, these edits are needed to ADC version:
- [ ] add space after "LG"
- [ ] add "DeKalb" in front of "DKC"
- [ ] remove space between DKC and the number
- [ ] remove space between "Kruger 2114" and "RR..."
- [ ] capitalize "s" in Morsoy so it is "MorSoy"

**Comment by giorgichi** [comment]
> add space after "LG"

@loriabendroth, I cannot find any corn hybrid with no space after "LG". I checked both, agronomic and planting tables. Let me know in which table did you find it.

**Comment by loriabendroth** [comment]
> > add space after "LG"
> 
> @loriabendroth, I cannot find any corn hybrid with no space after "LG". I checked both, agronomic and planting tables. Let me know in which table did you find it.
> 
> Actually, I could not find any of the items listed above except "Kruger 2114", which is fixed now.

@giorgichi , I was working from the ADC version this past weekend but when I redownloaded it now, they don't exist. So no issues with hybrid names.
