### ISSUE TITLE
Progress report data

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#344]
@skbowd , 

- [x] few comments for you in DN01 Methods document.
- [ ] Add a column to each spreadsheet tab and title as "keep/remove" and then populate keep or remove for each row. Most will be keep, but some instances of remove such as this note from you on 2020.10.28:
"The administrative rows that are pink are the tab for practices for DN_1 that we decided to remove."
- [ ] couple comments under column I here that appear to be "remove"?? 

@lnowatzke , 

- [x] comments under Data Team Notes (column N) in blue with Jamie's name on several. Are you able to reconcile?  https://docs.google.com/spreadsheets/d/1LyHN7hcPiNWjD6Ljj9Me1oCDIfMmeugkkjSApaKwY-c/edit#gid=0
- [x] Decide whether a new classification should be added for social media or leave as is in column N. 
- [x] under column J, this is based on the 25 mile centroid approach (yes/no) but we have TBD for locations "not reported". Should we assume yes? https://docs.google.com/spreadsheets/d/1LyHN7hcPiNWjD6Ljj9Me1oCDIfMmeugkkjSApaKwY-c/edit#gid=607235473

@skbowd and @lnowatzke , have we/you decided on the aggregation variables to represent the admin data from this raw data?

**Comment by skbowd** [comment]
@loriabendroth 

 Where did you see the note I had made that you listed in the second bullet...2020.10.28: "The administrative rows that are pink are the tab for practices for DN_1 that we decided to remove."

Under which tab are you referring to in our comment above in 3rd bullet "couple comments under column I here that appear to be "remove"??"

**Comment by lnowatzke** [comment]
Re: Social Media entries, I'm comfortable with leaving "social media" in the Data Team Notes column. No action needed, unless anyone disagrees.

**Comment by lnowatzke** [comment]
@loriabendroth re: events with location not reported, assume Y for column J (they are all classified as this currently, so no action needed). All of these were reported by the project coordinators (i.e. from DN_01 project reports), so they are within their watershed or pertain directly to the project.

**Comment by loriabendroth** [comment]
@skbowd @lnowatzke , I have made some updates to the DD for this data set such as discarding the coordinator and only keeping coordinator_coded and also removing the data team notes. I dont think these should be included for any data sets.
