### ISSUE TITLE
Add cost-share project data

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#345]
@lnowatzke , @skbowd , 

- [ ] In December, we discussed adding cost-share projects funded by USB to DN_18. Do you have that data Laurie or is it web-based that Steph can access? 
- [ ] integrate USB projects into DN_18 and standardize as needed.

**Comment by loriabendroth** [comment]
@lnowatzke , any idea on USB projects? Should we add this in to admin data that will go to Jiaming or forgot?

**Comment by lnowatzke** [comment]
@loriabendroth , remind me, what is USB?

**Comment by loriabendroth** [comment]
United Soybean Board with Chris Hay

**Comment by lnowatzke** [comment]
@loriabendroth  @skbowd 
I'm sorry, I'm having a hard time recalling this discussion, and I'm not familiar with USB's projects. A long time ago, we got a little bit of conservation practice information from Iowa Soybean Association, but they would only share sparse details (county and year of installation), and it was hard to ascertain whether the practice also received public funding or not (in other words, we didn't know if each practice was a duplicated with one in the public database). Happy to explore this further if either of you have any other information, though!

**Comment by loriabendroth** [comment]
@lnowatzke , that's right, I said USB but meant ISA. Let's skip based on your reasoning above.
