### ISSUE TITLE
Tile terminology

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#347]
@giorgichi , in past team discussions, I was thinking we had decided to put a precursor to "tile" to be more explanatory. Do you remember this being discussed? Was it to be "drainage tile"? If yes, then dictionary needs to be updated under "Brief Description" column. Variable names don't need to be changed.

**Comment by giorgichi** [comment]
@loriabendroth, it rings a bell. As I recall it was "tile" vs "pipe". Not sure if there was any consensus about it.

**Comment by giorgichi** [comment]
@loriabendroth, I just checked the yield manuscript, where "drain" is used instead of "tile".

**Comment by loriabendroth** [comment]
> @loriabendroth, I just checked the yield manuscript, where "drain" is used instead of "tile". If we have to change I would go with drain.

@giorgichi , yes, please correct data dictionary to say "drain" rather than "tile". The team decided this was more accurate terminology and especially for the data, it is important we are clear and consistent with other team work.

**Comment by giorgichi** [comment]
**tile** has been replaced with **drain** in column headings of all files:
- site charactersitics
- plot characteristics
- drain flow and N loads (used to be tile flow and N loads)

I also edited variable names mentioned in the following files:
- methods
- data dictionary
