### ISSUE TITLE
Data Dictionary

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#348]
@giorgichi , few items in DD:

- [x] list acceptable values for all "double" data types
- [x] address 3 comments: 2 for gio and 1 for lori
- [x] reconcile red issues
- [x] update data sheets as needed

I have added text to some red issues.

**Comment by giorgichi** [comment]
link to [the Data Dictionary](https://docs.google.com/spreadsheets/d/1QU858NHlkZ4L23dmAZ7zwFsVdEmmu-vhbF5o1EFk8pw/edit#gid=715750743)

**Comment by loriabendroth** [comment]
I made some comments in DD but will make here broadly, need to state if dry weight. That is a critical item. I thought it was stated upfront when people were entering data into our spreadsheets. Weren't they all at 0% moisture except grain yield?

**Comment by loriabendroth** [comment]
@giorgichi , I resolves several comments and added text to DD. Remaining items are ones that you will need to look at.

**Comment by giorgichi** [comment]
> I made some comments in DD but will make here broadly, need to state if dry weight. That is a critical item. I thought it was stated upfront when people were entering data into our spreadsheets. Weren't they all at 0% moisture except grain yield?

You are right, it is assumed that certain agronomic variables are reported at 0% moisture. But I am not sure how strictly did PIs follow this guideline.

**Comment by loriabendroth** [comment]
regarding values for AV -> will likely remove given email correspondence between Gio and Lori on 2021.03.02.
