### ISSUE TITLE
Add research site table

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#35]
- [x] @akrherz Add table to Research Sites tab, under the map. See attached for table content.
[research site table.docx](https://github.com/isudatateam/datateam/files/1160524/research.site.table.docx)

- [x] @akrherz Use map and photo icon in table instead of hyperlink to signal that content exists. If "NONE" then leave blank. 
get icons from (unless you have others you prefer):
https://www.onlinewebfonts.com/icon/248017
http://simpleicon.com/wp-content/uploads/map-8.png 

- [x] @akrherz Include text above table:
Considerations:
* Site maps will often include plot numbers; these align with the plot identifiers listed with the data. 
* However, the maps may contain treatment codes that do not match the data; these are unique to that location and were changed afterwards to align with codes used across Sustainable Corn CAP sites. 
*Some experiments include treatments beyond those that were part of the Sustainable Corn CAP which can be seen in the plot map. 

- [x] Lori, delete out duplicate photos; rename all with team name and site name

- [x] Lori, proof maps; rename all maps with team name, site name, and year

- [x] @giorgichi, can you look at HICKS.B and HICKS.G photos; are they mixed up based on your memory?

**Comment by loriabendroth** [comment]
@akrherz nice! few edits needed:
- [ ] asterisk comment under considerations should be third bullet. formatting got messed up in original job posting
- [ ] narrow plot map and photograph column width. Widen research site official name column width. Want to get table more compact vertically so users dont scroll so much. See what you can do to have all farms only take up 1 or 2 lines. 
- [ ] delete N/A and NONE under photographs; have blank instead
- [ ] SERF has "/a>" in link for maps

**Comment by loriabendroth** [comment]
@giorgichi I believe you made Google maps for NAEW. Please edit 113 so spelling of "reserve" is correct. Upload new version to CSCAP internal folder and also to new /dl folder. All other NAEW have correct spelling. 
https://drive.google.com/drive/folders/0B_Wz65q1Dw-0YWlVVllNS3lRcWc

**Comment by loriabendroth** [comment]
@akrherz, make photo and map hyperlinks open in new browser tab. Notice also how the ISUAG.USB site has white background behind farm name; this should be grey.

**Comment by giorgichi** [comment]
@loriabendroth these NAEW maps was not made by me. They were provided by site personnel.
