### ISSUE TITLE
Ingest TD data 

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#350]
@akrherz , @giorgichi ,

I'd like to push the newest (almost final) data to the external website. This will help us proof it one final time before we publish to NAL ADC on Friday. We will notice any items or errors that exist likely by interacting with it in that way. Possible to have done by end of day Tuesday? 

The data is on the Drive under ADC folder: https://drive.google.com/drive/folders/1zblZuTiEUdZOq1_IHgO_gEtR018TidRq

**Comment by akrherz** [comment]
- [x] All csv files now processed
- [ ] reviewing various apps to see if schema changes require SQL statement updates.

**Comment by loriabendroth** [comment]
thanks @akrherz I will play with this today and let you and @giorgichi know if I see anything relevant for publishing at NAL ADC as well as for the interface.

**Comment by loriabendroth** [comment]
@akrherz , tried to download data but got this error: Sorry, script failure occurred :(

**Comment by akrherz** [comment]
> @akrherz , tried to download data but got this error: Sorry, script failure occurred :(

I am unsure if this was ever close to working.  I am on the case now.

**Comment by akrherz** [comment]
> @akrherz , tried to download data but got this error: Sorry, script failure occurred :(

Lets move this discussion to #364, closing this issue as complete.
