### ISSUE TITLE
Update Refereed Journal List for Sus Corn

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#353]
@akrherz , few updates to the Smartsheet report have been made (https://app.smartsheet.com/reports/ggRcvpJpqVWwVjJ444GQpPJgHHg4gVP7vcw8mhH1). Please reingest for the Ref Journal page here: https://datateam.agron.iastate.edu/cscap/dl/#tab_pubs

**Comment by akrherz** [comment]
with #304 , you had me update to use Google as the source of these?

**Comment by akrherz** [comment]
OK, I believe it is now synced.

**Comment by loriabendroth** [comment]
yep - looks good.
