### ISSUE TITLE
Update site data checklists 

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#354]
Update site checklists across all data types asap. Populate in data that is missing as well as data questions. 

Assignments based on data type:

@giorgichi 
- [x] tile flow
- [x] water quality
- [x] weather
- [x] greenhouse gas
- [x] soil (if possible)
- [x] any issues with sites in Google map?

@skbowd 
- [x] management operations

@loriabendroth 
- [x] maps
- [x] site information
- [x] agronomic
- [x] bring in hard-copy notes as well from past meetings

**Comment by loriabendroth** [comment]
all hard copy notes brought in from past meetings or outlying issues from data review meetings. need to go through emails still.

**Comment by skbowd** [comment]
Site edit sheets up-to-date for management needs as of 23 Feb 2021.

**Comment by giorgichi** [comment]
>  any issues with sites in Google map?

Everything looks good with NN Google map.

**Comment by giorgichi** [comment]
Finished reviewing soil data for all available years. Populated comments in the SS for all sites with figures demonstrating problematic measurements. 

Also, updated [NutriNet Data Collected sheet](https://docs.google.com/spreadsheets/d/12T-03ilNDtJN32NTbR3t2tHBZ-y7rYcgtmYN9XmSS_w/edit#gid=878657452). Originally, Fall Soil NH4 was not collected at **MUDS2**, but it was added in 2019. I put the following `X (2019,2020)` in the cells for corresponding variables.
