### ISSUE TITLE
Populate linear interpolation methods for water, ghg

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#356]
@giorgichi , in the protocols section, please upload a word document explaining the basis for how you handled interpolations for ghg and water data. Some items to include (based on team discussions previously):

- [x] were water and ghg handled in an identical fashion?
- [x] were seasons handled in an identical fashion? 
- [x] if peaks occurred in winter water sampling, were these retained or determined to not be realistic? 
- [x] was interpolation related to precipitation at all for water? In other words, if it rained during a period of missing data, was this approximated at all in a higher peak of flow or just draw line between prior and post event? 
- [x] for GHG samplings that were less frequent and the N application in the middle, did you assume an elevated rate of emissions following the application or just draw line directly between measurements?
- [x] any adjustments to GHG based on temperature, moisture, or soil N readings? 

https://drive.google.com/drive/folders/1g-Xy1izK-kvO8T5XY77H0kINqVeKZuwi

**Comment by giorgichi** [comment]
Missing GHG data were estimated using linear interpolation. If the gap between consecutive GHG measurements were > 30 days, no interpolation was made.

**Comment by giorgichi** [comment]
Soil temperature, moisture, and/or N concentration was not used to adjust GHG data.

**Comment by giorgichi** [comment]
Seasons were not considered during interpolation.

**Comment by giorgichi** [comment]
> if peaks occurred in winter water sampling, were these retained or determined to not be realistic?

Nothing like this has been done. All data were considered equally valid.

**Comment by giorgichi** [comment]
> was interpolation related to precipitation at all for water? In other words, if it rained during a period of missing data, was this approximated at all in a higher peak of flow or just draw line between prior and post event?

Precipitation was not considered originally. The data was added later for visualization purposes.

**Comment by giorgichi** [comment]
Interpolation of GHG data was limited to 30-day gaps, while not such a limit was used for water data.

**Comment by giorgichi** [comment]
One more detail, before interpolating GHG data I averaged `in_row `and `between_row` measurements at **KELLEY**.
