### ISSUE TITLE
DN01 or DN02

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#357]
@skbowd , the source column for some are "blank" - are they DN01? 
https://docs.google.com/spreadsheets/d/1LyHN7hcPiNWjD6Ljj9Me1oCDIfMmeugkkjSApaKwY-c/edit#gid=607235473

**Comment by skbowd** [comment]
Verified that these entries were indeed from DN_01.  I also added the following text to Methods_DN_01 to represent bringing DN_02 data set into DN_01.

_Outreach Data from DN_02_PartnerOutreach was brought into the DN_01 data set as well under “outreach and education”.  These were all categorized as “events” and a column was created for the source of the entry as “DN_01” or “DN_02”.  If there was a duplicate entry from DN_02 that was already in DN_01 from the progress reports, the source was left as “DN_01” and the entry was updated with any additional information from DN_02._
