### ISSUE TITLE
Merge SEPAC publications

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#361]
@skbowd , move SEPAC publication PDFs out of https://drive.google.com/drive/u/0/folders/1B1jv72oWNCQCbkr6CvEySxU5R_V04Hxz and collate with main Publications folder.

**Comment by skbowd** [comment]
@loriabendroth  For some reason, I cannot access that folder.  I requested access.

**Comment by loriabendroth** [comment]
@skbowd , I think this must have been delete things around in past weeks to bring all of SEPAC together. Earlier, there were files that had been copied over from NNK but still sitting separate from the other SEPAC files. So I think the task was related to reconciling those. Go through the SEPAC publications (PDF and spreadsheet) and if everything looks OK, you can close this out. I did notice there are duplicates of some PDFs here; https://drive.google.com/drive/folders/10TjeiBQ0jTwuB5RRqs7TfEj8JfE25SUk
