### ISSUE TITLE
Review SUBSURF and NWRF checklists

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#366]
@skbowd , for NN:

- [x] check daily digests (Google and Smartsheet) from 3/1 onward for SUBSURF. Sonia checks the rows as complete. If you are able to verify that the change has been done and is correct, please note as verified and keep checked. If not able to verify, uncheck box so we know to come back later. 
- [x] same for NWRF.  
- [x] also update master data collected sheet as needed if comments made about not collecting certain variables.

**Comment by skbowd** [comment]
@loriabendroth  I verified her updates for "management data" and "metadata"; should I uncheck "research data" entries that she checked if I cannot verify?

**Comment by loriabendroth** [comment]
@skbowd , can you please look again at NWRF Smartsheet. Not sure if you got through this? There are green checked items that don't have a verify statement... but I think you can. Such as the water K one, this can be verified once the Data Collected Master sheet is changed from X to NO.

**Comment by skbowd** [comment]
Sorry- I looked for updates 3/1 onward, so I missed the comments from February.  Should be up-to-date now.
