### ISSUE TITLE
Review NN data 

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#373]
@skbowd , please review all data that is entered and issues addressed in checklists for each site. This will take a chunk of time. Steps will involve reviewing comments in SS, verifying that the issue is fully addressed, replying in SS whether it is OK or need more work for each data type. To verify that the values look OK, please scan the range of values entered and whether the values are within the range (minimum to maximum) of values entered for 2018 and 2019 for that site. If all values are similar to previously entered values, please verify and check off. Please make comments here and assign items to me that you'd like me to look at. 

Review data entered for:

DOUGLAS
- [x] mngt
- [x] agro
- [x] soil
- [x] water
- [x] weather
- [x] any changes needed in master sheets based on data entered or not entered
- [x] address any email correspondence we receive from Apr 15 request

DUDLEY
- [x] mngt
- [x] agro
- [x] soil
- [x] water
- [x] weather
- [x] greenhouse gas
- [x] any changes needed in master sheets based on data entered or not entered
- [x] address any email correspondence we receive from Apr 15 request

KELLEY
- [x] mngt
- [x] agro
- [x] soil
- [x] water
- [x] weather
- [x] greenhouse gas
- [x] any changes needed in master sheets based on data entered or not entered
- [x] address any email correspondence we receive from Apr 15 request

MUDS2
- [x] mngt
- [x] agro
- [x] soil
- [x] water
- [x] weather
- [x] greenhouse gas
- [x] any changes needed in master sheets based on data entered or not entered
- [x] address any email correspondence we receive from Apr 15 request

NWRF
- [x] mngt
- [x] agro
- [x] soil
- [x] water
- [x] weather
- [x] any changes needed in master sheets based on data entered or not entered
- [x] address any email correspondence we receive from Apr 15 request

ONT_4R
- [x] mngt
- [x] agro
- [x] soil
- [x] greenhouse gas
- [x] any changes needed in master sheets based on data entered or not entered
- [x] address any email correspondence we receive from Apr 15 request

SUBSURF
- [x] mngt
- [x] agro
- [x] soil
- [x] water
- [x] weather
- [x] greenhouse gas
- [x] any changes needed in master sheets based on data entered or not entered
- [x] address any email correspondence we receive from Apr 15 request

TRO
- [x] mngt
- [x] agro
- [x] soil
- [x] water
- [x] weather
- [x] greenhouse gas
- [x] any changes needed in master sheets based on data entered or not entered
- [x] address any email correspondence we receive from Apr 15 request

WQFS
- [x] mngt
- [x] agro
- [x] soil
- [x] water
- [x] weather
- [x] greenhouse gas
- [x] any changes needed in master sheets based on data entered or not entered
- [x] address any email correspondence we receive from Apr 15 request

**Comment by skbowd** [comment]
ONT_4R  2019- CROP DATA- They did not send sample P and K samples for analysis from combine, so they copied subsample P & K data over to combine data.  Should we keep or delete?

**Comment by skbowd** [comment]
ONT_4R 2020- CROP DATA- CornGrainK_Subsample and CornGrainK_Combine are almost 3x the values of 2018 and 2019.

**Comment by skbowd** [comment]
KELLEY 2020- WATER DATA- 2020  What do we do when there are negative values for DrainageNO3Conc, DrainageNH3Conc, and DrainageReactivePConc ?  Site personnel said it means they are below detection limit.

**Comment by loriabendroth** [comment]
> ONT_4R 2019- CROP DATA- They did not send sample P and K samples for analysis from combine, so they copied subsample P & K data over to combine data. Should we keep or delete?

delete from the combine columns. No need to have it duplicated.

**Comment by skbowd** [comment]
DUDLEY-  Soil Data-  There are a lot of blanks and n/a'sfor the Fall calculated data (columns Q-T).  Since bulk densities and the corresponding data needed to calculate that column (FallSOC, FallSoilTN, etc.) are available, shouldn't these columns be populated?

**Comment by giorgichi** [comment]
> DUDLEY- Soil Data- There are a lot of blanks and n/a'sfor the Fall calculated data (columns Q-T). Since bulk densities and the corresponding data needed to calculate that column (FallSOC, FallSoilTN, etc.) are available, shouldn't these columns be populated?

@skbowd yes, those values should be calculated.

**Comment by giorgichi** [comment]
@skbowd  - in the smartsheet there is a comment about MUDS2 water P concentration. Please move it to the Notes in the management form.

> Savannah: Values have been verified, potentially due to lack of frequent drainage.  This could be due to the extreme drought that was experienced in 2018 (KN).

> SKB (2021.04.15) Data team- where should comments about 2018 and its potential impacts on P go?
GIO (2021-05-05) This comment can go into the site Notes in the Management Form.

**Comment by giorgichi** [comment]
@loriabendroth see my comments below:

## GHG

**SUBSURF** 
- **Ammonia emissions** are missing in 2018, but entered for 2019 and 2020. I am not sure if it was collected in 2018. Do you remember Sonia/Fabian mentioning anything about years when NH3  was collected?
- **SamplingBulkDensity** values in 2018 and 2019 are identical and correspond to soil bulk density measurements made in 2018-10-22 at 15cm depth (not at 5 cm depth as noted in the [Data Collected](https://docs.google.com/spreadsheets/d/12T-03ilNDtJN32NTbR3t2tHBZ-y7rYcgtmYN9XmSS_w/edit#gid=878657452) sheet). 2020 measurements might actually come from 5 cm depth samples. Could you check methodology for GHG measurement/calculations or confirm with Sonia/Fabian where do the bulk density data comes from?  
  

**DUDLEY** 
- **Soil Nitrate and Ammonium** measurement are missing in 2020. According to Laura's comment: "_LEC (4/15/21) these will not be analyzed until later this summer if at all. We can change that if these are critical._". Should we wait or assume the data do not come and close the request in SS?

**WQFS** 
- **GHG data** are missing for 2020. According to Eric's comment: "_Eric (4-15-21): Data from 2020 probably won't be compiled for at least several months._". Should we wait or assume the data do not come and close the request in SS?

**Comment by loriabendroth** [comment]
> KELLEY 2020- WATER DATA- 2020 What do we do when there are negative values for DrainageNO3Conc, DrainageNH3Conc, and DrainageReactivePConc ? Site personnel said it means they are below detection limit.

@skbowd , appears that the sheet has been updated as no negative values exist. @giorgichi , in 2020, BDL values are denoted with "<" but not in previous years. For example, NH3 BDL is <0.3 in 2020 but 0.3 in 2019. Which do you prefer for consistency sake?

**Comment by giorgichi** [comment]
@loriabendroth  I think we should use "<0.3" if the value is less than 0.3, but if it's exactly 0.3 we can leave it as is.

**Comment by loriabendroth** [comment]
Regarding: 

DUDLEY

Soil Nitrate and Ammonium measurement are missing in 2020. According to Laura's comment: "LEC (4/15/21) these will not be analyzed until later this summer if at all. We can change that if these are critical.". Should we wait or assume the data do not come and close the request in SS?

Let's keep it in SS so we don't forget as I doubt we publish the data before the fall. So even if not included in the manuscript, it will be in dataset.

**Comment by loriabendroth** [comment]
Regarding 

WQFS

GHG data are missing for 2020. According to Eric's comment: "Eric (4-15-21): Data from 2020 probably won't be compiled for at least several months.". Should we wait or assume the data do not come and close the request in SS?

Keep it in, same reasoning as DUDLEY

**Comment by loriabendroth** [comment]
> @loriabendroth see my comments below:
> 
> ## GHG
> **SUBSURF**
> 
> * **Ammonia emissions** are missing in 2018, but entered for 2019 and 2020. I am not sure if it was collected in 2018. Do you remember Sonia/Fabian mentioning anything about years when NH3  was collected?
> * **SamplingBulkDensity** values in 2018 and 2019 are identical and correspond to soil bulk density measurements made in 2018-10-22 at 15cm depth (not at 5 cm depth as noted in the [Data Collected](https://docs.google.com/spreadsheets/d/12T-03ilNDtJN32NTbR3t2tHBZ-y7rYcgtmYN9XmSS_w/edit#gid=878657452) sheet). 2020 measurements might actually come from 5 cm depth samples. Could you check methodology for GHG measurement/calculations or confirm with Sonia/Fabian where do the bulk density data comes from?
> 
> **DUDLEY**
> 
> * **Soil Nitrate and Ammonium** measurement are missing in 2020. According to Laura's comment: "_LEC (4/15/21) these will not be analyzed until later this summer if at all. We can change that if these are critical._". Should we wait or assume the data do not come and close the request in SS?
> 
> **WQFS**
> 
> * **GHG data** are missing for 2020. According to Eric's comment: "_Eric (4-15-21): Data from 2020 probably won't be compiled for at least several months._". Should we wait or assume the data do not come and close the request in SS?

@giorgichi , I have addressed as follows: 

1. Sonya posted a comment that 2018 were not collected. I updated Master and closed SS issue. 
2. I have posted to SS. I think soil data should be removed from GHG since not at time of sampling, which is intention of that column, 
3. Let's keep it in SS so we don't forget as I doubt we publish the data before the fall. So even if not included in the manuscript, it will be in dataset.
4. Keep it in, same reasoning as DUDLEY

**Comment by skbowd** [comment]
@loriabendroth 
ONT_4R-  Weather-  There is no weather spreadsheet on google drive and no comment on ss about getting it.  However, we have X's on the NutriNet Data Collected (Master).  Will the data team be retrieving this data?

**Comment by skbowd** [comment]
@giorgichi or @loriabendroth 
ONT_4R- GHG-  The NH3Emissions seem to have a very wide range (-2779 to 4069) .  Can one of you verify this data?

**Comment by loriabendroth** [comment]
> @loriabendroth
> ONT_4R- Weather- There is no weather spreadsheet on google drive and no comment on ss about getting it. However, we have X's on the NutriNet Data Collected (Master). Will the data team be retrieving this data?

@skbowd the ONT_4R and TRO sites use the same weather station. So we only have weather data under one of the sites.

**Comment by giorgichi** [comment]
> @giorgichi or @loriabendroth
> ONT_4R- GHG- The NH3Emissions seem to have a very wide range (-2779 to 4069) . Can one of you verify this data?

@skbowd  the range is OK. No particular reason to doubt the accuracy of the readings.

**Comment by giorgichi** [comment]
I am almost done with **SOIL** data. Already (~10 days ago) posted some comments in SS. I need to recheck the calculated variables one more time.

**Comment by skbowd** [comment]
SUBSURF- SOIL- There are a lot of blank cells in spreadsheet. I know some things are optional that I have listed below.  I didn't see these specifically listed on ss.  For required data- should I fill in with -9999 or should I post to ss the missing data?  For missing optional data- mark as n/a??

2018   FallSoc, FallSoilTN (and calc), pH, Ca, Mg
2019   FallSoc, FallSoilTN (and calc), Ca, Mg, bulk density, soil texture
2020- Soil Texture

**Comment by skbowd** [comment]
@loriabendroth 
TRO_ CROP DATA- Ike said "We are only using the corn grain yield_subsample (column R) for the TRO field site instead of crop yield (column U). This is to accommodate the experimental design."  Should I delete CropYield column?  It is reflected in data collected master that it was not collected.

**Comment by loriabendroth** [comment]
> @loriabendroth
> TRO_ CROP DATA- Ike said "We are only using the corn grain yield_subsample (column R) for the TRO field site instead of crop yield (column U). This is to accommodate the experimental design." Should I delete CropYield column? It is reflected in data collected master that it was not collected.

@skbowd yes delete the cropyield column from data sheet. Now that we are in the final year of the project, we know for sure whether certain data types will come. If they have never collected a column of data and it is all n/a's, please delete column and remove from the master data collected sheet.

**Comment by skbowd** [comment]
@loriabendroth 
TRO- CROP DATA- 2019  based on his note....."Eric: As much data as we currently have is now entered. These data are still being processed and we should be able to enter them once that is finished: CornLSNT_N, SoybeanR6N, StalkNitrate, and SoybeanGrainN_Combine. Also, it sounds like we didn't measure SilkingEarLeafN this year."

Should I add -9999 to all other data types he does not have listed here for 2019?  It looks like just as much is missing for 2018.  Should we assume the same data types listed above are still coming? Or mark all blank 2018 cells as -9999?

**Comment by loriabendroth** [comment]
> > DUDLEY- Soil Data- There are a lot of blanks and n/a'sfor the Fall calculated data (columns Q-T). Since bulk densities and the corresponding data needed to calculate that column (FallSOC, FallSoilTN, etc.) are available, shouldn't these columns be populated?
> 
> @skbowd yes, those values should be calculated.

@giorgichi @skbowd The bulk densities are missing for the plots without calculated values. I put a note in the checklist for site personnel to decide how they would like to handle.

**Comment by erwaring** [comment]
@skbowd I think NWRF is ready to for QC. That is: I am "site personnel" and I have nothing left to add or edit.

**Comment by loriabendroth** [comment]
@erwaring and @skbowd , only a few things remain in Smartsheet and wondering if you can each look at:

NWRF - @skbowd , one comment
KELLEY - @erwaring , two water comments I think that can be closed
MUDS2 - @erwaring , one comment I think can be closed
SUBSURF - @erwaring , bunch of water comments that I think can be closed
TRO - @erwaring , one comment about detection limit
WQFS - @erwaring , two comments I think can be closed

**Comment by skbowd** [comment]
NWRF comment closed.

**Comment by loriabendroth** [comment]
Done on our end, waiting for verification from site personnel on detection limit (NWRF) and value repetition (MUDS2).
