### ISSUE TITLE
NERF vs NWRF management data

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#378]
@skbowd , in the backend management sheet, NWRF is entered as site ID. But for NNK, only NERF is included and is a site we have not worked with before. Do you mean NERF for this data or is NWRF correct? If NWRF is correct, did we decide to include this site long-term data as well so we actually have 4 IA sites?

**Comment by skbowd** [comment]
@loriabendroth    I am not seeing NERF as a site on backend for NNK.  Or did you already change yellow highlighted text to NWRF?

**Comment by loriabendroth** [comment]
@skbowd , I highlighted NWRF in yellow because that is what it was entered as but we don't need NWRF data. We are only concerned about NERF. We want Nashua data for NERF whereas Sutherland is NWRF. For NNK, the Sutherland site is not part of the project. We can double-check with Matt on this though if he wants NWRF included. See list here: https://sites.google.com/iastate.edu/knowledgebase/database

**Comment by skbowd** [comment]
@loriabendroth    Got it!  I accidentally brought over NWRF since by brain was on that site from NN.  I will delete NWRF data from NNK backend.

**Comment by skbowd** [comment]
@loriabendroth   Just saw your email.  I will wait for Matt to confirm.

**Comment by skbowd** [comment]
NWRF added to NNK google drive per Helmer's request to add it to the project.  Historic management data has been moved to NNK, still need to move 2018-current management data.
