### ISSUE TITLE
ISBI Data Dictionary- Data Types

### ISSUE THREAD

**Issue by skbowd** [isudatateam/datateam#379]
Based on CSCAP and TD published data dictionaries and information found on the national ag library, I populated the data type column in the ISBI data dictionary.   I used the following data types...

character
date 
double (numbers with decimal places- is this the same as floating point numbers?)
integer (integers, including years)
boolean (yes/no, 0/1, keep/delete type variables)

I have some pink text in the column with question marks for one or both of you to check/verify.  Questions are pertaining to the proper use of "boolean", how to classify currency, and whether or not to use "floating point numbers" or "double".

**Comment by lnowatzke** [comment]
Thanks, Steph! This all sounds great to me. I'll check out the pink fields. I'll close this task once I do that.

I think you're correct that double = floating point, essentially, but I think there are some nuanced computational differences that go over my head. When I look at the pink fields, I'll enter "double" for any decimal values.

**Comment by loriabendroth** [comment]
@skbowd , the inclusion of those 5 data type categories is appropriate for our data. I reviewed two pink cells and agree with your text so switched to black. I dont see any others to address so will close out this. 
https://docs.google.com/spreadsheets/d/18HjkF_g-ETocFxlCDX3MW8UG7RXWSs-eYdeXf8UNCg8/edit#gid=496262310
