### ISSUE TITLE
Overall misc

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#385]
@akrherz , 
- [x] on home page, link the doi text inside parentheses to https://doi.org/10.15482/USDA.ADC/1521092
- [x] under agronomy tab, change "To Be Determind" header to "Crop Density, Area"
- [x] under agronomy tab, move Crop Yield box to the last box (so it is 5th and not 2nd)
- [x] have text above and below the map go across the full width of the page: https://datateam.agron.iastate.edu/td/dl/#tab_wdata
- [x] on data viz page, change link to Google Map to https://www.google.com/maps/d/u/1/edit?mid=1Ubw9c2nAILMhNFclLT0IxNI1yFw&ll=40.143474335880995%2C-90.09503297118817&z=5

**Comment by loriabendroth** [comment]
@akrherz , the last two items in the checklist are not done. Recheck that they were pushed forward.

**Comment by akrherz** [comment]
> Recheck that they were pushed forward.

Please try shift-reloading the page?  They appear updated on my end.

**Comment by loriabendroth** [comment]
OK, looking good for google map relink. I am still having text not go across the page for the map under the Data Tab. Can you check that one? There is an identical map under Data Viz which does have text that goes across. So maybe we are confusing ourselves on which map we are looking at?




This electronic message contains information generated by the USDA solely for the intended recipients. Any unauthorized interception of this message or the use or disclosure of the information it contains may violate the law and subject the violator to civil or criminal penalties. If you believe you have received this message in error, please notify the sender and delete the email immediately.

**Comment by akrherz** [comment]
> I am still having text not go across the page for the map under the Data Tab

OK, I believe I have found this now and fixed it.  Please reopen if not.
