### ISSUE TITLE
Water table data

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#390]
@akrherz and @giorgichi , during the meeting, it was discussed that people were not possibly getting the authoritative source of data... or they were confused where to find it. 

- [x] need to ensure that the data online matches that via NAL. @giorgichi , do you want @akrherz to download from NAL or use files you sent him? 
- [x] need to add water table to water data options for download. it is not there now. 
- [x] @akrherz , can you cross-check that all data in the dictionary is listed in the web portal?

**Comment by akrherz** [comment]
The NAL website offers the following CSVs

Filename | In Database | Available for Download
--- | --- | ---
mngt_tillage_data.csv   |  :heavy_check_mark:   | :heavy_minus_sign: 
mngt_notes_data.csv    | :heavy_check_mark:  | :heavy_check_mark:    
mngt_residue_data.csv     |  :heavy_check_mark:   |  :heavy_minus_sign: 
mngt_fertilizing_data.csv    |  :heavy_check_mark:   |  :heavy_minus_sign: 
mngt_harvesting_data.csv    |  :heavy_check_mark:   |  :heavy_minus_sign: 
mngt_planting_data.csv     | :heavy_check_mark:  | :heavy_check_mark:
mngt_irrigation_data.csv    |  :heavy_check_mark:   |  :heavy_minus_sign: 
mngt_dwm_data.csv     | :heavy_check_mark:  | :heavy_check_mark:
weather_data.csv          |  :heavy_check_mark:   |  :heavy_minus_sign: 
soil_properties_data.csv  | :heavy_check_mark:  | :heavy_check_mark:
soil_moisture_data.csv    | :heavy_check_mark:  | :heavy_check_mark:
agronomic_data_0.csv     | :heavy_check_mark:  | :heavy_check_mark:
irrigation_data.csv       |  :heavy_check_mark:   |  :heavy_minus_sign: 
water_stage_data.csv      |  :heavy_check_mark:   |  :heavy_minus_sign: 
water_table_data.csv   | :heavy_check_mark:  | :heavy_check_mark:
water_quality_data.csv   | :heavy_check_mark:  | :heavy_check_mark:
drain_flow_and_N_loads_data_0.csv    | :heavy_check_mark:  | :heavy_check_mark:
meta_methods.csv          |  :heavy_check_mark:   |  :heavy_minus_sign: 
meta_treatment_identifier.csv    |  :heavy_check_mark:   |  :heavy_minus_sign: 
meta_plot_characteristics.csv     | :heavy_check_mark:  | :heavy_check_mark:
meta_site_characteristics_0.csv   | :heavy_check_mark:  | :heavy_check_mark:
data_dictionary_5.csv    | :heavy_check_mark:  | :heavy_check_mark:

**Comment by loriabendroth** [comment]
@akrherz , can you bring the missing ones into the drainagedata.org interface? The checklist is very helpful - thanks

**Comment by loriabendroth** [comment]
@akrherz , for the missing data, put:
 https://datateam.agron.iastate.edu/td/dl/#tab_data 

- [ ] Methods as the fourth item in list under Management and Metadata tab. When clicked, have it export meta_methods info. 
- [ ] When site metadata and history are checked, have it export both meta_site_characteristics and meta_plot_characteristics.
- [ ] When plot identifiers is checked, have it export meta_treatment_identifier
- [ ] Add water stage to the WATER DATA tab subheading
- [ ] weather_data should be under Weather Tab, On Site (https://datateam.agron.iastate.edu/td/dl/#tab_wxdata). There are data there - do they match?
- [ ] All of the remaining mngt_##### file names should be automatically exported when Field Operations are selected under Management and Metadata. 

unrelated, but:
- [ ] Under water tab, change WATER DATA heading to WATER DEPTH

**Comment by loriabendroth** [comment]
This leaves one file -> irrigation data. 

To me, this seems like mngt metadata, but @giorgichi made it research data in how the file is named. To me, it seems like it should go with other irrigation metadata. Gio, how do you recommend we handle this in the interface?

**Comment by giorgichi** [comment]
Irrigation data can be treated as daily precipitation data.

**Comment by loriabendroth** [comment]
The onsite precip data is not part of the data download tab. It is under the weather tab. Are you saying that we should have weather data as export tab within the download function?

**Comment by akrherz** [comment]
For reference the `mngt_irrigation_data` table has 771 rows and the `irrigation_data` table has 752.  Both of which could easily fit in the data export interface.  I would prefer to do it there.

**Comment by loriabendroth** [comment]
@akrherz , yes, go ahead and include the irrigation data with the other farm management records. So this will be included as long as the checkbox is checked for Field Operations Data under Management and Metadata tab.

**Comment by akrherz** [comment]
@loriabendroth so I have done `mngt_irrigation_data`  with incoming change not yet deployed.  Does the other `irrigation_data` table need to be done as well as a separate tab?

**Comment by loriabendroth** [comment]
@akrherz , yes, best to keep as a separate tab because at USDA NAL, they are two different csvs.

**Comment by akrherz** [comment]
@loriabendroth done, I called this tab "Irrigation 2" without any guidance for something more appropriate.

**Comment by loriabendroth** [comment]
@akrherz , for the data that is "mngt_irrigation_data.csv" - have the tab named "Irrigation_Event-Based" and for the other, name it "Irrigation_Daily"

**Comment by akrherz** [comment]
@loriabendroth , this should be done, but I did not use underscores nor dashes as spaces are no technical issue for this.
