### ISSUE TITLE
Research Site Tab changes

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#401]
@akrherz , 

- [x] change table heading called "One Page Summary" to "Summary Document"
- [x] change link for "View the Google map..." to https://www.google.com/maps/d/u/0/edit?mid=1Ubw9c2nAILMhNFclLT0IxNI1yFw&ll=39.86558648764423%2C-90.09503297118817&z=5 
- [x] Remove hyperlinks to the following photograph folders because no images exist in the folders: IA_Story2, MO_Knox4, NC_Washington, OH_Auglaize1, OH_Auglaize2, OH_Crawford, OH_Defiance1, OH_Delaware, OH_Hardin1, OH_Hardin2, OH_Henry. @giorgichi , does this seem correct for photos?

**Comment by giorgichi** [comment]
@loriabendroth  It looks right to me.
