### ISSUE TITLE
Changes to Nitrate Load Visualization

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#402]
@akrherz , 

- [x] change first sentence to: "Nitrate load data are included for all applicable sites in this visualization and aggregation tool. Data are from the USDA-NIFA funded project: "Managing Water for Increased Resiliency of Drained Agricultural Landscapes" (Award No. 2015-68007-23193)."
- [x] Move Pro Tip text and Download Option text so that it is below the RUN button but above the graphic. 
- [x] Change "Pro Tip" to "Viewing Options:"
- [x] Edit graphic title so it is "Nitrate Load for ############". In other words, remove "Site:". 
- [x] Remove "SELECT" text at top, I dont think its critical
- [x] Have the checkbox checked by default and reword text to "Show results based on average treatment response" 
- [x] I think the data in the backend needs to be changed, use the data we refer to as "Nitrate N Load Filled 2 (recommended)" in the data export tab

Once you get these done, I will review once more and then you can copy-paste more or less for the other visualization tools.

**Comment by loriabendroth** [comment]
@akrherz , also change coloring in graphic from green and black to orange and blue. 

Make the free drainage blue and controlled drainage orange. The color of orange and blue should be similar to the TD logo.
https://transformingdrainage.org/

**Comment by akrherz** [comment]
> also change coloring in graphic from green and black to orange and blue.

I was not able to figure this one out.  For some plots, more than two lines would be plotted....

**Comment by loriabendroth** [comment]
@akrherz , looking good. The checkbox is selected which means the figure should plot it as treatment averages. But it is showing up as plot # and plot #. Also, if I uncheck the box and hit run, it checks the box again so no way for people to run it without it being checked.

**Comment by loriabendroth** [comment]
@akrherz , ok to leave color as is for now. I was trying to look up past code of where you would have changed it because I think I remember you doing that. But not critical now and can change later if want/able.

**Comment by loriabendroth** [comment]
Closing, will enter checkbox on plotting mechanism as new issue if still acting up today.
