### ISSUE TITLE
Check non-text in numeric, date columns

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#409]
@skbowd , review all data sheets of all sites that text comments are only in the comments section of spreadsheets. Dates and time should be numeric as well as measurements with the only exception of n/a or NA. If text exists, move it into Comments and change cell to NA. 

I have changed some already but good to have you double-check. For example, SUBSURF GHG had comments in TimeOfSample.

**Comment by loriabendroth** [comment]
Also, they merged three columns in parts so those need to be unmerged so it reads in cleanly to R. I already did this in SUBSURF GHG, but check other sheets for any merging and undo that.

**Comment by skbowd** [comment]
DOUGLAS
- [ ]  mngt
- [ ]  agro
- [ ]  soil
- [ ]  water
- [ ]  weather

DUDLEY
- [ ] mngt
- [ ]  agro
- [ ]  soil
- [ ]  water
- [ ]  weather
- [ ]  greenhouse gas

KELLEY
- [ ] mngt
- [ ]  agro
- [ ]  soil
- [ ]  water
- [ ]  weather
- [ ]  greenhouse gas

MUDS2
- [ ] mngt
- [ ]  agro
- [ ]  soil
- [ ]  water
- [ ]  weather
- [ ]  greenhouse gas

NWRF
- [ ] mngt
- [ ]  agro
- [ ]  soil
- [ ]  water
- [ ]  weather

 
ONT_4R
- [ ] mngt
- [ ]  agro
- [ ]  soil
- [ ]  greenhouse gas

SUBSURF
- [ ] mngt
- [ ]  agro
- [ ]  soil
- [ ]  water
- [ ]  weather
- [ ]  greenhouse gas

TRO
- [ ]  mngt
- [ ]  agro
- [ ]  soil
- [ ]  water
- [ ]  weather
- [ ]  greenhouse gas

WQFS
- [ ] mngt
- [ ]  agro
- [ ]  soil
- [ ]  water
- [ ]  weather
- [ ]  greenhouse gas

**Comment by loriabendroth** [comment]
thanks @skbowd
