### ISSUE TITLE
Hosting server decision

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#416]
@loriabendroth @akrherz , need to determine if ISBI data and R Shiny App can sit on Agron server. Or if ISU Repository can host or INRC. ISU Repository can host data but unsure about app.

**Comment by lnowatzke** [comment]
@akrherz @loriabendroth 
I reached out to INRC to see if they existing capacity for this for other projects. Waiting to hear back, but if they don't have options for this, it would so helpful to have it on the Agron server! I'll let you both know what I hear from INRC.

**Comment by loriabendroth** [comment]
@loriabendroth email agronomy people about this. Could pay Shiny but lack control.
