### ISSUE TITLE
Checkbox not engaging

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#418]
@akrherz , the checkbox "Show results based on average treatment response." is not working. It should be checked on default, which it is. But when it is checked, the figure should change from showing "Plot ##" to the treatment categories. Also when I uncheck it, and select Run, it reverts to checked.  

Can you figure out what issue is?

**Comment by akrherz** [comment]
OK, fix incoming.  This gets into ugliness with how HTML checkboxes work.  I inverted the verbiage to be

> Show results by plot identifier instead of treatment.

Will be deployed once continuous integration passes.

**Comment by loriabendroth** [comment]
looks good @akrherz
