### ISSUE TITLE
Edits to Tile Flow Vis page

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#424]
@akrherz ,

- [x] can you change page header from Tile Flow Data Plotting/Download to Tile Flow Data Plotting
- [x] change first sentence to: "Tile flow data are included for all applicable sites in this visualization and aggregation tool. Data are from the USDA-NIFA funded project: "Managing Water for Increased Resiliency of Drained Agricultural Landscapes" (Award No. 2015-68007-23193)."
- [x] can you change the options so they are organized the same way as Nitrate Load (do you want me to itemize changes needed?) https://datateam.agron.iastate.edu/td/plot_nitrateload.phtml 
- [x] Move Pro Tip text and Download Option text so that it is below the RUN button but above the graphic.
- [x] Change "Pro Tip" to "Viewing Options:" -> this is how Nitrate Load is also
- [x] Edit graphic title so it is "Tile Flow for ############". In other words, remove "Site:".
- [x] Have checkbox the same as Nitrate Load, i.e. unchecked by default with text "Show results by plot identifier instead of treatment." 
- [x] To verify, you are using the data we refer to as "Tile Flow Filled 2 (recommended)" in the data export tab, correct? 
- [x] Also, which precip source are using? Onsite or nearby weather station?

**Comment by akrherz** [comment]
> * To verify, you are using the data we refer to as "Tile Flow Filled 2 (recommended)" in the data export tab, correct?

I am using the `tile_flow_and_n_loads_data` database table, which is believe matches what the download interface offers

**Comment by akrherz** [comment]
> * Also, which precip source are using? Onsite or nearby weather station?

I am using the `weather_data` table, which I believe is the onsite data.

**Comment by loriabendroth** [comment]
> > * To verify, you are using the data we refer to as "Tile Flow Filled 2 (recommended)" in the data export tab, correct?
> 
> I am using the `tile_flow_and_n_loads_data` database table, which is believe matches what the download interface offers

@akrherz , there is data missing in the interface when it should exist. The file is correct I believe, are you using column I?

**Comment by loriabendroth** [comment]
@akrherz disregard, I am going across too many interfaces/tools. I may be incorrect. I'll open a new job if needed.
