### ISSUE TITLE
Final check on ISBI Data Dictionary

### ISSUE THREAD

**Issue by lnowatzke** [isudatateam/datateam#454]
@loriabendroth @skbowd @lnowatzke 
Final check on DD once all tasks are complete.

**Comment by loriabendroth** [comment]
Look through Publish/Discard column once more and validate that each variable is correct to publish

**Comment by lnowatzke** [comment]
@skbowd @loriabendroth I've looked through before maternity leave, and things look good to me so far. I'll leave the final final check to you two.

**Comment by loriabendroth** [comment]
I have looked through it, made edits, and posted one or two issues here on github to address. No other items I see needed on the data dictionary.

**Comment by lnowatzke** [comment]
I have also looked through. Data dictionary looks good to me.
