### ISSUE TITLE
TD Site Summaries

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#456]
@akrherz , we now have the site summaries ready to be posted to https://datateam.agron.iastate.edu/td/dl/#tab_sites. These will be a column added into the tables. You had it there before but then I asked you remove it temporarily. 

Are you able to host these somewhere or best to upload into Google folders like we do for photos and maps? Each site document is 2 pages.

**Comment by akrherz** [comment]
I like the Google Folders approach, since additional content could always easily be added.

**Comment by giorgichi** [comment]
@loriabendroth do you want me to add the to the same Google Drive location where photos and maps are (under my old institutional Gmail account)?

**Comment by loriabendroth** [comment]
I don't think we want any files left under your temp account for the external website access because that account will disappear eventually. Mine did.

Can you move all of it to under a generic account? I think you had a transformingdrainagedata gmail address or something? I can move the Site Summaries to the same location if you let me know login info.

You could house the folders outside of the TD main Drive folders in case Ben deletes at some point. That way we won't accidentally lose anything.




This electronic message contains information generated by the USDA solely for the intended recipients. Any unauthorized interception of this message or the use or disclosure of the information it contains may violate the law and subject the violator to civil or criminal penalties. If you believe you have received this message in error, please notify the sender and delete the email immediately.

**Comment by giorgichi** [comment]
@loriabendroth _transformingdrainagedata_ account hosted videos taken during the site visits and did not have free space to put more data. As a results I had to distribute TD files under several Google Accounts. 

@akrherz I think that will be a better solution. Let me know once you have shared drive ready.

**Comment by loriabendroth** [comment]
thanks @akrherz for creating this shared drive. @giorgichi can you move over all photos and maps and provide a list of hyperlinks that daryl needs for relinking from external site. I will get the site summaries up and provide links.

**Comment by giorgichi** [comment]
@akrherz what do you need from me to update link on the website?

**Comment by loriabendroth** [comment]
@akrherz , here are links for all available site summaries. I have changed folder permissions to anyone with the link so these won't change.

Saturated Buffers
IA_Boone | https://drive.google.com/file/d/1WzZZIDn1EBKuE5xTTxk-XseJaTUcOwtd/view
IA_Grundy | https://drive.google.com/file/d/1lnTvbG9QWyJguortyqMBkpsny6DxrN1w/view
IA_Hamilton1 | not available
IA_Hamilton2 | https://drive.google.com/file/d/1yZCYGUoTXfMsDATYpq3EAtNyd9_seYW0/view
IA_Hamilton3 | not available
IA_Story1 | https://drive.google.com/file/d/1FPu9phFUHcD_AFw-k08cLEh8ByI_afAv/view
IA_Tama | not available
MN_Wilkin3 | https://drive.google.com/file/d/12T14AShk37ARxODIg5UhyIxgGAWWv0Ba/view

Controlled Drainage
IA_Story2 | https://drive.google.com/file/d/1QJgoeexoKVmr0w0aPHheVIQxCBxFCAHH/view
IA_Washington | https://drive.google.com/file/d/1xFl8yP9lxjyZr7UBOlDkv2_svdcVrmPv/view
IN_Randolph | https://drive.google.com/file/d/1AHUsJrfT7F_wRoc0BWOSD2N9nasGKRu2/view
MN_Redwood1 | not available
MN_Wilkin1 | https://drive.google.com/file/d/1_fBXTYlr26GAowowdGMKUmQkGQg9xq7L/view
MN_Wilkin2 | https://drive.google.com/file/d/1NGlg42rq4mLpO--dhHh0pC0LpiPiAfWP/view
MO_Knox1 | https://drive.google.com/file/d/1ZZg00be8rUMcCzp2Dq4y71GxeVjSquSP/view
MO_Knox3 | https://drive.google.com/file/d/1x1Hx6Kd1ueURNlbhWy3_z3COqx2SMA8c/view
MO_Knox4 | https://drive.google.com/file/d/18aDhjuWci2VEkD5ptmV0VKqpzx6DBL1Y/view
NC_Washington | not available
OH_Auglaize1 | https://drive.google.com/file/d/1uY3HknYRlqWbobyP78eFaXXTxQY9JnI0/view
OH_Auglaize2 | https://drive.google.com/file/d/1B64WTpR--aGsKYK4AAxF6WHpb2UniUre/view
OH_Crawford | https://drive.google.com/file/d/15lHNarXKZQOeud6fEKM3Inge2hp_DtAQ/view
OH_Defiance1 | https://drive.google.com/file/d/1CKg-x0QEZ77_EWkNqx3qX3B9x77XdBlB/view
OH_Delaware | https://drive.google.com/file/d/1AkA80M7WdA8agTdsNGjrE1t8NgbFyxPe/view
OH_Hardin1 | https://drive.google.com/file/d/1UFpvZKmmb8LuCtx8cVZ6FLisEGmwPHpw/view
OH_Hardin2 | https://drive.google.com/file/d/1sl8xRIzSrrNSJuWT_nj90DK3CesXkJaa/view
OH_Henry | https://drive.google.com/file/d/1hGZ-BDMlFLfN7MlxT0Zj3VRYRRF7c0Vz/view
SD_Clay | https://drive.google.com/file/d/1mxzau1RZXPPMQLvF2hvaOhIiIipaBbgf/view

Drainage Water Recycling
MN_Clay2 | https://drive.google.com/file/d/1iRk_7aPL5KrD9G9nyzl1hL9CqyJm1n85/view
MN_Redwood3 | https://drive.google.com/file/d/1vnB1ioZ0UDCnEJT5Ix0q6CS9owOiPoYe/view
MO_Knox2 | https://drive.google.com/file/d/1awj5J2AaxmJdStK9J1Azz3shyJRUkoeu/view
MO_Shelby | https://drive.google.com/file/d/1IHY3G8QsqJrHYAOuveXjYz4VO3Gi9MmE/view
OH_Defiance2 | https://drive.google.com/file/d/1MYShEcEAUnhiigWsc7K4GOVwyyubC0ia/view
OH_Fulton | https://drive.google.com/file/d/1AkA80M7WdA8agTdsNGjrE1t8NgbFyxPe/view
OH_VanWert | https://drive.google.com/file/d/14FmKQnAK3Z79LdxwkGo075ZtJdyyvw0E/view

Other
IN_Tippecanoe | not available
MN_Clay1 | https://drive.google.com/file/d/1vMUaxS_RmIgsWrn1sIHX4hyItvqSeyK1/view
MN_Clay3 | https://drive.google.com/file/d/19JF4JC45NBtHpt2sey5W-mCO4N_S8Woj/view
MN_Redwood2 | not available
ND_Richland | https://drive.google.com/file/d/1a3ts8pHSJvwqBYs8cFPxw6MF58O_Hpba/view
