### ISSUE TITLE
Change to nitrate load plotting tool

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#458]
@akrherz , kinda forgot that we need to finish these tools. You previously worked on nitrate tool btw as part of https://github.com/isudatateam/datateam/issues/402

For nitrate tool:
- [x] For Download Options text, change "right clicking" to "clicking" 
- [x] MO_Knox2 shows the plot when it is by treatment but not by plot. Is there some linkage on the backend between these two that you need me to look at? 
- [x] IA_Hamilton2 is not plotting any data; check on this. Btw, I am just doing random checks so issues may exist in other sites too.

**Comment by akrherz** [comment]
@loriabendroth There was code in the backend that would prevent the plotting of any "Saturated Buffers" when running in the plotting by treatment.  I have removed that limitation and IA_Hamilton2 plots.
