### ISSUE TITLE
Remove Residue, Irrigation

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#46]
Remove this checkbox entirely from export interface under Management and Metadata, along with the variables.

**Comment by akrherz** [comment]
When you say "along with the variables", is this referencing the dictionaries?

**Comment by loriabendroth** [comment]
Just meant the column headings (listed below) that were within this Residue, Irrigation tab when exported, are no longer needed. i.e. that you dont need to merge them within another tab. These variables that should be removed are: 
irrigation
irrigationamount
irrigationmethod
limeyear
notill
residuebiomassmoisture
residuebiomassweight
residuehow
residueplantingpercentage
residueremoval
residuetype

**Comment by loriabendroth** [comment]
Variables are no longer included in Data Dictionary export.
