### ISSUE TITLE
Water Data Text

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#47]
- [x]  Reorg tabs to be L to R: Research Sites, Research Data, Weather Data, Publications

- [x] Create “Water Data, Tools” tab. Make this the third tab (after Research Data)

- [x] Remove this text at bottom of “Export Options” 

For additional data please visit following pages:
On-site weather (precipitation)
Drainage water flow (and NO3-N load)
Groundwater table depth
Soil moisture and temperature

- [x] Remove Water sub-tab within the Research data tab

- [x] On Water Data, Tools page, populate this text:

Data originating from research sites that have subsurface tile drainage installed are included here. They are not included under the Research Data tab because data are collected on a time series basis with the user selecting the aggregation preferred for export.  

Datasets include (will open up in a new browser tab): 

- Drainage Tile Flow (hyperlink to https://datateam.agron.iastate.edu/cscap/plot_tileflow.phtml) 
- Groundwater Table Depth (hyperlink to https://datateam.agron.iastate.edu/cscap/plot_watertable.phtml) 
- Soil Moisture and Temperature, Decagon sensors (hyperlink to https://datateam.agron.iastate.edu/cscap/plot_decagon.phtml) 
- On-site Precipitation (to be posted soon)

- [x] Include the attached graphic as a header of sorts. This just provides an example so people can see what they would access by clicking on the links. And to fill up the page. 
![example graphic_faded](https://user-images.githubusercontent.com/27225264/29833776-1f32a37e-8cb2-11e7-8cc8-85edd61ffd4d.png)

- [x] Remove BRADFORD.A from tile flow dropdown and Observation table at bottom of page. 

- [x] Create a new visualization tool identical to tile flow except it is for "Nitrate-N concentration in Tile Flow". @giorgichi will send you the data early next week to populate the tool. 

- [x] For soil moisture, need variables added to data dictionary and ensure alignment with exported file. In DD, we have SOIL5 now which is vague; need specification and additional codes added. Variables include: uniqueid, plotid, timestamp, vol. SWC, soil temp, and soil EC. 

- [x] Water data that are not included in above tools but previously identified as necessary for export are: WAT2 (tile nitrate conc), WAT8 (tile total p conc), WAT9 (tile reactive P conc), WAT20 (tile nitrate loss). I question whether WAT9 is needed and if instead we need tile P loss similar to WAT20. Need to add to existing tools or provide in Research Data interface.

**Comment by loriabendroth** [comment]
Fast work! Items 2, 4, 5 are not showing up. Can you check this?

**Comment by akrherz** [comment]
@loriabendroth Gio had a pull request with some of those implemented that I had not merged yet.  I have made an additional commit which does the rest of those items

**Comment by loriabendroth** [comment]
@akrherz good! notice that third item in original listing is showing up again. And no text on water tools page... but maybe that is still coming?

**Comment by akrherz** [comment]
@loriabendroth OK, fixed that.

**Comment by loriabendroth** [comment]
@akrherz make 1st open up in new browser tab. Others are fine.

**Comment by akrherz** [comment]
@loriabendroth fixed typo

**Comment by loriabendroth** [comment]
@akrherz two new items added to the original posting. Related to visualization tools.

**Comment by loriabendroth** [comment]
@akrherz remove the visualization image; I dont like it after all!

**Comment by giorgichi** [comment]
Tile NO3-N (WAT2) and Tile Reactive P (WAT9)concentrations were identified as the drainage water quality related data to be available for public. Tile Total P (WAT8) was not included since only one sites provided that data. Nutrient losses are not available for download due to scarcity of that data compared to the nutrient concentration. Furthermore, nutrient loss can be calculated using concentration and flow, both are available through the export tool.
