### ISSUE TITLE
DN_08 column

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#493]
@lnowatzke @skbowd , do you remember why Gio thought the following? I dont see an issue. 

@giorgichi made the following comment for DN08:
Gio 8.29.2021: I think ID_HUC12 is misleading here and should be removed from the table, leaving only ProjectID and ProjectName as geographic identifiers.
https://docs.google.com/spreadsheets/d/1wzhNIBYHhRRsWcwFmXzmv6kZhzDoKeiK0kXt8HeNUmY/edit#gid=0

**Comment by lnowatzke** [comment]
I don't see an issue either. There are multiple huc12s per project, and they each have a different urban value, so we would lose key information her if we removed that entire column. Not sure what he meant originally.
