### ISSUE TITLE
Fine-tune edits (second round)

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#53]
I will add to this list tomorrow also :) Most are not critical, so if time-consuming or disagree, then don't do!

**Interface -> Publications**

- [x] Under Publications tab, add this second sentence to header text. 
“For individuals without accessibility to certain journals, contact sustainablecorn@iastate.edu for requests to articles below that are subscription-only.”
- [x] make email address hyperlinked
- [x] remove "NA" from showing up for volume and page number. Example: see Haruna et al., 2017. Would it be easier if I used "n/a" for these in SS?
- [x] under Thesis and Dissertations tab, delete "CSCAP Theses and Dissertations" subheader text and replace with the following. Use that side vertical beige bar like what you have for R.J. 
Many biophysical and social science graduate students were supported by and contributed to the scientific discoveries and publications of the Sustainable Corn CAP team. Their theses and dissertations are provided here via links to their major University library.

**Interface -> Export Options**

- [x] have “do NOT agree” as default on agreement
- [x] make so have to enter email twice, with checks if they don’t match
- [x] Don’t enable "Proceed with Download" button if an email is not entered 
- [x] Need to have the data agreement either posted on the water tools pages or link to it on the /dl. What is feasibility of having an AGREE button pop-up if someone selects the "Download as CSV file" option? 
- [x] Switch out data agreement on Export subtab and Data Agreement drop down to:
By using these data, you acknowledge and agree to cite the data in all publications or presentations using the following format: 

Abendroth, Lori J., Daryl E. Herzmann, Giorgi Chighladze, Eileen J. Kladivko, Matthew J. Helmers, Laura Bowling, Michael Castellano, Richard M. Cruse, Warren A. Dick, Norman R. Fausey, Jane Frankenberger, Aaron J. Gassmann, Alexandra Kravchenko, Rattan Lal, Joseph G. Lauer, Daren S. Mueller, Emerson D. Nafziger, Nsalambi Nkongolo, Matthew O'Neal, John E. Sawyer, Peter Scharf, Jeffrey S. Strock, and Maria B. Villamil. 2017. Sustainable Corn CAP (USDA-NIFA Funded). National Agricultural Library - ARS - USDA. https://dx.doi.org/xxxxxxx 

You are encouraged to contact the Sustainable Corn CAP personnel listed above to ensure proper data interpretation and may also consider co-authoring with them. You shall have no claim of ownership to any intellectual property rights in any part of the data, content, functions, features, code, data exploration tools, logos or other intellectual property comprising this database. 

The coauthors individually and the Sustainable Corn CAP collectively shall NOT be responsible or liable for the accuracy, reliability and completeness of any information included in the database as well as for the suitability of its application for any particular purpose. Data users are encouraged to notify the coauthors regarding data quality and other issues concerning the data, tools, and functionality of this website. Contact sustainablecorn@iastate.edu with any questions or concerns regarding usage and application of the data available at this site.

**Interface -> Navigation**

- [x] Remove headings under the horizontal navigation bar such as "Available Research Sites", "Treatments", ...,  "Available Export Options"
- [x] In dropdown, change "Mainpage" to "Homepage" and "Data Download" to "Research Data"
- [x] on homepage, put a little arrow at bottom right, that directs to /dl
- [x] Make Sustainable Corn link under Daily Erosion Project and IEM come to /cscap and not old website
- [x] I don’t think disclaimer or apps tabs up top are needed for cscap; remove
- [x] When going to /dl, it starts on the second tab (Research Data); make it so it starts on first tab

**Data**

- [x] add date to column heading of soil nitrate for couple sites (to match other sites):
HICKS.P; in 2013 tab it should be 11-01-2013 and in 2014 it should be 10-29-2014. This will match what we have in the management sheet/field operations. 
https://docs.google.com/spreadsheets/d/14MM9e-K2E5EG0c7cOkp-yG8664T8Aym6PvnaRzXCnq4/edit#gid=3
SERF in 2012, it should be 10-09-2012. This will match what we have in field ops. 
https://docs.google.com/spreadsheets/d/1P_tOV5f0Vy8HURv1HQnA7yce_OTtacM7v6XM04Yw2nw/edit#gid=2
- [x] lowercase “Crop” in column heading (such as 2011 Crop), merge with the year also to match other codes (which tend to not have spaces between words). Update data dictionary. 
- [x] move these crop columns to the right of landscape column
- [x] for weather data, change exported file name from "changeme" to uniqueid of site
- [x] remove NAEW.WS115, 123, 127, Y102 and Y103 from site dropdown for weather
- [x] for weather data, the .txt file exports different column names than what we have here (CLIM#). Need to change one or the other so they match, along with DD. https://docs.google.com/spreadsheets/d/1PKK-vWuOryYFOSYSgt4TosrjIDX_F-opHOvrEo5q-i4/edit?hl=en_US&hl=en_US#gid=0 
- [x] ~~possible to add unique site ID to weather files as first column in addition to weather station names? I know these are coming from IEM so if difficult, no big deal.~~ 

**Map**

- [x] remove ONFARM sites under Monitoring Locations
- [x] remove VICMS under Site Area

**Exported file**

- [x] Make data dictionary tab first in exported file – before Plot Identifiers
- [x] have uniqueid come before official farm name in Site Metadata tab
- [x] sort rows in field ops, pest, dwm, notes by uniqueid and then by date
- [x] remove “herb” column from plotid tab
- [x] move “rep” column to the left of “plot id” in plot ID tab
- [x] possible to wrap text at all in cells and/or force a certain width to columns? How is it that the column widths are wider in dictionary tab than other tabs? 
- [x] ~~Possible to set font to Arial 10 pt. in export?~~
- [x] remove "Official Farm Name" from site metadata tab 
- [x] sort Data Dictionary by data category > spreadsheet_tab > element_or_value_display_name
- [x] sort soil series columns L to R under Plot Identifiers tab to:
soilseriesname1 | soiltextureseries1 | soilseriesdescription1 | soilseriesname2 | soiltextureseries2 | soilseriesdescription2 | soilseriesname3 | soiltextureseries3 | soilseriesdescription3 | soilseriesname4 | soiltextureseries4 | soilseriesdescription4
- [x] in plotid tab, far right columns, can we rename to agro_data, soil_data, ghg_data, ipmcscap_data, ipmusb_data? And then change DD to match. 
- [x] we have blank cells in data columns not collected at certain sites. this makes sense to us but will confuse users likely. Can we have empty cells populate with the missing variable selected by user at end so that no blank cells exist?

**Admin**

- [x] Possible to have list of individuals (emails) who have downloaded data on this page? 

**Misc**

- [x] Add this on homepage:
"... funding from 2011-2016 with Dr. Lois Wright Morton as project director and Lori Abendroth as project manager."
- [x] add to homepage, under isu library sentence: "The Sustainable Corn CAP data is also described and available at the USDA National Agricultural Library Ag Data Commons (url pending)."
- [x] for water plotting tools, remove "CSCAP" at the front end of each subheading. Also, add a small line up above so header is not right up against grey header. 
- [x] add this onto Water Data, Tools page as the third and fourth sentences. 
Please note that additional data such as management operations, plot identifiers, data dictionary, and site history for these drainage research sites are included under the Research Data tab. It is strongly recommended to download these supporting data to properly interpret and synthesize water data contained here.  
- [x] On GHG tab, subset numbers for gases and superscript 2 following "R"
- [x] change email body to following (note I changed weblinks at top):

Sustainable Corn CAP - Research and Management Data
Requested: 13 September 2017 17:54:14 UTC
Website: https://datateam.agron.iastate.edu/cscap/
Contact: sustainablecorn@iastate.edu

Please click here to download your spreadsheet file.

    https://datateam.agron.iastate.edu/tmp/cscap_xxxxxxxxxxxxxx (link will remain active for 30 days)

By using these data, you acknowledge and agree to cite the data in all publications or presentations using the following format: 

Abendroth, Lori J., Daryl E. Herzmann, Giorgi Chighladze, Eileen J. Kladivko, Matthew J. Helmers,  Laura Bowling, Michael Castellano, Richard M. Cruse, Warren A. Dick, Norman R. Fausey, Jane Frankenberger, Aaron J. Gassmann, Alexandra Kravchenko, Rattan Lal, Joseph G. Lauer, Daren S. Mueller, Emerson D. Nafziger, Nsalambi Nkongolo, Matthew O'Neal, John E. Sawyer, Peter Scharf, Jeffrey S. Strock, and Maria B. Villamil. 2017. Sustainable Corn CAP (USDA-NIFA Funded). National Agricultural Library - ARS - USDA. https://dx.doi.org/xxxxxxx 

You are encouraged to contact the Sustainable Corn CAP personnel listed above to ensure proper data interpretation and may also consider co-authoring with them. You shall have no claim of ownership to any intellectual property rights in any part of the data, content, functions, features, code, data exploration tools, logos or other intellectual property comprising this database. 

The coauthors individually and the Sustainable Corn CAP collectively shall NOT be responsible or liable for the accuracy, reliability and completeness of any information included in the database as well as for the suitability of its application for any particular purpose. Data users are encouraged to notify the coauthors regarding data quality and other issues concerning the data, tools, and functionality of this website. Contact sustainablecorn@iastate.edu with any questions or concerns regarding usage and application of the data available at this site.

- [x] populate text to Contact Us (change your info as you’d like):
Questions regarding the research database such as experimental designs, farm management operations, research and metadata collected, and protocols should be directed to sustainablecorn@iastate.edu. The team members listed below will answer your questions. We will determine if contacting the individual research site faculty and staff members are necessary.  

Lori Abendroth 
Sustainable Corn Project Manager, PI
Agronomist
labend@iastate.edu

Daryl Herzmann
Systems Administrator and Analyst
Agricultural Meteorologist
akrherz@iastsate.edu

Giorgi Chighladze
Data Manager and Analyst
Agricultural Engineer
gio@iastate.edu

- [x] Upload TD logo to bottom of TD homepage 
![data_web_logos](https://user-images.githubusercontent.com/27225264/30398611-aee012e6-9896-11e7-9181-b62e19a66c1e.png)
- [x] For the TD page, possible to have this as the hompage text which is visible to all but then have the subpages not be visible to people? 

Transforming Drainage Project Team Research Data

< picture > https://fe6156f6-a-62cb3a1a-s-sites.googlegroups.com/site/transformingdrainage/home/Team%20Pic.jpg?attachauth=ANoY7crQvsGtwxX7jUUG4ldoUa10exJ-nQr2aALQ_HnyAFiiwzl_rxzk73pxJoHK2RWSenPc-hjSDLK9tcv_uL9-8pw7TCZ0fs7D0B71gfE9jwUeJuXAZWcc-nC4n9faY9kndByuPWbCBEulkYvDdfs-Ps7N9bvk06cdLMM8wP5gAFnq2t2pB2tMpfJDxiVqWv68QM4ENQm9ucR18HfyZpvxF6nuP-4xlZAurQMNi1rEhWG1LYnC23U%3D&attredirects=0 

This website will contain research data measured across a set of experiments carried out by the Managing Water for Increased Resiliency of Drained Agricultural Landscapes or Transforming Drainage (transformingdrainage.org). 

The Transforming Drainage team is currently funded by the United States Department of Agriculture, National Institute of Food and Agriculture (USDA-NIFA, Award No. 2015-68007-23193). 

The team is a multi-state research, extension, and education effort aimed at addressing important drainage management questions through the assessment and development of new water storage practices and technologies. Drainage is an essential component of the landscape to provide suitable growing conditions for the crops that feed and support both local and global communities. However, this infrastructure also creates a pathway for water and nutrient losses to occur. Increasing water storage on the landscape can provide greater water security for growing crops while supporting water quality efforts, which are of growing interest to landowners and the public. The vision for this project is that the process of designing and implementing agricultural drainage will be transformed so that storing water in the landscape will be considered for every drainage system as a foundation for resilient and productive agricultural systems.

Research data have been and are collected across 36 experimental sites focused on control drainage, water recycling, or saturated buffers, beginning in 1996. At the end of the project award period, the team will make all water quality and quantity data available here. 

For questions on the project, please contact the project director, Jane Frankenberger (frankenb@purdue.edu), and the project manager, Ben Reinhart (breinhar@purdue.edu). For questions on the research database, please contact Lori Abendroth and Giorgi Chighladze at isudatateam@iastate.edu.

**Comment by akrherz** [comment]
Regarding the column widths: I have manual adjustments within the export script to resize certain columns.  I am unsure of a more general means by which this can be done.  If there are certain columns you really want resized, just let me know.  Or maybe some solution will come to mind

Regarding font size, I could not find a simple means for doing this either :(

**Comment by loriabendroth** [comment]
@akrherz correction needed to this: "sort rows in field ops, pest, dwm, notes" - sort by uniqueid, crop year, then date. 
Regarding the column width, is it possible to set all to the width of the column heading at minimum?

**Comment by akrherz** [comment]
@loriabendroth I am not finding such an option to set the default column width :(

**Comment by akrherz** [comment]
@loriabendroth regarding
>remove "NA" from showing up for volume and page number. Example: see Haruna et al., 2017. Would it be easier if I used "n/a" for these in SS?

this is based on what is in the smartsheet.  Just update it there to how you want it to appear and I'll resync the content to the ISU database.

**Comment by loriabendroth** [comment]
I'd like to keep it as NA in SS if you can kick it out on your end.

**Comment by akrherz** [comment]
@loriabendroth regarding
>What is feasibility of having an AGREE button pop-up if someone selects the "Download as CSV file" option?

I'm not too keen on that as one would have to somehow keep track of that with each successive data request.  In the future version, I have simply added a link to the data agreement.

**Comment by akrherz** [comment]
@loriabendroth regarding
> I don’t think disclaimer or apps tabs up top are needed for cscap; remove

What is this referencing?

**Comment by loriabendroth** [comment]
The three red tabs up at the right. You have text for them when show up for IEM. But I don't think we need them for us.

**Comment by giorgichi** [comment]
@loriabendroth, I cannot make any changes to the map. I can access the original **CSCAP MAP** that I have been developing along the way, but I cannot get to the **Sustainable Corn Field Research Sites**. If you give me access to that map I can make the changes, otherwise it is on you.

**Comment by loriabendroth** [comment]
You should be able to access bc it is in shared folder but I know it is goofy too from when I worked with it earlier. So I can handle later today.

**Comment by giorgichi** [comment]
@loriabendroth, do you reply to my comment about maps? Can you check the sharing option for that map? Also I cannot find (or see) it in the shared folder, maybe I am looking in wrong place?

p.s. what "bc" stands for?

**Comment by giorgichi** [comment]
@loriabendroth, where do you want to add "Contact Us" text?

**Comment by loriabendroth** [comment]
@giorgichi The Contact Us page was removed earlier as part of this job ( I don’t think disclaimer or apps tabs up top are needed for cscap; remove); it should not have been. So it needs to come back and then the text can go there. Go to IEM page to see how this looks: https://mesonet.agron.iastate.edu/info/contacts.php

**Comment by loriabendroth** [comment]
@akrherz can you move the Research Data download "button" on homepage above the logo and below the hyperlink? Also, unbold my name and Lois's; not necessary.

**Comment by loriabendroth** [comment]
@akrherz the header is gone from publications page that stated about open access, etc. Bring this back in.

**Comment by loriabendroth** [comment]
@akrherz having the data agreement in dropdown is good. I would like it to come back into the Export tab also so people are forced to see it there and with do not agree dropdown. They are more likely to read it there than exit.

**Comment by loriabendroth** [comment]
@akrherz for this "Make Sustainable Corn link under Daily Erosion Project and IEM come to /cscap and not old website" it is still routing to sustainablecorn.org. Are you doing this intentionally since /cscap is not live yet?

**Comment by akrherz** [comment]
@loriabendroth regarding the sustainable corn link found on the IEM and Daily Erosion websites, that is correct.  The /cscap/ is not publicly available yet.

**Comment by loriabendroth** [comment]
@akrherz for TD page, have transformingdrainage.org open up in new browser

**Comment by loriabendroth** [comment]
@akrherz @giorgichi made some additions here to list. this is all I will post to this job.

**Comment by giorgichi** [comment]
There was no **soiltaxonomicclass** listed in this comment. It should be added back to the export data.
> sort soil series columns L to R under Plot Identifiers tab to:
soilseriesname1 | soiltextureseries1 | soilseriesdescription1 | soilseriesname2 | soiltextureseries2 | soilseriesdescription2 | soilseriesname3 | soiltextureseries3 | soilseriesdescription3 | soilseriesname4 | soiltextureseries4 | soilseriesdescription4

**Comment by loriabendroth** [comment]
@giorgichi @akrherz this sentence was missed for data agreements, make it the first sentence before citation listing. Also the "s" is missing on data agreement dropdown for suscorn email address. 
"By using these data, you acknowledge and agree to cite the data in all publications or presentations using the following format:"

**Comment by giorgichi** [comment]
@loriabendroth 
>for weather data, change exported file name from "changeme" to uniqueid of site

What if a user downloads multiple sites together? Should it be a string of all uniques IDs in that case?

**Comment by loriabendroth** [comment]
@giorgichi yes, a string is good with "_" in between. Btw, "seperated" spelling needs to be corrected on weather page.

**Comment by akrherz** [comment]
@loriabendroth regarding
> we have blank cells in data columns not collected at certain sites. this makes sense to us but will confuse users likely.

Do you have a current example of this?  For example, the database appears to be clean now
```sql
select count(*) from soil_data where value = '';
 count 
-------
     0
select count(*) from agronomic_data where value = '';
 count 
-------
     0
```

**Comment by akrherz** [comment]
@loriabendroth regarding
> possible to add unique site ID to weather files as first column in addition to weather station names? 

Sorry, not really :(
