### ISSUE TITLE
Update TD homepage

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#92]
The TD homepage will be live to external users when CSCAP goes live. These changes should be made to it based on feedback from Jane and Ben:

- [x] Reduce size of picture to 1/3 of current. Center photo on page. 
- [x] Change title to "Future Site for Transforming Drainage Project Team Research Data"
- [x] Merge first two sentences and reword slightly to: 
This website will contain research data measured across a set of experiments carried out by the “Managing Water for Increased Resiliency of Drained Agricultural Landscapes” project or Transforming Drainage (hyperlink to https://transformingdrainage.org/). This project is funded from 2015-2020 by the United States Department of Agriculture, National Institute of Food and Agriculture (USDA-NIFA, Award No. 2015-68007-23193). Data will be publicly available after the project is completed.
- [x] replace logo at bottom with new attachment. 
![data_web_logos](https://user-images.githubusercontent.com/27225264/31787377-31bdcf22-b4d1-11e7-9aca-3d1b94bea9d6.png)
- [x] can plotting dropdowns not be visible to people not authorized to see TD data? Want everyone to see homepage but then only team members to see data.

**Comment by akrherz** [comment]
@loriabendroth regarding
> The TD homepage will be live to external users when CSCAP goes live

Why is that?

**Comment by loriabendroth** [comment]
@akrherz I want a hub for TD team to point to these next few years of where data will be. But I dont want any of data open to public so only want homepage visible. Also to show the projects we are responsible for as data team.

**Comment by loriabendroth** [comment]
@akrherz if painful to create diff permissions for subpages, could create slightly diff web addresses for subpages. I want homepage to stay "permanent" though.
